Repository wso2/docs-apim, pull requests merged in 2020-09, with the labels that each got.

#1814 Update secure-apis-using-mutual-ssl.md
  en/docs/learn/api-security/api-authentication/secure-apis-using-mutual-ssl.md
Labels: PR-Review/Pending Resolution

#1527 Gateway REST API Documentation
  en/docs/develop/product-apis/gateway-apis/gateway-v1/gateway-v1.md
  en/docs/develop/product-apis/gateway-apis/gateway-v1/gateway-v1.yaml
  en/docs/develop/product-apis/getting-started/guide-gateway-v1.md
  en/docs/develop/product-apis/restful-apis.md
  en/mkdocs.yml
Labels: PR-Review/Has Comments, PR-Review/Pending Resolution

#1749 update Analytics event streams and aggregations
  en/docs/learn/analytics/analytics-event-streams-and-aggregations.md
  en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/introducing-the-wso2-api-manager-statistics-model.md
  en/mkdocs.yml
Labels: PR-Review/In-progress

#1807 fix for https://github.com/wso2/docs-apim/issues/1719
  en/docs/assets/img/learn/attach-custom-in-sequence.png
  en/docs/learn/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
  en/docs/learn/api-security/authorization/role-based-access-control-using-xacml.md
Labels: PR-Review/In-progress

#1575 Update extending-scope-validation.md
  en/docs/learn/extensions/extending-scope-validation.md
Labels: PR-Review/Has Comments

#1769 Update configuration doc for 3.2.0
  en/docs/assets/img/learn/analytics-quick-setup.png
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: PR-Review/In-progress

#1887 Update faq.md corrected broken link
  en/docs/reference/faq.md
Labels: PR-Status/Rejected

#1900 IS as a KM doc
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Labels: PR/Reviewer-Updated

#1853 update extending KM docs and add custom keymmanager doc
  en/docs/administer/key-managers/configure-custom-connector.md
  en/docs/administer/key-managers/how-to-configure-key-cloak-connector.md
  en/docs/assets/attachments/administer/custom.auth.client.zip
  en/docs/develop/extending-api-manager/extending-key-management/extending-key-validation.md
  en/docs/develop/extending-api-manager/extending-key-management/extending-the-key-manager-interface.md
  en/mkdocs.yml
Labels: PR/Reviewer-Updated

#1695 Updated manage-user doc.
  en/docs/administer/managing-users-and-roles/managing-permissions.md
  en/docs/administer/managing-users-and-roles/managing-user-roles.md
  en/docs/assets/img/administer/add-new-role-mapping.png
  en/docs/assets/img/administer/add-role-permission.png
  en/docs/assets/img/administer/new-role-mapping.png
  en/docs/assets/img/administer/new-scope-mapping.png
Labels: PR-Review/Has Comments, PR/Reviewer-Updated

#1699 Workflow executor configurations
  en/docs/learn/design-api/advanced-topics/adding-an-api-state-change-workflow.md
Labels: PR-Review/Has Comments, PR/Reviewer-Updated

#1934 Adding per API log feature's and log4j2 UI manipulation docs
  en/docs/administer/logging-and-monitoring/logging/gw-api.yaml
  en/docs/administer/logging-and-monitoring/logging/setting-up-logging-per-api.md
  en/docs/administer/logging-and-monitoring/logging/setting-up-logging.md
  en/docs/assets/img/administer/add-logger.png
  en/docs/assets/img/administer/list-logger.png
  en/docs/assets/img/administer/logging.png
  en/docs/assets/img/administer/update-logger.png
Labels: PR/Reviewer-Updated

#1819 Updating the docs on "Creating and Uploading using WSO2 Integration Studio"
  en/docs/assets/img/learn/api-gateway/message-mediation/add-sequence-properties.png
  en/docs/assets/img/learn/api-gateway/message-mediation/composite-app-pom.png
  en/docs/assets/img/learn/api-gateway/message-mediation/create-new-sequence-2.png
  en/docs/assets/img/learn/api-gateway/message-mediation/create-new-sequence.png
  en/docs/assets/img/learn/api-gateway/message-mediation/esb-solution-project.png
  en/docs/assets/img/learn/api-gateway/message-mediation/integration-project.png
  en/docs/assets/img/learn/api-gateway/message-mediation/integration-studio.png
  en/docs/assets/img/learn/api-gateway/message-mediation/newsequence-xml.png
  en/docs/assets/img/learn/api-gateway/message-mediation/sequences.png
  en/docs/learn/api-gateway/message-mediation/creating-and-uploading-using-integration-studio.md
Labels: PR-Review/In-progress

#1842 Add redocly integration for admin api v1
  en/docs/develop/product-apis/admin-apis/admin-v1/admin-v1.yaml
  en/docs/develop/product-apis/restful-apis.md
Labels: PR-Review/Pending Resolution

#1811 Update docs for GDPR
  en/docs/install-and-setup/setup/security/general-data-protection-regulation-gdpr-for-wso2-api-manager.md
Labels: PR-Review/In-progress
