Repository wso2/docs-apim, pull requests merged in 2020-02, with the labels that each got.

#550 improve subscription workflow doc
  en/docs/Learn/ConsumeAPI/ManageSubscription/AdvancedTopics/adding-an-api-subscription-workflow.md
  en/docs/assets/img/Learn/workflow-subscription-admin-entry.png
  en/docs/assets/img/Learn/workflow-subscription-complete.png
  en/docs/assets/img/Learn/workflow-subscription-onhold.png
Labels: Review/Has Comments, Review/Pending Resolution

#708 fix for https://github.com/wso2/docs-apim/issues/607
  en/docs/Learn/APIMonetization/monetizing-an-api.md
Labels: Type/Bug

#617 Corrected internal links.
  en/docs/Learn/APISecurity/Authorization/role-based-access-control-using-xacml.md
  en/docs/assets/img/Learn/add-getorder-rule.png
  en/docs/assets/img/Learn/add-getorder-value.png
  en/docs/assets/img/Learn/add-new-entitlement-policy.png
  en/docs/assets/img/Learn/added-getorder.png
  en/docs/assets/img/Learn/attach-the-custom-sequence.png
  en/docs/assets/img/Learn/define-entitlement-rules.png
  en/docs/assets/img/Learn/enabling-roll-based-access-control.png
  en/docs/assets/img/Learn/entitlement-values.png
  en/docs/assets/img/Learn/login-and-subscribe-permission.png
  en/docs/assets/img/Learn/policy-administration.png
  en/docs/assets/img/Learn/publish-to-my-pdp.png
  en/docs/assets/img/Learn/save-ploicy.png
  en/docs/assets/img/Learn/test-service-by-try-option.png
  en/docs/assets/img/Learn/xacml-with-apim.png
Labels: Review/Has Comments, Review/Pending Resolution

#789 Updates based on doc reviews and bug fixes
  en/docs/administer/product-security/logins-and-passwords/working-with-encrypted-passwords.md
  en/docs/develop/wso2-admin-services.md
  en/docs/learn/consume-api/manage-application/sharing-applications/sharing-applications.md
Labels: Review/Has Comments
