Repository wso2/docs-apim, pull requests merged in 2020-08, with the labels that each got.

#1587 Fix for https://github.com/wso2/docs-apim/issues/1569
  en/docs/assets/attachments/get_started/petstore.json
  en/docs/assets/img/get_started/qsg-devportal.png
  en/docs/assets/img/get_started/qsg-petstore-response.png
  en/docs/assets/img/get_started/qsg-publisher.png
  en/docs/getting-started/quick-start-guide.md
Labels: API-M-3.2.0

#1566 Adding APICTL+Git Integration documentation
  en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
Labels: PR-Review/Has Comments, PR-Review/Pending Resolution

#1612 Fixes https://github.com/wso2/docs-apim/issues/1601
  en/docs/assets/img/learn/add-new-application-option.png
  en/docs/assets/img/learn/application-overview.png
  en/docs/assets/img/learn/applications-listing.png
  en/docs/assets/img/learn/create-new-application.png
  en/docs/learn/consume-api/manage-application/create-application.md
Labels: API-M-3.2.0

#1473 adding doc "PrivateJet mode for Microgateways"
  en/docs/assets/img/learn/privatejet-mode/architecture.png
  en/docs/assets/img/learn/privatejet-mode/devportal.png
  en/docs/assets/img/learn/privatejet-mode/environment.png
  en/docs/assets/img/learn/privatejet-mode/lifecycle_publish.png
  en/docs/assets/img/learn/privatejet-mode/tryout-Execute.png
  en/docs/assets/img/learn/privatejet-mode/tryout-console-gateway-selection.png
  en/docs/assets/img/learn/privatejet-mode/tryout-response.png
  en/docs/learn/api-microgateway/deploy-apis-in-privatejet-mode.md
  en/mkdocs.yml
Labels: PR-Review/Has Comments, PR-Review/Pending Resolution

#1633 fixes https://github.com/wso2/docs-apim/issues/1629
  en/docs/administer/product-security/configuring-transport-level-security.md
Labels: API-M-3.0.0

#1632 fixes https://github.com/wso2/docs-apim/issues/1629
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: API-M-3.1.0

#1630 fixes https://github.com/wso2/docs-apim/issues/1629
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: API-M-3.2.0

#1563 Adding document visibility feature to the docs
  en/docs/assets/img/learn/api-doc-visibility-dropdown.png
  en/docs/assets/img/learn/api-doc-visibility-selector.png
  en/docs/learn/design-api/advanced-topics/control-api-visibility-and-subscription-availability-in-developer-portal.md
  en/docs/learn/design-api/api-documentation/add-api-documentation.md
Labels: PR-Review/Has Comments, PR-Review/Pending Resolution

#1658 Updated Rate Limiting Policies doc.
  en/docs/assets/img/learn/add-condition-group.png
  en/docs/assets/img/learn/add-request-bandwith-advanced-policy.png
  en/docs/assets/img/learn/add-subscription-policy.png
  en/docs/assets/img/learn/new-advanced-throttling-tier.png
  en/docs/assets/img/learn/new-application-policy.png
  en/docs/assets/img/learn/new-conditional-groups.png
  en/docs/assets/img/learn/new-header-condition-regex.png
  en/docs/assets/img/learn/new-jwt-condition-regex.png
  en/docs/assets/img/learn/save-advanced-policy.png
  en/docs/assets/img/learn/save-new-application-policy.png
  en/docs/assets/img/learn/save-new-subscription-policy.png
  en/docs/learn/rate-limiting/adding-new-throttling-policies.md
Labels: PR-Review/Has Comments, PR-Review/Pending Resolution

#1557 Add changes related to scope management
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/after-attaching-multiple-scopes.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/api-scopes/apply-scope.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/api-scopes/create-a-new-scope.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/api-scopes/select-resource.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/api-scopes/start-creating-scope.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/attach-shared-scope.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/create-op-shared-scope.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/create-shared-scope.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/generate-keys.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/multiple-scopes-per-resource.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/resource-scope-api-definition.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/scopes-api-definition.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/select-resource.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/shared-scope-attached.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/subscribe-api.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/token-scopes-output.png
  en/docs/assets/img/learn/api-security/oauth2/oauth2-scopes/token-scopes.png
  en/docs/assets/img/learn/apply-scope.png
  en/docs/assets/img/learn/create-a-new-scope.png
  en/docs/assets/img/learn/select-resource.png
  en/docs/assets/img/learn/start-creating-scope.png
  en/docs/learn/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md
Labels: API-M-3.2.0, Docs/API-Security, PR-Review/Has Comments, PR-Review/Pending Resolution, enhancement

#1652 Update Microgateway label adding doc
  en/docs/assets/img/learn/add-microgateway-label-menu.png
  en/docs/assets/img/learn/add-microgateway-label.png
  en/docs/learn/api-microgateway/grouping-apis-with-labels.md
Labels: PR-Review/Has Comments, PR-Review/Pending Resolution

#1644 Update overview.md
  en/docs/getting-started/overview.md
Labels: PR-Review/Has Comments, PR-Review/Pending Resolution

#1611 Update 'About this Release' with analytics features
  en/docs/getting-started/about-this-release.md
Labels: PR-Review/Has Comments, PR-Review/Pending Resolution

#1700 fixes build break due to https://github.com/wso2/docs-apim/pull/1669
  en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/viewing-api-statistics.md
  en/docs/learn/api-security/threat-protection/bot-detection.md
  en/mkdocs.yml
Labels: API-M-3.2.0

#1663 Updated access-control doc.
  en/docs/assets/img/learn/new-advanced-throttling-query-conidtion.png
  en/docs/assets/img/learn/new-allow-specific-ip.png
  en/docs/assets/img/learn/new-allowed-ip-range.png
  en/docs/assets/img/learn/save-allow-specific-ip.png
  en/docs/learn/rate-limiting/access-control.md
  en/docs/learn/rate-limiting/adding-new-throttling-policies.md
  en/docs/learn/rate-limiting/introducing-throttling-use-cases.md
Labels: PR-Review/Has Comments, PR-Review/Pending Resolution

#1665 Bot detection doc fix
  en/docs/assets/img/learn/bot-data.png
  en/docs/assets/img/learn/bot-email-notification-menu.png
  en/docs/assets/img/learn/bot-email-notification-recipient-adding.png
  en/docs/assets/img/learn/bot-email-notification.png
  en/docs/learn/api-security/threat-protection/bot-detection.md
Labels: PR-Review/Has Comments, PR-Review/Pending Resolution

#1659 Update tenant theme doc
  en/docs/assets/img/learn/upload-tenant-theme.png
  en/docs/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
Labels: PR-Review/Has Comments, PR-Review/Pending Resolution

#1712 Reviewed and updated based on #1613 & #1702
  en/docs/administer/key-managers/configure-keycloak-connector.md
  en/docs/administer/key-managers/configure-okta-connector.md
  en/docs/administer/key-managers/configure-wso2is-connector.md
  en/docs/administer/key-managers/how-to-configure-key-cloak-connector.md
  en/docs/administer/key-managers/how-to-configure-okta-connector.md
  en/docs/administer/key-managers/how-to-configure-wso2is-connector.md
  en/docs/administer/key-managers/overview.md
  en/docs/assets/attachments/administer/wso2is-km-connector-1.0.15.zip
  en/docs/assets/img/administer/add-km-overview.png
  en/docs/assets/img/administer/multiple-km-token-validation.png
  en/mkdocs.yml
Labels: API-M-3.2.0

#1722 Reviewed and updated
  en/docs/getting-started/overview.md
  en/docs/index.md
  en/docs/install-and-setup/setup/distributed-deployment/configure-a-third-party-key-manager.md
  en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
  en/docs/learn/api-gateway/overview-of-the-api-gateway.md
  en/docs/learn/api-microgateway/grouping-apis-with-labels.md
  en/docs/learn/api-security/api-authentication/api-authentication-overview.md
  en/mkdocs.yml
Labels: API-M-3.2.0

#1634 fix for https://github.com/wso2/docs-apim/issues/1619
  en/docs/getting-started/overview.md
Labels: API-M-3.1.0, PR-Review/Has Comments, PR-Review/Pending Resolution

#1745 fix for https://github.com/wso2/docs-apim/issues/1631 part2
  en/docs/assets/img/develop/api_categories_dropdown.png
  en/docs/assets/img/develop/attach_category.png
  en/docs/assets/img/develop/devportal_listing.png
  en/docs/assets/img/develop/new_add_category.png
  en/docs/assets/img/develop/new_api_category_left_tag.png
  en/docs/assets/img/develop/new_click_add_category.png
  en/docs/assets/img/learn/api_categories_dropdown.png
  en/docs/assets/img/learn/attach_category.png
  en/docs/assets/img/learn/devportal_listing.png
  en/docs/assets/img/learn/new_add_category.png
  en/docs/develop/customizations/customizing-the-developer-portal/customize-api-listing/api-category-based-grouping.md
Labels: API-M-3.2.0

#1716 Applicationkeys
  en/docs/administer/key-managers/configure-keycloak-connector.md
  en/docs/administer/key-managers/configure-okta-connector.md
  en/docs/administer/key-managers/configure-wso2is-connector.md
  en/docs/administer/key-managers/how-to-configure-key-cloak-connector.md
  en/docs/assets/img/learn/keycloak-generate-keys.png
  en/docs/assets/img/learn/okta-application-key-generation.png
  en/docs/learn/consume-api/manage-application/generate-keys/generate-api-keys.md
  en/mkdocs.yml
Labels: PR-Review/In-progress

#1753 Introspect
  en/docs/administer/key-managers/configure-keycloak-connector.md
  en/docs/administer/key-managers/configure-okta-connector.md
Labels: PR-Review/In-progress

#1762 Fix docs in References/Samples
  en/docs/assets/img/reference/sample-subscription-tiers.png
  en/docs/reference/samples/api-development-sample/collaborative-api-development-sample.md
  en/docs/reference/samples/api-development-sample/development-of-developer-optimized-apis-sample.md
  en/docs/reference/samples/api-development-sample/managing-apis-sample.md
  en/docs/reference/samples/api-governance-sample.md
  en/docs/reference/samples/api-lifecycle-management-sample.md
  en/docs/reference/samples/api-rate-limiting-sample.md
  en/docs/reference/samples/api-rate-monetization-sample.md
  en/docs/reference/samples/api-security-sample.md
  en/docs/reference/samples/api-versioning-sample.md
Labels: API-M-3.2.0, API-M-Master

#1795 PR review for https://github.com/wso2/docs-apim/pull/1793
  en/docs/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster.md
Labels: API-M-3.2.0

#1801 update connection diagrams
  en/docs/assets/img/setup-and-install/dev-portal-connections.png
  en/docs/assets/img/setup-and-install/gateway-connections.png
  en/docs/assets/img/setup-and-install/key-manager-connections.png
  en/docs/assets/img/setup-and-install/publisher-connections.png
  en/docs/assets/img/setup-and-install/traffic-manager-connections.png
Labels: PR-Review/Has Comments

#1693 update distributed deployment steps and active active steps
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
  en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
  en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md
Labels: PR-Review/Has Comments, PR-Review/Pending Resolution
