Repository wso2/docs-apim, pull requests merged in 2020-11, with the labels that each got.

#2115 [3.1.0] Modify the configuration to enable notifications
  en/docs/learn/design-api/api-versioning/enabling-notifications.md
Labels: API-M-3.1.0, Docs/SyncPR-Pending, Docs/Waiting on SME, PR-Review/Phase-1

#2140 Added in a missing congif to deployment.toml of IS
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: Docs/Waiting on SME

#2116 [3.0.0] Update token persistence document
  en/docs/learn/api-security/oauth2/token-persistence.md
Labels: API-M-3.0.0, Docs/Waiting on SME, PR-Review/Pending Resolution, PR-Review/Phase-1, PR-Review/Phase-2, PR/Reviewer-Updated

#2068 [3.1.0] Add docs to configure IS as extenral IDP using OIDC and SAML
  en/docs/assets/img/setup-and-install/claim-configuration-in-service-provider-for-saml2-sso.png
  en/docs/assets/img/setup-and-install/claim-configuration-in-service-provider.png
  en/docs/assets/img/setup-and-install/identity-provider-configuration-for-saml-sso.png
  en/docs/assets/img/setup-and-install/identity-provider-configuration-for-sso.png
  en/docs/assets/img/setup-and-install/jit-provisioning-for-sso.png
  en/docs/assets/img/setup-and-install/local-and-outbound-authentication-configuration-for-sso.png
  en/docs/assets/img/setup-and-install/role-mapping-for-sso.png
  en/docs/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-oidc.md
  en/docs/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-saml.md
  en/mkdocs.yml
Labels: PR-Review/Pending Resolution, PR-Review/Phase-1, PR-Review/Phase-2, PR/Reviewer-Updated

#2084 Add information regarding the removal of support for opaque access tokens
  en/docs/assets/img/learn/api-credentials.png
  en/docs/assets/img/learn/edit-application-grant-types.png
  en/docs/assets/img/learn/from-existing-app.png
  en/docs/assets/img/learn/key-gen-wizard-access.png
  en/docs/assets/img/learn/key-gen-wizard-create-app.png
  en/docs/assets/img/learn/key-gen-wizard-generate-keys.png
  en/docs/assets/img/learn/key-gen-wizard-subscribe.png
  en/docs/assets/img/learn/key-gen-wizard.png
  en/docs/assets/img/learn/key-generation-wizard.png
  en/docs/assets/img/learn/select-api-dev-portal.png
  en/docs/assets/img/learn/subscribe-to-app.png
  en/docs/assets/img/learn/subscription-list.png
  en/docs/assets/img/learn/unsubscribe.png
  en/docs/getting-started/about-this-release.md
  en/docs/getting-started/key-concepts.md
  en/docs/learn/consume-api/manage-subscription/subscribe-to-an-api.md
Labels: PR/Reviewer-Updated

#2189 PR sync for https://github.com/wso2/docs-apim/pull/2151
  en/docs/learn/analytics/overview-of-api-analytics.md
Labels: PR-Review/Phase-1, PR-Review/Phase-2, PR/Reviewer-Updated

#2190 PR sync for https://github.com/wso2/docs-apim/pull/2139
  en/docs/administer/key-managers/configure-auth0-connector.md
Labels: PR-Review/Phase-1, PR/Reviewer-Updated

#2177 Updating deployment.toml configs for Gateway
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
Labels: Docs/Waiting on SME

#2178 Updating deployment.toml configs for Gateway
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
Labels: Docs/Waiting on SME

#2191 [3.1.0] Update the tenants windows migration scripts
  en/docs/assets/attachments/install-and-setup/apim200_to_apim310_gateway_artifact_migrator_for_tenants.ps1
  en/docs/assets/attachments/install-and-setup/apim210_to_apim310_gateway_artifact_migrator_for_tenants.ps1
  en/docs/assets/attachments/install-and-setup/apim220_to_apim310_gateway_artifact_migrator_for_tenants.ps1
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
Labels: Docs/Waiting on SME

#2194 PR sync for https://github.com/wso2/docs-apim/pull/2179
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
  en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
Labels: PR-Review/Phase-1

#2073 [3.0.0] Add docs to configure IS as extenral IDP using OIDC and SAML
  en/docs/assets/img/setup-and-install/claim-configuration-in-service-provider-for-saml2-sso.png
  en/docs/assets/img/setup-and-install/claim-configuration-in-service-provider.png
  en/docs/assets/img/setup-and-install/enable-tenant-domain-in-local-sub-identifier.png
  en/docs/assets/img/setup-and-install/identity-provider-configuration-for-saml-sso.png
  en/docs/assets/img/setup-and-install/identity-provider-configuration-for-sso.png
  en/docs/assets/img/setup-and-install/jit-provisioning-for-sso.png
  en/docs/assets/img/setup-and-install/local-and-outbound-authentication-configuration-for-sso.png
  en/docs/assets/img/setup-and-install/local-and-outbound-authentication-configuration.png
  en/docs/assets/img/setup-and-install/role-configuration-for-sso.png
  en/docs/assets/img/setup-and-install/role-mapping-for-sso.png
  en/docs/assets/img/setup-and-install/saas.png
  en/docs/assets/img/setup-and-install/saml-configuration-in-service-provider.png
  en/docs/assets/img/setup-and-install/upload-certificate-in-SP-for-saml2-sso.png
  en/docs/install-and-setup/sso/configure-identity-server-as-external-idp-using-oidc.md
  en/docs/install-and-setup/sso/configure-identity-server-as-external-idp-using-saml.md
  en/mkdocs.yml
Labels: PR-Review/Pending Resolution, PR-Review/Phase-1, PR-Review/Phase-2, PR/Reviewer-Updated

#2131 [3.2.0] Modify the configuration to enable notifications
  en/docs/learn/design-api/api-versioning/enabling-notifications.md
Labels: PR-Review/Phase-1

#2201 Update Keymanager compatibility in Release Notes
  en/docs/getting-started/about-this-release.md
Labels: PR-Review/Phase-1, PR/Reviewer-Updated

#2209 [3.1.0] Add a documentation for APIM Analytics Encryption with Secure Vault
  en/docs/learn/analytics/securing-sensitive-data-via-the-secure-vault.md
  en/mkdocs.yml
Labels: PR-Review/Pending Resolution

#2228 Test and update screenshot - Issue #2199
  en/docs/assets/img/learn/changing-the-logo-and-header3.png
  en/docs/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
  en/docs/develop/customizations/customizing-the-developer-portal/styling-the-logo-and-header.md
Labels: PR-Review/Phase-1

#2226 Added a note to create non-secure APIs.
  en/docs/assets/img/learn/invoke-api-without-access-token.png
  en/docs/learn/design-api/create-api/create-a-rest-api.md
Labels: PR-Review/Phase-1

#2227 Added a note to create non-secure APIs.
  en/docs/assets/img/learn/invoke-api-without-access-token.png
  en/docs/learn/design-api/create-api/create-a-rest-api.md
Labels: PR-Review/Phase-1

#2240 Fix "Admin Services" page - #1851
  en/docs/assets/img/develop/discover-admin-services.png
  en/docs/develop/wso2-admin-services.md
Labels: PR-Review/Phase-1

#2289 fixes https://github.com/wso2/docs-apim/issues/1146
  en/docs/learn/analytics/managing-alerts-with-real-time-analytics/configuring-alerts.md
Labels: API-M-3.0.0, Issue/PR-sent

#2293 fixes https://github.com/wso2/docs-apim/issues/1146
  en/docs/learn/analytics/managing-alerts-with-real-time-analytics/configuring-alerts.md
Labels: API-M-3.1.0, Issue/PR-sent

#2294 fixes https://github.com/wso2/docs-apim/issues/1146
  en/docs/learn/analytics/configuring-alerts.md
Labels: API-M-3.2.0, Issue/PR-sent

#2296 fix for https://github.com/wso2/docs-apim/issues/1146
  en/docs/learn/analytics/configuring-alerts.md
Labels: API-M-Master, Issue/PR-sent

#2311 PR sync for https://github.com/wso2/docs-apim/pull/2262
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
Labels: API-M-Master, Issue/PR-sent

#2312 [Master] Add note to support group replication
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
Labels: API-M-Master

#2321 documentation updatation
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: PR-Review/In-progress

#2374 fix for https://github.com/wso2/docs-apim/issues/2357
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: API-M-3.0.0

#2373 fix for https://github.com/wso2/docs-apim/issues/2357
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: API-M-3.1.0

#2372 Fix for https://github.com/wso2/docs-apim/issues/2357
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: API-M-3.2.0

#2358 fix for https://github.com/wso2/docs-apim/issues/2357
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: API-M-Master

#2208 [3.2.0] Fix throttle condition group configs Configuration Catalog
  en/docs/reference/config-catalog.md
Labels: PR-Review/In-progress

#2207 [master] Fix throttle condition group configs Configuration Catalog
  en/docs/reference/config-catalog.md
Labels: API-M-Master, PR-Review/Phase-1

#2388 Update theming docs
  en/docs/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
Labels: PR-Review/In-progress

#2211 [3.2.0] Adding Docs for Setting up a user for the Admin Portal
  en/docs/administer/managing-users-and-roles/managing-users-for-admin-portal.md
  en/docs/assets/img/administer/add-admin-manager-role-to-user.png
  en/docs/assets/img/administer/add-admin-portal-role.png
  en/docs/assets/img/administer/add-manager-user.png
  en/docs/assets/img/administer/minimum-version-admin-portal.png
  en/mkdocs.yml
Labels: API-M-3.2.0, PR-Review/Pending Resolution, PR-Review/Phase-1, PR-Review/Phase-2, PR/Reviewer-Updated

#2210 Remove NFS instructions for TM
  en/docs/assets/img/setup-and-install/traffic-manager-connections.png
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
  en/docs/reference/config-catalog.md
Labels: API-M-4.0.0, API-M-Master, PR/Reviewer-Updated

#2420 fix for https://github.com/wso2/docs-apim/issues/2413
  en/docs/install-and-setup/installation-guide/installing-the-product/installing-the-binary/installing-as-a-linux-service.md
Labels: API-M-3.0.0, Issue/PR-sent

#2419 fix for https://github.com/wso2/docs-apim/issues/2413
  en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-as-a-linux-service.md
Labels: API-M-Master, Issue/PR-sent

#2418 fix for https://github.com/wso2/docs-apim/issues/2413
  en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-as-a-linux-service.md
Labels: API-M-3.1.0, Issue/PR-sent

#2417 fix for https://github.com/wso2/docs-apim/issues/2413
  en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-as-a-linux-service.md
Labels: API-M-3.2.0, Issue/PR-sent

#2421 Update theming docs
  en/docs/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
Labels: PR-Review/In-progress

#2428 Token expiry doc master
  en/docs/assets/img/learn/generate-token-with-custom-validity.png
  en/docs/learn/consume-api/manage-application/generate-keys/generate-api-keys.md
  en/docs/learn/consume-api/manage-application/generate-keys/obtain-access-token/changing-the-default-token-expiration-time.md
Labels: API-M-4.0.0

#2223 add application level token expiry docs
  en/docs/assets/img/learn/generate-token-with-custom-validity.png
  en/docs/learn/consume-api/manage-application/generate-keys/generate-api-keys.md
  en/docs/learn/consume-api/manage-application/generate-keys/obtain-access-token/changing-the-default-token-expiration-time.md
Labels: API-M-3.2.0, Type/WUM
