Repository wso2/docs-apim, pull requests merged in 2020-12, with the labels that each got.

#2429 Update 4.0.0 release note
  en/docs/getting-started/about-this-release.md
Labels: API-M-4.0.0

#2386 [3.2.0] Update docs for notification enabling
  en/docs/learn/design-api/api-versioning/enabling-notifications.md
  en/docs/reference/config-catalog.md
  en/docs/reference/configs.json
  en/tools/config-catalog-generator/data/apim.notification.toml
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/dist/config-catalog.md
Labels: API-M-3.2.0, Issue/PR-sent, PR-Review/Pending Resolution, PR-Review/Phase-1

#2390 [3.1.0] Update docs for notification enabling
  en/docs/learn/design-api/api-versioning/enabling-notifications.md
  en/docs/reference/config-catalog.md
  en/docs/reference/configs.json
  en/tools/config-catalog-generator/data/apim.cache.gateway_token.toml
  en/tools/config-catalog-generator/data/apim.notification.toml
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/dist/config-catalog.md
Labels: API-M-3.1.0, Issue/PR-sent, PR-Review/Phase-1

#2391 [3.0.0] Update docs for notification enabling
  en/docs/learn/design-api/api-versioning/enabling-notifications.md
  en/docs/reference/config-catalog.md
  en/docs/reference/configs.json
  en/tools/config-catalog-generator/data/apim.cache.gateway_token.toml
  en/tools/config-catalog-generator/data/apim.notification.toml
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/dist/config-catalog.md
Labels: API-M-3.0.0, Issue/PR-sent, PR-Review/Pending Resolution, PR-Review/Phase-1

#2438 change position of notes
  en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md
  en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/try-out-using-postman.md
Labels: API-M-4.0.0, API-M-Master

#2437 Reviewed GraphQL Console page
  en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md
Labels: API-M-3.2.0, PR-Review/Phase-1, PR-Review/Phase-2

#2200 [master] Update Monitoring Server Health Docs
  en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
  en/mkdocs.yml
Labels: API-M-Master, Docs/Waiting on SME, PR-Review/Phase-1, PR-Review/Phase-2, PR/Reviewer-Updated

#2168 [3.2.0] Update Monitoring Server Health Docs
  en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
  en/mkdocs.yml
Labels: API-M-3.2.0, PR-Review/Phase-1, PR-Review/Phase-2, PR/Reviewer-Updated

#2430 [master] Fix and sync config catalog inconsistencies
  en/docs/reference/config-catalog.md
  en/docs/reference/configs.json
  en/tools/config-catalog-generator/data/apim.jwt.issuer.claim_mapping.toml
  en/tools/config-catalog-generator/data/apim.jwt.issuer.jwks.toml
  en/tools/config-catalog-generator/data/apim.jwt.issuer.toml
  en/tools/config-catalog-generator/data/apim.open_tracer.toml
  en/tools/config-catalog-generator/data/apim.sdk.toml
  en/tools/config-catalog-generator/data/apim.throttling.toml
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.custom.bandwidth.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.custom.resource_volume.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.custom.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.custom.users.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.demo.bandwidth.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.demo.resource_volume.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.demo.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.demo.users.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.smb.bandwidth.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.smb.resource_volume.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.smb.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.smb.users.toml
  en/tools/config-catalog-generator/data/multi_tenancy.cloud_services.toml
  en/tools/config-catalog-generator/data/multi_tenancy.stratos.manager_service.toml
  en/tools/config-catalog-generator/data/multi_tenancy.stratos.paypal.toml
  en/tools/config-catalog-generator/data/multi_tenancy.stratos.toml
  en/tools/config-catalog-generator/data/multi_tenancy.throttling_manager_tasks.parameters.toml
  en/tools/config-catalog-generator/data/multi_tenancy.throttling_manager_tasks.toml
  en/tools/config-catalog-generator/data/multi_tenancy.usage_agent.data_persistence_task.toml
  en/tools/config-catalog-generator/data/tenant_mgt.toml
  en/tools/config-catalog-generator/dist/config-catalog.md
  en/tools/config-catalog-generator/templates/_configs.njk
  en/tools/config-catalog-generator/templates/index.njk
Labels: API-M-Master

#2434 [3.2.0] Fix and sync config catalog inconsistencies
  en/docs/reference/config-catalog.md
  en/docs/reference/configs.json
  en/tools/config-catalog-generator/data/apim.jwt.issuer.claim_mapping.toml
  en/tools/config-catalog-generator/data/apim.jwt.issuer.jwks.toml
  en/tools/config-catalog-generator/data/apim.jwt.issuer.toml
  en/tools/config-catalog-generator/data/apim.open_tracer.toml
  en/tools/config-catalog-generator/data/apim.sdk.toml
  en/tools/config-catalog-generator/data/apim.throttling.toml
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.custom.bandwidth.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.custom.resource_volume.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.custom.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.custom.users.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.demo.bandwidth.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.demo.resource_volume.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.demo.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.demo.users.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.smb.bandwidth.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.smb.resource_volume.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.smb.toml
  en/tools/config-catalog-generator/data/multi_tenancy.billing.package.smb.users.toml
  en/tools/config-catalog-generator/data/multi_tenancy.cloud_services.toml
  en/tools/config-catalog-generator/data/multi_tenancy.stratos.manager_service.toml
  en/tools/config-catalog-generator/data/multi_tenancy.stratos.paypal.toml
  en/tools/config-catalog-generator/data/multi_tenancy.stratos.toml
  en/tools/config-catalog-generator/data/multi_tenancy.throttling_manager_tasks.parameters.toml
  en/tools/config-catalog-generator/data/multi_tenancy.throttling_manager_tasks.toml
  en/tools/config-catalog-generator/data/multi_tenancy.usage_agent.data_persistence_task.toml
  en/tools/config-catalog-generator/data/tenant_mgt.toml
  en/tools/config-catalog-generator/dist/config-catalog.md
  en/tools/config-catalog-generator/templates/_configs.njk
  en/tools/config-catalog-generator/templates/index.njk
Labels: API-M-3.2.0

#2439 [3.1.0] Fix and sync config catalog inconsistencies
  en/docs/reference/config-catalog.md
  en/docs/reference/configs.json
  en/tools/config-catalog-generator/data/apim.analytics.toml
  en/tools/config-catalog-generator/data/apim.analytics.url_group.toml
  en/tools/config-catalog-generator/data/apim.cache.jwt_claim.toml
  en/tools/config-catalog-generator/data/apim.cache.publisher_roles.toml
  en/tools/config-catalog-generator/data/apim.cache.scopes.toml
  en/tools/config-catalog-generator/data/apim.cache.tags.toml
  en/tools/config-catalog-generator/data/apim.cors.toml
  en/tools/config-catalog-generator/data/apim.devportal.toml
  en/tools/config-catalog-generator/data/apim.key_manager.toml
  en/tools/config-catalog-generator/data/apim.oauth_config.toml
  en/tools/config-catalog-generator/data/apim.open_tracer.toml
  en/tools/config-catalog-generator/data/apim.sdk.toml
  en/tools/config-catalog-generator/data/apim.throttling.toml
  en/tools/config-catalog-generator/data/apim.throttling.url_group.toml
  en/tools/config-catalog-generator/data/apim.token.revocation.toml
  en/tools/config-catalog-generator/data/apim.workflow.toml
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/dist/config-catalog.md
  en/tools/config-catalog-generator/templates/_configs.njk
  en/tools/config-catalog-generator/templates/index.njk
Labels: API-M-3.1.0

#2440 [3.0.0] Fix and sync config catalog inconsistencies
  en/docs/reference/config-catalog.md
  en/docs/reference/configs.json
  en/tools/config-catalog-generator/data/apim.analytics.toml
  en/tools/config-catalog-generator/data/apim.analytics.url_group.toml
  en/tools/config-catalog-generator/data/apim.cache.jwt_claim.toml
  en/tools/config-catalog-generator/data/apim.cache.publisher_roles.toml
  en/tools/config-catalog-generator/data/apim.cache.scopes.toml
  en/tools/config-catalog-generator/data/apim.cache.tags.toml
  en/tools/config-catalog-generator/data/apim.cors.toml
  en/tools/config-catalog-generator/data/apim.devportal.toml
  en/tools/config-catalog-generator/data/apim.key_manager.toml
  en/tools/config-catalog-generator/data/apim.oauth_config.toml
  en/tools/config-catalog-generator/data/apim.open_tracer.toml
  en/tools/config-catalog-generator/data/apim.sdk.toml
  en/tools/config-catalog-generator/data/apim.throttling.toml
  en/tools/config-catalog-generator/data/apim.throttling.url_group.toml
  en/tools/config-catalog-generator/data/apim.token.revocation.toml
  en/tools/config-catalog-generator/data/apim.workflow.toml
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/dist/config-catalog.md
  en/tools/config-catalog-generator/templates/_configs.njk
  en/tools/config-catalog-generator/templates/index.njk
Labels: API-M-3.0.0

#2129 Add docs to configure IS as IDP using OIDC and SAML
  en/docs/assets/img/setup-and-install/claim-configuration-in-service-provider-for-saml2-sso.png
  en/docs/assets/img/setup-and-install/claim-configuration-in-service-provider.png
  en/docs/assets/img/setup-and-install/enable-tenant-domain-in-local-sub-identifier.png
  en/docs/assets/img/setup-and-install/identity-provider-configuration-for-saml-sso.png
  en/docs/assets/img/setup-and-install/identity-provider-configuration-for-sso.png
  en/docs/assets/img/setup-and-install/jit-provisioning-for-sso.png
  en/docs/assets/img/setup-and-install/local-and-outbound-authentication-configuration-for-sso.png
  en/docs/assets/img/setup-and-install/role-mapping-for-sso.png
  en/docs/assets/img/setup-and-install/saas.png
  en/docs/assets/img/setup-and-install/saml-configuration-in-service-provider.png
  en/docs/assets/img/setup-and-install/upload-certificate-in-SP-for-saml2-sso.png
  en/docs/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-oidc.md
  en/docs/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-saml.md
  en/mkdocs.yml
Labels: API-M-Master, PR-Review/In-progress

#2128 [3.2.0] Add docs to configure IS as extenral IDP using OIDC and SAML
  en/docs/assets/img/setup-and-install/claim-configuration-in-service-provider-for-saml2-sso.png
  en/docs/assets/img/setup-and-install/claim-configuration-in-service-provider.png
  en/docs/assets/img/setup-and-install/enable-tenant-domain-in-local-sub-identifier.png
  en/docs/assets/img/setup-and-install/identity-provider-configuration-for-saml-sso.png
  en/docs/assets/img/setup-and-install/identity-provider-configuration-for-sso.png
  en/docs/assets/img/setup-and-install/jit-provisioning-for-sso.png
  en/docs/assets/img/setup-and-install/local-and-outbound-authentication-configuration-for-sso.png
  en/docs/assets/img/setup-and-install/role-mapping-for-sso.png
  en/docs/assets/img/setup-and-install/saas.png
  en/docs/assets/img/setup-and-install/saml-configuration-in-service-provider.png
  en/docs/assets/img/setup-and-install/upload-certificate-in-SP-for-saml2-sso.png
  en/docs/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-oidc.md
  en/docs/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-saml.md
  en/mkdocs.yml
Labels: API-M-3.2.0

#2251 Update OAS 3.0 definitions of Portal APIs
  en/docs/develop/product-apis/admin-apis/admin-v1/admin-v1.yaml
  en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
  en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml
Labels: API-M-4.0.0, API-M-Master

#2453 [master] Add sample opentracer configs
  en/docs/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing.md
Labels: API-M-Master

#2278 [3.2.0] Add security guidelines for admin accounts
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Labels: API-M-3.2.0, PR-Review/Phase-1

#2449 [master] Add note for NFS configs
  en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
Labels: API-M-Master, Docs/Waiting on SME, PR-Review/In-progress

#2431 [master] Add security guidelines for admin accounts
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Labels: API-M-Master

#2432 [3.1.0] Add security guidelines for admin accounts
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Labels: API-M-3.1.0

#2276 Add collation info for ANALYTICS_DB on primary key violations
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: API-M-3.1.0, Issue/PR-sent, PR/Reviewer-Updated

#2460 [3.1.0] Update Monitoring Server Health Docs
  en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
  en/mkdocs.yml
Labels: API-M-3.1.0, PR-Review/Phase-1, PR-Review/Phase-2

#2060 Move supported cipher suites document under APIM doc space
  en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
  en/mkdocs.yml
Labels: API-M-3.2.0, PR-Review/Pending Resolution

#2444 [master] Update docs for analytics migration from 3.1.0
  en/docs/assets/img/setup-and-install/analytics_dashboard_export.png
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
Labels: API-M-Master

#2442 [3.2.0] Update docs for analytics migration from 3.1.0
  en/docs/assets/img/setup-and-install/analytics_dashboard_export.png
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
Labels: API-M-3.2.0

#2465 Move supported cipher suites document under APIM doc space
  en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
  en/mkdocs.yml
Labels: API-M-Master

#2466 Add collation info for ANALYTICS_DB on primary key violations
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: API-M-Master

#2473 fixes https://github.com/wso2/docs-apim/issues/2464
  en/docs/administer/product-administration/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md
Labels: API-M-3.0.0, Issue/PR-sent

#2470 fix for https://github.com/wso2/docs-apim/issues/2464
  en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md
Labels: API-M-Master, Issue/PR-sent

#2472 fixes https://github.com/wso2/docs-apim/issues/2464
  en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md
Labels: API-M-3.1.0, Issue/PR-sent

#2471 fixes https://github.com/wso2/docs-apim/issues/2464
  en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md
Labels: API-M-3.2.0, Issue/PR-sent

#2476 Fixes https://github.com/wso2/docs-apim/issues/2467
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
Labels: API-M-Master, PR/Reviewer-Updated

#2475 Fixes https://github.com/wso2/docs-apim/issues/2467 in APIM 3.2.0 docs
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
Labels: API-M-3.2.0

#2469 Fixes https://github.com/wso2/docs-apim/issues/2467 in APIM 3.1.0 docs
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
Labels: API-M-3.1.0

#2468 Fixes https://github.com/wso2/docs-apim/issues/2467 in APIM 3.0.0 docs
  en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
  en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
  en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
  en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
  en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
Labels: API-M-3.0.0

#2462 [3.1.0] Fix issue in description of database collation for analytics
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: API-M-3.1.0

#2463 [3.0.0] Add collation info for ANALYTICS_DB on primary key violations
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300.md
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: API-M-3.0.0, PR-Review/Phase-1, PR/Reviewer-Updated

#2235 Add info on Changing passwords - Issue #2065
  en/docs/administer/managing-users-and-roles/managing-users.md
  en/docs/assets/img/administer/change-password.png
  en/docs/assets/img/administer/list-user-roles.png
Labels: API-M-Master

#2258 Remove duplicate content regarding shared artifacts
  en/docs/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster.md
  en/docs/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts.md
  en/mkdocs.yml
Labels: API-M-Master, PR-Review/Pending Resolution, PR-Review/Phase-1

#2362 [master] Update monetization docs
  en/docs/assets/img/learn/monetization_create_connected_account.png
  en/docs/assets/img/learn/monetization_customer_created.png
  en/docs/assets/img/learn/monetization_enable_oauth.png
  en/docs/assets/img/learn/monetization_new_customer_details.png
  en/docs/assets/img/learn/monetization_obtain_keys.png
  en/docs/assets/img/learn/monetization_pricing_bill.png
  en/docs/assets/img/learn/monetization_shared_customer.png
  en/docs/assets/img/learn/monetization_shared_customer_details.png
  en/docs/assets/img/learn/monetization_subscription.png
  en/docs/learn/api-monetization/monetizing-an-api.md
Labels: API-M-Master, PR-Review/In-progress

#2351 [3.2.0] Update monetization docs
  en/docs/assets/img/learn/monetization_create_connected_account.png
  en/docs/assets/img/learn/monetization_customer_created.png
  en/docs/assets/img/learn/monetization_enable_oauth.png
  en/docs/assets/img/learn/monetization_new_customer_details.png
  en/docs/assets/img/learn/monetization_obtain_keys.png
  en/docs/assets/img/learn/monetization_pricing_bill.png
  en/docs/assets/img/learn/monetization_shared_customer.png
  en/docs/assets/img/learn/monetization_shared_customer_details.png
  en/docs/assets/img/learn/monetization_subscription.png
  en/docs/learn/api-monetization/monetizing-an-api.md
Labels: API-M-3.2.0

#2375 [3.1.0] Update monetization docs
  en/docs/assets/img/learn/monetization_create_connected_account.png
  en/docs/assets/img/learn/monetization_customer_created.png
  en/docs/assets/img/learn/monetization_enable_oauth.png
  en/docs/assets/img/learn/monetization_new_customer_details.png
  en/docs/assets/img/learn/monetization_obtain_keys.png
  en/docs/assets/img/learn/monetization_pricing_bill.png
  en/docs/assets/img/learn/monetization_shared_customer.png
  en/docs/assets/img/learn/monetization_shared_customer_details.png
  en/docs/assets/img/learn/monetization_subscription.png
  en/docs/learn/api-monetization/monetizing-an-api.md
Labels: API-M-3.1.0

#2378 [3.0.0] Update monetization docs
  en/docs/assets/img/learn/monetization_create_connected_account.png
  en/docs/assets/img/learn/monetization_customer_created.png
  en/docs/assets/img/learn/monetization_enable_oauth.png
  en/docs/assets/img/learn/monetization_new_customer_details.png
  en/docs/assets/img/learn/monetization_obtain_keys.png
  en/docs/assets/img/learn/monetization_pricing_bill.png
  en/docs/assets/img/learn/monetization_shared_customer.png
  en/docs/assets/img/learn/monetization_shared_customer_details.png
  en/docs/assets/img/learn/monetization_subscription.png
  en/docs/learn/api-monetization/monetizing-an-api.md
Labels: API-M-3.0.0

#2478 Updating architecture diagrams
  en/docs/getting-started/overview.md
  en/docs/learn/api-security/oauth2/grant-types/authorization-code-grant.md
Labels: API-M-3.1.0

#2477 [4.0.0] Displaying comments with User Information in REST APIs
  en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
Labels: API-M-4.0.0, API-M-Master

#2445 Fixing 64x download location
  en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
Labels: API-M-3.1.0

#2441 [Docs] Documentation changes related to the feature of resolving env-parameters at server-side while importing an API project
  en/docs/learn/api-controller/advanced-topics/configuring-different-endpoint-types.md
  en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md
Labels: API-M-4.0.0, API-M-Master, Docs/Waiting on SME, PR-Review/In-progress

#2488 Updated the image paths
  en/docs/learn/api-security/oauth2/access-token-types/jwt-tokens.md
Labels: API-M-3.2.0

#2485 Re-write Overview page
  en/docs/administer/managing-users-and-roles/managing-user-roles.md
  en/docs/assets/css/theme.css
  en/docs/assets/img/get_started/analytics.png
  en/docs/assets/img/get_started/basic-architecture.png
  en/docs/assets/img/get_started/build.png
  en/docs/assets/img/get_started/developer-portal-overview.png
  en/docs/assets/img/get_started/find.png
  en/docs/assets/img/get_started/key-manager-overview.png
  en/docs/assets/img/get_started/overview-analytics.png
  en/docs/assets/img/get_started/portals.png
  en/docs/assets/img/get_started/rate-limiting.png
  en/docs/assets/img/get_started/security.png
  en/docs/assets/img/get_started/traffic-manager-overview.png
  en/docs/assets/img/learn/overviewpage-rest-api.jpg
  en/docs/getting-started/basic-architecture.md
  en/docs/getting-started/overview.md
  en/docs/install-and-setup/setup/distributed-deployment/configure-a-third-party-key-manager.md
  en/docs/learn/api-security/oauth2/grant-types/password-grant.md
  en/docs/learn/design-api/advanced-topics/block-subscription-to-an-api.md
  en/docs/learn/design-api/create-api/create-a-rest-api.md
  en/mkdocs.yml
Labels: API-M-3.2.0, PR/Reviewer-Updated

#2267 Add details to keep system roles without being deleted during the provisioning process
  en/docs/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-saml.md
Labels: API-M-Master, CEXP, PR-Review/Pending Resolution, PR/Reviewer-Updated

#2234 Added analytics configuration description.
  en/docs/assets/img/learn/analytics-standard-architecture-diagram.png
  en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-passive.md
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: API-M-3.1.0, PR-Review/In-progress

#2244 permission to other users to create dashboards.
  en/docs/learn/analytics/customizing-analytics-dashboards.md
Labels: API-M-3.1.0, PR-Review/In-progress

#2246 Update the content to provide permission to other users to create dashboards in analytics
  en/docs/learn/analytics/managing-dashboard-permissions.md
Labels: API-M-3.0.0

#2498 Add Code owner info
  CODEOWNERS
Labels: Docs/SyncPR-Pending, Docs/Waiting on SME, SyncPR-pending/3.0.0, SyncPR-pending/3.1.0

#2494 update IS connector
  en/docs/administer/key-managers/configure-wso2is-connector.md
  en/docs/assets/attachments/administer/wso2is-km-connector-1.0.17.zip
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Labels: API-M-3.2.0, Docs/SyncPR-Pending, PR-Review/Pending Resolution, SyncPR-pending/master

#2510 Updating the file structure and schemas of APIs and API Products in APICTL documentation
  en/docs/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md
  en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md
  en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md
  en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
  en/docs/install-and-setup/setup/api-controller/importing-apis-via-dev-first-approach.md
  en/docs/install-and-setup/setup/api-controller/migrating-api-products-to-different-environments.md
  en/docs/install-and-setup/setup/api-controller/migrating-apis-to-different-environments.md
Labels: API-M-Master, PR-Review/In-progress

#2269 Add details to keep system roles without being deleted during the provisioning process
  en/docs/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-saml.md
Labels: CEXP, PR-Review/Pending Resolution, PR/Reviewer-Updated

#2492 Review and update "Okta as an external IDP using SAML"
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-saml.md
Labels: API-M-Master, PR-Review/Phase-1, PR/Reviewer-Updated

#2527 Fix for port offset cmd issue
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: PR-Review/technical-review-done

#2528 Fix for port offset cmd issue
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: PR-Review/technical-review-done

#2534 Fix keymanager webapp ep issue
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Labels: PR-Review/technical-review-done

#2535 Fix keymanager webapp ep issue
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Labels: PR-Review/technical-review-done

#2561 Fix2491
  en/docs/administer/key-managers/configure-wso2is-connector.md
  en/docs/assets/attachments/administer/wso2is-km-connector-1.0.17.zip
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Labels: API-M-Master, PR-Review/Phase-1

#2536 Fix url
  en/docs/administer/updating-wso2-api-manager.md
Labels: PR-Review/technical-review-done

#2537 Fix url
  en/docs/administer/updating-wso2-api-manager.md
Labels: PR-Review/technical-review-done

#2538 Fix url
  en/docs/administer/updating-wso2-api-manager.md
Labels: PR-Review/technical-review-done

#2539 Fix url
  en/docs/administer/product-administration/updating-wso2-api-manager.md
Labels: PR-Review/technical-review-done

#2550 Fix doc issues
  en/docs/administer/managing-users-and-roles/managing-user-roles.md
  en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md
  en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md
  en/docs/install-and-setup/setup/setting-up-databases/overview.md
Labels: PR-Review/technical-review-done

#2596 [4.0.0] Adding Signature property to configurations
  en/docs/design/api-versioning/enabling-notifications.md
  en/docs/install-and-setup/setup/security/user-account-management.md
  en/docs/reference/config-catalog.md
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/data/output_adapter.email.toml
  en/tools/config-catalog-generator/dist/config-catalog.md
Labels: PR-Review/Phase-1

#2568 [3.2.0] Adding Signature property to configurations
  en/docs/install-and-setup/setup/security/user-account-management.md
  en/docs/learn/design-api/api-versioning/enabling-notifications.md
  en/docs/reference/config-catalog.md
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/data/output_adapter.email.toml
  en/tools/config-catalog-generator/dist/config-catalog.md
Labels: PR-Review/Phase-1

#2565 [4.0.0] Fix broken REST API links
  en/docs/reference/customize-product/product-apis/admin-apis/admin-v0.17/admin-v0.17.md
  en/docs/reference/customize-product/product-apis/admin-apis/admin-v1/admin-v1.md
  en/docs/reference/customize-product/product-apis/devportal-apis/devportal-v1/devportal-v1.md
  en/docs/reference/customize-product/product-apis/gateway-apis/gateway-v1/gateway-v1.md
  en/docs/reference/customize-product/product-apis/publisher-apis/publisher-v1/publisher-v1.md
Labels: PR-Review/Phase-1

#2567 [4.0.0] Update Rest API docs on wsdl file upload
  en/docs/reference/customize-product/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml
Labels: PR-Review/Phase-1

#2662 [3.0.0] Fix trustore configuration
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-300.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-300.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-300.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300.md
Labels: PR-Review/technical-review-done

#2660 [3.1.0] Fix trustore configuration
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md
Labels: PR-Review/technical-review-done

#2435 Update configuring-alerts.md
  en/docs/learn/analytics/configuring-alerts.md
Labels: API-M-3.2.0, Docs/Waiting on SME, help wanted

#2720 Adding/Updating the configs on enable loading dynamic MutualSSL profiles
  en/docs/publish/api-gateway/mutual-ssl-between-api-gateway-and-backend.md
Labels: PR-Review/technical-review-done

#2721 [3.2.0] Adding/Updating the configs on enable loading dynamic MutualSSL profiles
  en/docs/learn/api-gateway/mutual-ssl-between-api-gateway-and-backend.md
Labels: PR-Review/technical-review-done

#2722 [3.1.0] Adding/Updating the configs on enable loading dynamic MutualSSL profiles
  en/docs/learn/api-gateway/mutual-ssl-between-api-gateway-and-backend.md
Labels: PR-Review/technical-review-done

#2752 [Docs] [Master] Remove inconsistency in examples when configuring MutualSSL
  en/docs/publish/api-gateway/mutual-ssl-between-api-gateway-and-backend.md
Labels: PR-Review/technical-review-done

#2757 [Docs] [3.0.0] Remove inconsistency in examples when configuring MutualSSL
  en/docs/administer/product-security/mutual-ssl-between-api-gateway-and-backend.md
Labels: PR-Review/technical-review-done

#2787 Adding details on configuring a trustore from deployment.toml
  en/docs/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md
Labels: PR-Review/technical-review-done

#2789 [3.1.0] Adding details on configuring a trustore from deployment.toml
  en/docs/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md
Labels: PR-Review/technical-review-done

#2174 [3.1.0] Update Primary User Stores Docs
  en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md
  en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store.md
  en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-active-directory-user-store.md
  en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-ldap-user-store.md
  en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md
Labels: API-M-3.1.0, PR/Reviewer-Updated
