Repository wso2/docs-apim, pull requests merged in 2020-10, with the labels that each got.

#1837 Updating the docs on "Configuring Caching"
  en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md
Labels: PR/Reviewer-Updated

#1985 Add a configuration for creating analytics dashboards for users.
  en/docs/learn/analytics/customizing-analytics-dashboards.md
Labels: PR-Review/In-progress

#1857 Fixes
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
  en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md
  en/docs/learn/api-security/oauth2/oauth2-scopes/scope-allowlisting.md
  en/docs/learn/api-security/openid-connect/open-id-discovery-endpoint.md
  en/docs/learn/design-api/advanced-topics/block-subscription-to-an-api.md
  en/docs/reference/config-catalog.md
  en/docs/reference/configs.json
  en/docs/wip/config-catalog.md
  en/mkdocs.yml
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/dist/config-catalog.md
Labels: PR-Review/In-progress

#1829 add admin portal sso config content
  en/docs/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
Labels: PR-Review/Pending Resolution

#1868 Update extending-scope-validation.md
  en/docs/develop/extending-api-manager/extending-key-management/extending-scope-validation.md
Labels: PR-Review/In-progress

#1902 added new steps for the UI customization
  en/docs/develop/customizations/customizing-the-developer-portal/advanced-customization.md
Labels: PR/Reviewer-Updated

#1914 Add Accessibility Compliance statement
  en/docs/reference/accessibility-compliance.md
  en/mkdocs.yml
Labels: PR-Review/In-progress

#1916 Refine CORS doc
  en/docs/learn/api-gateway/message-mediation/configuring-message-builders-formatters.md
  en/docs/learn/design-api/advanced-topics/enabling-cors-for-apis.md
Labels: PR-Review/In-progress

#1973 Update changing-to-mysql.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
Labels: PR-Review/In-progress

#2038 PR sync for https://github.com/wso2/docs-apim/pull/2037
  en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md
Labels: PR/Reviewer-Updated

#2037 Applied and reviewed changes in #1895 #1896
  en/docs/getting-started/about-this-release.md
  en/docs/getting-started/quick-start-guide.md
  en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md
Labels: PR/Reviewer-Updated

#2040 added new steps for the UI customization
  en/docs/develop/customizations/customizing-the-developer-portal/advanced-customization.md
Labels: PR/Reviewer-Updated

#2042 Add Accessibility Compliance statement
  en/docs/getting-started/about-this-release.md
  en/docs/reference/accessibility-compliance.md
  en/mkdocs.yml
Labels: PR/Reviewer-Updated

#2043 Refine CORS doc
  en/docs/learn/api-gateway/message-mediation/configuring-message-builders-formatters.md
  en/docs/learn/design-api/advanced-topics/enabling-cors-for-apis.md
Labels: PR/Reviewer-Updated

#2045 Add info about apim.jwt.convert_dialect config
  en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md
Labels: PR/Reviewer-Updated

#2047 Remove opaque token references
  en/docs/learn/api-security/api-authentication/api-authentication-overview.md
  en/docs/learn/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
  en/docs/learn/consume-api/manage-application/generate-keys/generate-api-keys.md
Labels: PR/Reviewer-Updated

#1977 Add doc on passing Authorization header to backend configuration
  en/docs/learn/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
Labels: PR/Reviewer-Updated

#1974 Add doc on passing Authorization header to backend configuration
  en/docs/learn/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
Labels: PR/Reviewer-Updated

#1976 [3.2.0]Update set of contents related to "deployment" and "Installation and start up" topics under FAQ
  en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores.md
  en/docs/getting-started/key-concepts.md
  en/docs/install-and-setup/install/installation-prerequisites.md
  en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md
  en/docs/reference/config-catalog.md
Labels: PR-Review/Has Comments, PR-Review/In-progress, PR-Review/Pending Resolution

#2081 fixes https://github.com/wso2/docs-apim/issues/1995
  en/docs/learn/analytics/creating-custom-widgets-in-analytics-dashboards.md
Labels: API-M-Master

#2079 fixes https://github.com/wso2/docs-apim/issues/1995
  en/docs/learn/analytics/creating-custom-widgets-in-analytics-dashboards.md
Labels: API-M-3.1.0

#2080 fixes https://github.com/wso2/docs-apim/issues/1995
  en/docs/learn/analytics/creating-custom-widgets-in-analytics-dashboards.md
Labels: API-M-3.2.0

#2017 3.1.0 performance results documentation
  en/docs/assets/img/setup-and-install/apim_performance_test_all_in_one_deployment.png
  en/docs/assets/img/setup-and-install/performance-result-graph-gc-throughput-0ms.png
  en/docs/assets/img/setup-and-install/performance-result-graph-precentiles-0ms-1kib.png
  en/docs/assets/img/setup-and-install/performance-result-graph-response-time-0ms-1kib.png
  en/docs/assets/img/setup-and-install/performance-result-graph-response-time-concurrent-users.png
  en/docs/assets/img/setup-and-install/performance-result-graph-response-time-message-size.png
  en/docs/assets/img/setup-and-install/performance-result-graph-throughput-0ms-1kib.png
  en/docs/assets/img/setup-and-install/performance-result-graph-throughput-concurrent-users.png
  en/docs/assets/img/setup-and-install/performance-result-graph-throughput-message-size.png
  en/docs/install-and-setup/setup/deployment-best-practices/performance-test-results.md
  en/mkdocs.yml
Labels: API-M-3.1.0, PR/Reviewer-Updated

#1986 Add doc for Auth0 as KM
  en/docs/administer/key-managers/configure-auth0-connector.md
  en/docs/administer/key-managers/overview.md
  en/docs/assets/img/administer/auth0-add-app-admin.png
  en/docs/assets/img/administer/auth0-app-creation-form.png
  en/docs/assets/img/administer/auth0-connector-configs.png
  en/docs/assets/img/administer/auth0-create-custom-api.png
  en/docs/assets/img/administer/auth0-create-scope.png
  en/docs/assets/img/administer/auth0-created-app.png
  en/docs/assets/img/administer/auth0-dashboard.png
  en/docs/assets/img/administer/auth0-dev-app-create.png
  en/docs/assets/img/administer/auth0-endpoints.png
  en/docs/assets/img/administer/auth0-grant-types.png
  en/docs/assets/img/administer/auth0-km-type.png
  en/docs/assets/img/administer/auth0-management-api.png
  en/docs/assets/img/administer/auth0-new-application.png
  en/docs/assets/img/administer/auth0-permission-to-use-app.png
  en/docs/assets/img/administer/auth0-resource-api.png
  en/docs/assets/img/administer/auth0-success.png
  en/docs/assets/img/administer/auth0-token-validation.png
  en/mkdocs.yml
Labels: PR-Review/In-progress

#1984 Update docs on Invoke an API using the Integrated API Console
  en/docs/assets/img/learn/get-test-key.png
  en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
Labels: PR/Reviewer-Updated

#2093 [Docs] [3.2.0] Add Missing DB related information in documentation
  en/docs/install-and-setup/install/installation-prerequisites.md
  en/docs/install-and-setup/setup/setting-up-databases/overview.md
Labels: API-M-3.2.0

#2095 fixes https://github.com/wso2/docs-apim/issues/2094
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Labels: API-M-3.2.0

#2100 Adding document section for analytics migration edge case
  en/docs/assets/img/setup-and-install/migration-analytics-fedarated-authentication.png
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
Labels: CEXP, PR-Review/In-progress

#1994 [Doc][Master] Docs for Obtaining the OpenID Provider configuration information
  en/docs/learn/api-security/openid-connect/obtaining-user-profile-information-with-openid-connect.md
Labels: PR-Review/In-progress

#2016 add PingFederate connector documentation
  en/docs/administer/key-managers/configure-pingfederate-connector.md
  en/docs/administer/key-managers/overview.md
  en/docs/assets/img/administer/ping-devportal-generate-keys.png
  en/docs/assets/img/administer/ping-federate-ssl-certificate-export.png
  en/docs/assets/img/administer/ping-federate-ssl-certificate.png
  en/docs/assets/img/administer/pingfederate-client-create-1.png
  en/docs/assets/img/administer/pingfederate-client-create-2.png
  en/docs/assets/img/administer/pingfederate-client-secret.png
  en/docs/assets/img/administer/pingfederate-endpoints.png
  en/mkdocs.yml
Labels: API-M-3.2.0, PR-Review/Pending Resolution, PR/Reviewer-Updated

#2109 PR sync for https://github.com/wso2/docs-apim/pull/1994
  en/docs/learn/api-security/openid-connect/obtaining-user-profile-information-with-openid-connect.md
Labels: API-M-3.2.0, PR-Review/Phase-1, PR/Reviewer-Updated

#2112 PR sync for https://github.com/wso2/docs-apim/pull/2011
  en/docs/administer/key-managers/configure-okta-connector.md
  en/docs/assets/img/administer/okta-admin-configuration.png
Labels: API-M-3.2.0, Docs/SyncPR-Pending, PR-Review/Phase-1, PR-Review/Phase-2, PR/Reviewer-Updated

#2114 PR sync for https://github.com/wso2/docs-apim/pull/2112
  en/docs/administer/key-managers/configure-okta-connector.md
  en/docs/assets/img/administer/okta-admin-configuration.png
Labels: API-M-Master, PR-Review/Phase-1, PR-Review/Phase-2

#2051 Add jwt issuer configs to config catalog
  en/docs/reference/config-catalog.md
Labels: API-M-3.2.0, PR-Review/Pending Resolution, PR-Review/Phase-1, PR/Reviewer-Updated

#2008 Add jwt issuer configs to config catalog
  en/docs/reference/config-catalog.md
Labels: API-M-Master, Docs/SyncPR-Pending, PR-Review/Pending Resolution, PR-Review/Phase-1, PR/Reviewer-Updated

#2022 [Docs] [Master] Adding multi-tenancy properties to config catalog
  en/docs/reference/config-catalog.md
Labels: Docs/SyncPR-Pending, PR-Review/Has Comments, PR-Review/Pending Resolution, PR-Review/Phase-1, PR/Reviewer-Updated

#2035 [Doc][Master] Modify docs for publish API to a cloud cluster in private jet mode
  en/docs/learn/design-api/publish-api/publish-an-api-to-a-cloud-cluster-in-privatejet-mode.md
Labels: PR-Review/In-progress

#2063 Adds documentation for configuring custom key store for signing API Keys
  en/docs/learn/api-security/api-authentication/secure-apis-using-api-keys.md
Labels: PR-Review/In-progress

#2125 [3.2.0] Update the documentation on default ports.
  en/docs/install-and-setup/setup/reference/default-product-ports.md
Labels: API-M-3.2.0, PR-Review/Phase-1, PR/Reviewer-Updated

#2105 [3.2.0] Update FAQ section
  en/docs/reference/faq.md
Labels: API-M-3.2.0, PR-Review/Phase-1, PR/Reviewer-Updated

#2107 [3.1.0] Update FAQ section
  en/docs/reference/faq.md
Labels: API-M-3.1.0, PR-Review/Pending Resolution, PR-Review/Phase-1, PR/Reviewer-Updated

#2134 fixes https://github.com/wso2/docs-apim/issues/2133
  en/mkdocs.yml
Labels: API-M-3.2.0

#2110 [3.1.0] Add docs to configure SAML SSO for admin portal
  en/docs/assets/img/setup-and-install/enable-tenant-domain-in-local-sub-identifier.png
  en/docs/assets/img/setup-and-install/saas.png
  en/docs/assets/img/setup-and-install/saml-configuration-in-service-provider.png
  en/docs/assets/img/setup-and-install/upload-certificate-in-SP-for-saml2-sso.png
  en/docs/install-and-setup/setup/sso/configuring-sso-for-admin-portal-using-saml.md
  en/mkdocs.yml
Labels: Docs/Waiting on SME

#2146 fixes https://github.com/wso2/docs-apim/issues/2144
  en/docs/reference/samples/api-governance-sample.md
Labels: API-M-3.0.0

#2145 fixes https://github.com/wso2/docs-apim/issues/2144
  en/docs/reference/samples/api-governance-sample.md
  en/mkdocs.yml
Labels: API-M-3.1.0

#2149 https://github.com/wso2/docs-apim/issues/2044
  en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md
Labels: API-M-3.1.0

#2148 fixes https://github.com/wso2/docs-apim/issues/2044
  en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md
Labels: API-M-Master

#2147 fixes https://github.com/wso2/docs-apim/issues/2044
  en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md
Labels: API-M-3.2.0

#2138 [3.1.0] Update 2.x to 3.1 artifacts migration scripts
  en/docs/assets/attachments/install-and-setup/apim200_to_apim310_gateway_artifact_migrator_for_tenants.ps1
  en/docs/assets/attachments/install-and-setup/apim210_to_apim310_gateway_artifact_migrator.sh
Labels: API-M-3.1.0

#2163 Fixing version for search
  en/theme/material/base.html
  en/versions/assets/versions.json
Labels: API-M-Master

#2056 add jms based cache invalidation configuration
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
  en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
Labels: PR-Review/Pending Resolution, Priority/High
