Repository wso2/docs-apim, pull requests merged in 2021-07, with the labels that each got.

#4311 Fix A735 in 3.2.0
  en/docs/troubleshooting/configuring-xslt-mediation-with-xalan.md
  en/mkdocs.yml
Labels: 4.0.0-post

#4324 Updated to improve Google search
  en/docs/api-analytics/api-analytics-architecture.md
  en/docs/api-analytics/viewing/view-api-analytics-on-alerts.md
  en/docs/get-started/apim-architecture.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#4333 fixes https://github.com/wso2/docs-apim/issues/4314
  en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md
Labels: API-M-4.0.0

#4337 fixes https://github.com/wso2/docs-apim/issues/4275
  en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-passive.md
Labels: API-M-3.2.0

#4338 fixes https://github.com/wso2/docs-apim/issues/4276
  en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-passive.md
Labels: API-M-3.2.0

#4339 Update theme.css
  en/docs/assets/css/theme.css
Labels: API-M-4.0.0

#4340 fixes https://github.com/wso2/docs-apim/issues/4254
  en/mkdocs.yml
Labels: API-M-4.0.0

#4341 fixing incorrect redirection
  en/mkdocs.yml
Labels: API-M-4.0.0

#4342 fixes https://github.com/wso2/docs-apim/issues/4254
  en/docs/install-and-setup/setup/setting-up-databases/overview.md
Labels: API-M-4.0.0

#4343 fixes #4315 and #3521
  en/docs/assets/img/deploy/check.svg
  en/docs/assets/img/deploy/error.svg
  en/docs/deploy-and-publish/deploy-on-gateway/deploying-apis-in-api-gateway-vs-choreo-connect.md
Labels: API-M-4.0.0

#4347 fixes https://github.com/wso2/docs-apim/issues/4321
  en/docs/integrate/develop/integration-development-kickstart.md
Labels: API-M-4.0.0

#4344 fixes https://github.com/wso2/docs-apim/issues/4304
  en/docs/get-started/apim-architecture.md
Labels: API-M-4.0.0

#4345 fixes https://github.com/wso2/docs-apim/issues/4320
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/choreo-connect-analytics.md
Labels: API-M-4.0.0

#4348 fixes https://github.com/wso2/docs-apim/issues/4334
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
Labels: API-M-3.2.0

#4349 fixes https://github.com/wso2/docs-apim/issues/4334
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
Labels: API-M-4.0.0

#4350 fixes https://github.com/wso2/docs-apim/issues/4335
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
Labels: API-M-4.0.0

#4351 fixes https://github.com/wso2/docs-apim/issues/4335
  en/mkdocs.yml
Labels: API-M-4.0.0

#4353 fixes https://github.com/wso2/docs-apim/issues/4336
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
Labels: API-M-4.0.0

#4364 fixes https://github.com/wso2/docs-apim/issues/4358
  en/docs/observe/mi-observe/working-with-monitoring-dashboard.md
Labels: API-M-4.0.0

#4366 fixes https://github.com/wso2/docs-apim/issues/4356
  en/docs/integrate/develop/deploying-in-integration-cloud.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#4369 Fixing wso2/docs-apim#4317
  en/docs/assets/img/learn/api-revisions-mutiple-gateways.png
  en/docs/assets/img/learn/devportal-tryout-multiple-gateways.png
  en/docs/assets/img/learn/multiple-gateways-devportal-overview.png
  en/docs/assets/img/learn/multiple-gateways-revision-dialog-filled.png
  en/docs/assets/img/learn/multiple-gateways-revision-dialog.png
  en/docs/assets/img/learn/pizzashack-api-devportal.png
  en/docs/assets/img/learn/pizzashak-api-publisher.png
  en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways.md
Labels: API-M-4.0.0

#4372 Fixes https://github.com/wso2/docs-apim/issues/4356
  en/mkdocs.yml
Labels: API-M-4.0.0

#4374 Fixing wso2/docs-apim#4317
  en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways.md
Labels: API-M-4.0.0

#4373 Fixing wso2/docs-apim#4317
  en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways.md
Labels: API-M-4.0.0

#4376 fixes https://github.com/wso2/docs-apim/issues/4263
  en/docs/assets/img/home/integration.svg
  en/docs/assets/img/home/landing-page/analytics.svg
  en/docs/assets/img/home/landing-page/create-rest-api-from-an-openapi-definition.svg
  en/docs/assets/img/home/landing-page/engage-access-control-to-the-api.svg
  en/docs/assets/img/home/landing-page/external-key-manager-support.svg
  en/docs/assets/img/home/landing-page/getting-the-developer-community-involved.svg
  en/docs/assets/img/home/landing-page/graphql-support.svg
  en/docs/assets/img/home/landing-page/guaranteed-message-delivery.svg
  en/docs/assets/img/home/landing-page/implementing-an-api.svg
  en/docs/assets/img/home/landing-page/integrate-with-services-via-connectors.svg
  en/docs/assets/img/home/landing-page/integrating-with-data-sources.svg
  en/docs/assets/img/home/landing-page/notifications-using-webhooks.svg
  en/docs/assets/img/home/landing-page/other.svg
  en/docs/assets/img/home/landing-page/rate-limiting.svg
  en/docs/assets/img/home/landing-page/realtime-data-with-websocket-api.svg
  en/docs/assets/img/home/landing-page/signing-up-a-new-user.svg
  en/docs/index.md
Labels: API-M-4.0.0

#4377 fixes https://github.com/wso2/docs-apim/issues/4258
  en/docs/index.md
Labels: API-M-4.0.0

#4383 fixes https://github.com/wso2/docs-apim/issues/4382
  en/docs/design/endpoints/endpoint-types.md
Labels: API-M-4.0.0

#4367 Add GeoLocation data population capability for Windows and Fix 'update-geolocation-data.sh' for Linux
  en/docs/assets/attachments/learn/analytics/geo-location/linux/update-geolocation-data.sh
  en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/using-geo-location-based-statistics/creating-geo-location-data-set.md
Labels: API-M-3.1.0

#4389 fixes https://github.com/wso2/docs-apim/issues/4384
  en/docs/install-and-setup/setup/reference/product-compatibility.md
Labels: API-M-3.2.0

#4390 [4.0.0] Add TLS support to release note
  en/docs/get-started/about-this-release.md
Labels: 4.0.0-post, Priority/High, Severity/Major

#4391 Fixes A780
  en/docs/assets/img/setup-and-install/communication-among-port.png
  en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
Labels: API-M-3.2.0, APIMINTERNAL

#4395 Fix A776
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
Labels: 4.0.0-post, APIMINTERNAL, Priority/Highest, Severity/Critical

#4402 fixes https://github.com/wso2/docs-apim/issues/4394
  en/docs/assets/img/setup-and-install/active-active-apim-deployment.png
Labels: API-M-4.0.0

#4404 Update Publishing-Analytics-Events-to-External-Systems with suggestions
  en/docs/api-analytics/samples/publishing-analytics-events-to-external-systems.md
  en/docs/assets/img/analytics/samples/analytics-traffic-for-a-specific-api-filter.png
  en/docs/assets/img/analytics/samples/analytics-traffic-for-a-specific-api.png
  en/docs/assets/img/analytics/samples/logs-listed-in-kibana.png
  en/docs/assets/img/analytics/samples/total-analytics-traffic-filter.png
  en/docs/assets/img/analytics/samples/total-analytics-traffic.png
  en/mkdocs.yml
Labels: API-M-4.0.0

#4403 Fix E1094
  en/docs/reference/connectors/file-connector/file-connector-config.md
Labels: 4.0.0-post, APIMINTERNAL

#4405 Fix-E1086
  en/docs/reference/connectors/salesforcebulk-connector/salesforcebulk-reference.md
Labels: 4.0.0-post, APIMINTERNAL

#4408 fixes https://github.com/wso2/docs-apim/issues/4393
  en/docs/tutorials/integration-tutorials/using-inbound-endpoints.md
Labels: API-M-4.0.0

#4411 Fixed a typo
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/inter-component-communication.md
Labels: API-M-4.0.0

#4409 fixes https://github.com/wso2/docs-apim/issues/4375
  en/docs/install-and-setup/setup/mi-setup/observability/setting-up-cloud-native-observability-in-kubernetes.md
Labels: API-M-4.0.0

#4407 Fixing broken links - Part 2
  en/docs/administer/managing-users-and-roles/introduction-to-user-management.md
  en/docs/administer/managing-users-and-roles/managing-users.md
  en/docs/administer/multitenancy/managing-tenants.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/try-out-using-postman.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-via-apictl.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-via-apim.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-docker.md
  en/docs/deploy-and-publish/publish-on-dev-portal/publish-to-multiple-external-api-stores.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mariadb.md
  en/docs/install-and-setup/setup/si-setup/configuring-data-sources.md
  en/docs/integrate/examples/rabbitmq_examples/move-msgs-to-dlq-rabbitmq.md
  en/docs/integrate/examples/rabbitmq_examples/point-to-point-rabbitmq.md
  en/docs/integrate/examples/rabbitmq_examples/pub-sub-rabbitmq.md
  en/docs/integrate/examples/rabbitmq_examples/request-response-rabbitmq.md
  en/docs/integrate/examples/rabbitmq_examples/requeue-msgs-with-errors-rabbitmq.md
  en/docs/integrate/examples/rabbitmq_examples/retry-delay-failed-msgs-rabbitmq.md
  en/docs/observe/mi-observe/cloud-native-observability-dashboards.md
  en/docs/observe/si-observe/viewing-dashboards.md
  en/docs/reference/connectors/db-event-inbound-endpoint/db-event-inbound-endpoint-overview.md
  en/docs/reference/connectors/jira-connector/jira-connector-config.md
  en/docs/reference/connectors/jira-connector/jira-connector-example.md
  en/docs/reference/connectors/jira-connector/jira-connector-overview.md
  en/docs/reference/connectors/kafka-connector/kafka-connector-avro-producer-example.md
  en/docs/reference/connectors/kafka-connector/kafka-connector-overview.md
Labels: API-M-4.0.0

#4414 Partly fixes https://github.com/wso2/docs-apim/issues/4303
  en/docs/includes/design/create-streaming-api/create-a-streaming-api-from-an-asyncapi-definition.md
Labels: API-M-4.0.0

#4412 fixes https://github.com/wso2/docs-apim/issues/4316
  en/docs/install-and-setup/setup/reference/default-product-ports.md
Labels: API-M-4.0.0

#4413 fixes https://github.com/wso2/docs-apim/issues/4316
  en/docs/install-and-setup/setup/mi-setup/changing_default_ports.md
Labels: API-M-4.0.0

#4415 fixes https://github.com/wso2/docs-apim/issues/4298
  en/docs/api-analytics/getting-started-guide.md
Labels: API-M-4.0.0

#4419 fixes https://github.com/wso2/docs-apim/issues/4289
  en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/exposing-apis-via-custom-hostnames.md
Labels: API-M-4.0.0

#4420 [3.1.0] fixes https://github.com/wso2/docs-apim/issues/4284
  en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
Labels: API-M-3.1.0

#4421 [3.2.0] fixes https://github.com/wso2/docs-apim/issues/4284
  en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
Labels: API-M-3.2.0

#4422 [4.0.0] fixes https://github.com/wso2/docs-apim/issues/4284
  en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
Labels: API-M-4.0.0

#4416 fixes https://github.com/wso2/docs-apim/issues/4298
  en/docs/includes/analytics/configure-synapse-gateway.md
Labels: API-M-4.0.0

#4417 fixes https://github.com/wso2/docs-apim/issues/4298
  en/docs/api-analytics/viewing/introduction-to-api-analytics-dashboard.md
Labels: API-M-4.0.0

#4418 fixes https://github.com/wso2/docs-apim/issues/4298
  en/docs/api-analytics/viewing/view-overview-of-api-analytics.md
Labels: API-M-4.0.0

#4426 fixes https://github.com/wso2/docs-apim/issues/4210
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: API-M-4.0.0

#4425 Fixing broken links - Part 3
  en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
  en/docs/streaming/getting-started/getting-started-guide-overview.md
  en/docs/streaming/getting-started/monitor-statistics.md
  en/docs/streaming/getting-started/test-siddhi-application.md
  en/docs/use-cases/streaming-usecase/use-cases.md
Labels: API-M-4.0.0

#4427 fixes https://github.com/wso2/docs-apim/issues/4124
  en/docs/consume/manage-application/generate-keys/revoke-oauth2-application.md
Labels: API-M-4.0.0

#4431 fixes https://github.com/wso2/docs-apim/issues/4006
  en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
Labels: API-M-3.2.0

#4436 fixes https://github.com/wso2/docs-apim/issues/4284
  en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
Labels: API-M-4.0.0

#4434 fixes https://github.com/wso2/docs-apim/issues/4284
  en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
Labels: API-M-3.1.0

#4435 fixes https://github.com/wso2/docs-apim/issues/4284
  en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
Labels: API-M-3.2.0

#4438 fixes https://github.com/wso2/docs-apim/issues/4123
  en/docs/design/api-security/oauth2/grant-types/refresh-token-grant.md
  en/docs/design/api-security/oauth2/token-revocation.md
  en/docs/reference/product-apis/token-api.md
Labels: API-M-4.0.0

#4443 Introduce new params for delete and isFileExist operations
  en/docs/reference/connectors/file-connector/3.x/file-connector-3.x-config.md
Labels: API-M-4.0.0
