Repository wso2/docs-apim, pull requests merged in 2021-01, with the labels that each got.

#2873 Added missing syntax
  en/mkdocs.yml
Labels: API-M-3.2.0

#2870 Fix inline script in protype API docs
  en/docs/assets/img/learn/create-api-prototype-endpoint-add-swagger-petstore.png
  en/docs/learn/design-api/mock-api/create-a-mock-api-with-an-inline-script.md
Labels: PR-Review/Phase-1

#2819 fix token persistance doc
  en/docs/learn/api-security/oauth2/token-persistence.md
  en/docs/learn/api-security/threat-protection/bot-detection.md
Labels: PR-Review/Phase-2

#2826 3.1.0 fix token persisitance doc
  en/docs/learn/api-security/oauth2/token-persistence.md
Labels: PR-Review/Phase-2

#2801 [3.2.0] Fixes issue #1930
  en/docs/learn/rate-limiting/adding-new-throttling-policies.md
Labels: PR-Review/In-progress

#2883 [3.0.0] Update links in analytics
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: PR-Review/Pending Resolution

#2791 [3.1.0] Fixes issue #1930
  en/docs/learn/rate-limiting/adding-new-throttling-policies.md
Labels: PR-Review/In-progress

#2899 [3.2.0] Fix config typos in performance tuning docs
  en/docs/develop/extending-api-manager/extending-key-management/extending-scope-validation.md
  en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
Labels: API-M-3.2.0, PR-Review/Phase-1

#2799 [3.0.0] Fixes issue #1930
  en/docs/learn/rate-limiting/adding-new-throttling-policies.md
Labels: PR-Review/In-progress

#2886 Adding REST API change for API Product
  en/docs/reference/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml
Labels: Docs/Waiting on SME

#2908 Add Microgateway K8s QSG
  en/docs/publish/api-microgateway/get-started-with-kubernetes-for-microgateway.md
  en/mkdocs.yml
Labels: API-M-4.0.0, PR-Review/Pending Resolution

#2909 [3.0.0] Add custom urls for teants doc
  en/docs/assets/img/learn/customizations/add-collection.png
  en/docs/assets/img/learn/customizations/browse-registry.png
  en/docs/assets/img/learn/customizations/create-mapping-file.png
  en/docs/assets/img/learn/customizations/mapping-file-directory-structure.png
  en/docs/assets/img/learn/customizations/per-tenant-sp-creation-config.png
  en/docs/assets/img/learn/customizations/tenant-conf.png
  en/docs/learn/consume-api/customizations/customize-the-api-store-and-gateway-urls-for-tenants.md
  en/mkdocs.yml
Labels: API-M-3.0.0

#2898 Add Microgateway QSG
  en/docs/publish/api-microgateway/quick-start-guide.md
  en/mkdocs.yml
Labels: PR-Review/technical-review-done

#2977 [3.2.0] Remove invalid step from Managing the growth of Carbon logs section
  en/docs/administer/logging-and-monitoring/logging/managing-log-growth.md
Labels: API-M-3.2.0, PR-Review/technical-review-done

#2978 [3.1.0] Fixing #2939 and #2940 issues.
  en/docs/administer/logging-and-monitoring/logging/managing-log-growth.md
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: PR-Review/technical-review-done

#2979 [Master] Remove invalid step from Managing the growth of Carbon logs section
  en/docs/administer/logging-and-monitoring/logging/managing-log-growth.md
Labels: PR-Review/technical-review-done

#2980 [3.0.0] Fixing #2939 and #2940 issues.
  en/docs/administer/product-administration/monitoring/logging/managing-log-growth.md
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: PR-Review/technical-review-done

#3001 fixes https://github.com/wso2/docs-apim/issues/2988
  en/docs/assets/img/setup-and-install/performance-test-results/apim_performance_test_all_in_one_deployment.png
  en/docs/assets/img/setup-and-install/performance-test-results/lineplot-throughput-2g-1kib-0ms.png
  en/docs/install-and-setup/setup/deployment-best-practices/performance-test-results.md
  en/mkdocs.yml
Labels: API-M-3.2.0

#2968 [3.2.0] Add Mutual SSL configurations
  en/docs/learn/api-security/api-authentication/secure-apis-using-mutual-ssl.md
Labels: API-M-3.2.0

#3000 [3.0.0] Fixing HA terminology in APIM Analytics
  en/docs/learn/analytics/configuring-apim-analytics.md
Labels: API-M-3.0.0, Docs/Waiting on SME

#2936 Revamping the apictl documentation with MI integration
  en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
  en/docs/install-and-setup/setup/api-controller/managing-integrations-with-ctl.md
  en/mkdocs.yml
Labels: Docs/Waiting on SME, PR-Review/In-progress, PR-Review/technical-review-done

#3038 Add Revision Support Feature Documentation
  en/docs/assets/img/design/revision/create-new-revision-button.png
  en/docs/assets/img/design/revision/create-revision.png
  en/docs/assets/img/design/revision/delete-and-create-revision.png
  en/docs/assets/img/design/revision/delete-revision.png
  en/docs/assets/img/design/revision/deploy-existing-revision.png
  en/docs/assets/img/design/revision/deploy-new-revision-example.png
  en/docs/assets/img/design/revision/deploy-new-revision.png
  en/docs/assets/img/design/revision/restore-revision.png
  en/docs/assets/img/design/revision/undeploy-revision.png
  en/docs/design/create-api/create-api-revisions.md
  en/mkdocs.yml
Labels: PR-Review/In-progress
