Repository wso2/docs-apim, pull requests merged in 2021-09, with the labels that each got.

#4600 Update configuring-alerts.md
  en/docs/learn/analytics/configuring-alerts.md
Labels: API-M-3.2.0

#4598 Update try-out-using-postman.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/try-out-using-postman.md
Labels: API-M-4.0.0

#4604 Update key-concepts.md
  en/docs/get-started/key-concepts.md
Labels: API-M-4.0.0

#4603 Update configure-wso2is-connector.md
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: API-M-3.2.0

#4602 Update configure-wso2is-connector.md
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: API-M-4.0.0

#4601 Update configuring-wso2-identity-server-as-a-key-manager.md
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Labels: API-M-3.1.0

#4599 Update managing-users.md
  en/docs/administer/managing-users-and-roles/managing-users.md
Labels: API-M-4.0.0

#4576 Add correct instructions for Using OKTA As An External IDP With SAML
  en/docs/assets/img/learn/okta-apim-role-oidc-sp-select.png
  en/docs/assets/img/learn/okta-apim-role-oidc-sp.png
  en/docs/assets/img/learn/okta-apim-role-scope-mapping-edit1.png
  en/docs/assets/img/learn/okta-apim-role-scope-mapping-edit2.png
  en/docs/assets/img/learn/okta-apim-role-scope-mapping-edit3.png
  en/docs/assets/img/learn/okta-apim-role-scope-mapping.png
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-saml.md
Labels: Docs/Waiting on SME, CEXP

#4577 Add correct instructions for Using OKTA As An External IDP With SAML
  en/docs/assets/img/learn/okta-apim-role-oidc-sp-select.png
  en/docs/assets/img/learn/okta-apim-role-oidc-sp.png
  en/docs/assets/img/learn/okta-apim-role-scope-mapping-edit1.png
  en/docs/assets/img/learn/okta-apim-role-scope-mapping-edit2.png
  en/docs/assets/img/learn/okta-apim-role-scope-mapping-edit3.png
  en/docs/assets/img/learn/okta-apim-role-scope-mapping.png
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-saml.md
Labels: Docs/Waiting on SME, CEXP

#4612 Add primary key to temp table for reg indexing
  en/docs/assets/attachments/install-and-setup/reg-index.sql
Labels: CEXP

#4613 Add primary key to temp table for reg indexing
  en/docs/assets/attachments/install-and-setup/reg-index.sql
Labels: CEXP

#4614 Add primary key to temp table for reg indexing
  en/docs/assets/attachments/install-and-setup/reg-index.sql
Labels: CEXP

#4615 Add primary key to temp table for reg indexing
  en/docs/assets/attachments/install-and-setup/reg-index.sql
Labels: CEXP

#4616 Follow up for #4578
  en/docs/assets/img/learn/okta-apim-role-scope-mapping-edit1.png
Labels: CEXP

#4609 Add endpoint info for Choreo Analytics Cloud in QSG
  en/docs/api-analytics/getting-started-guide.md
Labels: CEXP

#4606 Kafka Connector configuration in WSO2 Integration Studio-8.0.0
  en/docs/reference/connectors/exporting-artifacts.md
  en/docs/reference/connectors/google-spreadsheet-connector/get-credentials-for-google-spreadsheet.md
  en/docs/reference/connectors/importing-connector-to-integration-studio.md
  en/docs/reference/connectors/kafka-connector/kafka-connector-producer-example.md
Labels: CEXP, SyncPR-pending/4.0.0

#4621 Kafka Connector configuration in WSO2 Integration Studio-8.0.0
  en/docs/reference/connectors/exporting-artifacts.md
  en/docs/reference/connectors/google-spreadsheet-connector/get-credentials-for-google-spreadsheet.md
  en/docs/reference/connectors/importing-connector-to-integration-studio.md
  en/docs/reference/connectors/kafka-connector/kafka-connector-producer-example.md
Labels: CEXP

#4619 Update jira-connector-example.md
  en/docs/reference/connectors/jira-connector/jira-connector-example.md
Labels: API-M-4.0.0

#4625 Configure Oracle DB - URL parameter
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
Labels: Docs/SyncPR-Pending, CEXP, SyncPR-pending/3.1.0, SyncPR-pending/3.0.0, SyncPR-pending/3.2.0, SyncPR-pending/master

#4628 Configure Oracle DB - URL parameter
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
Labels: CEXP

#4629 Configure Oracle DB - URL parameter
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
Labels: CEXP

#4630 Configure Oracle DB - URL parameter
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
Labels: CEXP

#4618 Update adding-an-api-subscription-tier-update-workflow.md
  en/docs/learn/consume-api/manage-subscription/advanced-topics/adding-an-api-subscription-tier-update-workflow.md
Labels: API-M-3.2.0

#4623 Update writing-custom-handlers.md
  en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md
Labels: API-M-4.0.0

#4627 Update managing-users-for-admin-portal.md
  en/docs/administer/managing-users-and-roles/managing-users-for-admin-portal.md
Labels: API-M-4.0.0

#4633 Update upgrading-from-is-km-530-to-5100.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-5100.md
Labels: API-M-3.2.0

#4620 Fixing issues in the TCP Monitoring page
  en/docs/administer/logging-and-monitoring/monitoring/monitoring-tcp-based-messages.md
  en/docs/assets/img/administer/tcpmon_screen4.png
  en/docs/assets/img/administer/tcpmon_screen5.png
  en/docs/assets/img/administer/tcpmon_screen6.png
Labels: API-M-4.0.0

#4622 Service Providers List
  en/docs/assets/img/troubleshooting/service-providers-list.png
  en/docs/troubleshooting/troubleshooting-invalid-callback-error.md
Labels: API-M-4.0.0

#4626 Update configure-keycloak-connector.md
  en/docs/administer/key-managers/configure-keycloak-connector.md
Labels: API-M-4.0.0

#4632 Update working-with-encrypted-passwords.md
  en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md
Labels: API-M-4.0.0

#4635 Update customizing-a-workflow-extension.md
  en/docs/learn/extensions/managing-workflow-extension/customizing-a-workflow-extension.md
Labels: API-M-3.0.0

#4636 Update customizing-a-workflow-extension.md
  en/docs/develop/extending-api-manager/extending-workflows/customizing-a-workflow-extension.md
Labels: API-M-3.1.0

#4637 Update customizing-a-workflow-extension.md
  en/docs/develop/extending-api-manager/extending-workflows/customizing-a-workflow-extension.md
Labels: API-M-3.2.0

#4624 [4.0.0] remove java 8 from QSG
  en/docs/get-started/api-manager-quick-start-guide.md
  en/docs/get-started/integration-quick-start-guide.md
  en/docs/get-started/streaming-quick-start-guide.md
  en/docs/install-and-setup/install/installing-the-product/installing-api-m-runtime.md
  en/docs/install-and-setup/install/installing-the-product/installing-mi-dashboard.md
  en/docs/install-and-setup/install/installing-the-product/installing-mi.md
  en/docs/install-and-setup/install/installing-the-product/installing-si-as-a-linux-service.md
  en/docs/install-and-setup/install/installing-the-product/installing-si.md
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
  en/docs/install-and-setup/setup/security/enabling-java-security-manager.md
  en/docs/streaming/getting-started/download-install-and-start-si.md
Labels: PR-Review/Pending Resolution

#4638 Update customizing-a-workflow-extension.md
  en/docs/reference/customize-product/extending-api-manager/extending-workflows/customizing-a-workflow-extension.md
Labels: API-M-4.0.0

#4641 Dynamic Endpoint Sample | Mediation Extensions
  en/docs/learn/api-gateway/message-mediation/adding-dynamic-endpoints.md
  en/docs/learn/api-gateway/message-mediation/changing-the-default-mediation-flow-of-api-requests.md
Labels: CEXP

#4646 Dynamic Endpoint Sample | Mediation Extensions
  en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/message-mediation/adding-dynamic-endpoints.md
  en/docs/learn/api-gateway/message-mediation/changing-the-default-mediation-flow-of-api-requests.md
Labels: CEXP

#4648 [4.0.0] Add missing commands related to the Windows environment
  en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
Labels: API-M-4.0.0

#4647 [Master] Add missing commands related to the Windows environment
  en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
Labels: API-M-Master

#4649 [3.2.0] Add missing commands related to the Windows environment
  en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
Labels: API-M-3.2.0

#4683 Missing configuration related to load balancer proxy settings
  en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md
Labels: CEXP

#4684 Missing configuration related to load balancer proxy settings
  en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md
Labels: CEXP

#4685 Add configurations to enable Passthrough transport level ciphers and TLS versions
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: CEXP

#4691 Add configurations to enable Passthrough transport level ciphers and TLS versions
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: CEXP

#4692 Add configurations to enable Passthrough transport level ciphers and TLS versions
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: CEXP

#4693 Add configurations to enable Passthrough transport level ciphers and TLS versions
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: CEXP

#4700 Creating Geo Location Data Set - update-geolocation-data.sh script
  en/docs/assets/attachments/learn/analytics/geo-location/linux/update-geolocation-data.sh
Labels: CEXP

#4699 Remove deployment synchronization related content
  en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
Labels: CEXP

#4710 Application and Application User separation is removed in 3.x versions
  en/docs/reference/vendor-extensions-catalog.md
Labels: CEXP

#4709 Application and Application User separation is removed in 3.x versions
  en/docs/reference/vendor-extensions-catalog.md
Labels: CEXP

#4708 Application and Application User separation is removed in 3.x versions
  en/docs/reference/vendor-extensions-catalog.md
Labels: CEXP

#4707 Application and Application User separation is removed in 3.x versions
  en/docs/reference/vendor-extensions-catalog.md
Labels: CEXP

#4706 Application and Application User separation is removed in 3.x versions
  en/docs/reference/vendor-extensions-catalog.md
Labels: CEXP

#4713 fixes https://github.com/wso2/docs-apim/issues/4269
  en/docs/install-and-setup/install-and-setup-overview.md
  en/docs/install-and-setup/setup/mi-setup/observability/observability-deployment-strategy.md
  en/docs/integrate/integration-overview.md
  en/docs/observe/api-manager/metrics/jmx-based-monitoring.md
  en/docs/observe/api-manager/monitoring-http-access-logs.md
  en/docs/observe/api-manager/traces/monitoring-with-opentracing.md
  en/docs/observe/micro-integrator/classic-observability-logs/configuring-log4j2-properties.md
  en/docs/observe/micro-integrator/cloud-native-observability-overview.md
  en/docs/observe/micro-integrator/setting-up-cloud-native-observability-in-kubernetes.md
  en/docs/observe/micro-integrator/setting-up-cloud-native-observability-on-a-vm.md
  en/docs/observe/observe-overview.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#4716 reviewed and updated
  en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/message-mediation/changing-the-default-mediation-flow-of-api-requests.md
Labels: API-M-4.0.0

#4748 fixes https://github.com/wso2/docs-apim/issues/4269
  en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
Labels: API-M-4.0.0

#4749 fixes https://github.com/wso2/docs-apim/issues/4269
  en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
Labels: API-M-4.1.0

#4747 Modify the documentation to refer tenant-conf.json file in registry when adding new scopes or roles to existing scopes
  en/docs/learn/analytics/managing-dashboard-permissions.md
Labels: CEXP

#4751 Adding proxy service support for Service Catalog documentation
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/api-business-plans.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/api-deployment-revision.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/api-gateway-deployment-summary.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/api-overview.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/create-api-from-service.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/developer-portal-api-list.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/developer-portal-api-overview.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/developer-portal-api-subscription.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/developer-portal-api-try-it-execute.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/developer-portal-api-try-it.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/endpoint-config-of-api.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/metadata-folder-service-catalog.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/new-service-api-view.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/open-service-catalog.png
  en/docs/assets/img/integrate/tutorials/service-catalog/expose-soap-service/project-explorer-service-catalog.png
  en/docs/get-started/about-this-release.md
  en/docs/get-started/integration-quick-start-guide.md
  en/docs/integrate/develop/working-with-service-catalog.md
  en/docs/integrate/integration-overview.md
  en/docs/reference/product-apis/service-catalog-apis/service-catalog-v1/service-catalog-v1.yaml
  en/docs/tutorials/integration-tutorials/service-catalog-tutorial-for-proxy-services.md
  en/docs/tutorials/tutorials-overview.md
  en/mkdocs.yml
Labels: API-M-4.1.0

#4778 Fix rendering of TOML sample
  en/docs/reference/config-catalog.md
  en/docs/wip/config-catalog.md
  en/tools/config-catalog-generator/data/_http-proxy-profile.toml
  en/tools/config-catalog-generator/data/_http-secured-proxy-profile.toml
  en/tools/config-catalog-generator/dist/config-catalog.md
Labels: CEXP

#4771 Mutual TLS Between Choreo Connect and Backend
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/tls/mutual-tls-between-gateway-and-backend.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/tls/transport-security.md
  en/mkdocs.yml
Labels: PR-Review/technical-review-done

#4765 Add SMB-2 support for APIM
  en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md
Labels: CEXP

#4733 [4.0.0] Add http_access log config and Fixes #3324 issue
  en/docs/observe/api-manager/monitoring-http-access-logs.md
  en/docs/reference/config-catalog.md
  en/tools/config-catalog-generator/data/http_access_log.toml
Labels: PR-Review/Pending Resolution

#4779 fixes https://github.com/wso2/docs-apim/issues/4774
  en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store.md
  en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways.md
  en/docs/includes/install_setup/configuring_gateway_node.md
  en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
  en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md
  en/docs/install-and-setup/setup/single-node/configuring-a-single-node.md
  en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#4780 fixes https://github.com/wso2/docs-apim/issues/4774
  en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store.md
  en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways.md
  en/docs/includes/install_setup/configuring_gateway_node.md
  en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
  en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md
  en/docs/install-and-setup/setup/single-node/configuring-a-single-node.md
  en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
  en/mkdocs.yml
Labels: API-M-4.1.0

#4763 Add audit log docs for MI
  en/docs/get-started/about-this-release.md
  en/docs/observe/micro-integrator/classic-observability-logs/monitoring-mi-audit-logs.md
  en/mkdocs.yml
Labels: API-M-4.1.0

#4783 Revert "Add audit log docs for MI"
  en/docs/get-started/about-this-release.md
  en/docs/observe/micro-integrator/classic-observability-logs/monitoring-mi-audit-logs.md
  en/mkdocs.yml
Labels: API-M-4.1.0

#4785 fixes https://github.com/wso2/docs-apim/issues/4784
  en/docs/get-started/about-this-release.md
  en/docs/observe/micro-integrator/classic-observability-logs/monitoring-mi-audit-logs.md
  en/mkdocs.yml
Labels: API-M-4.1.0
