Repository wso2/docs-apim, pull requests merged in 2021-06, with the labels that each got.

#4121 cc: Update doc for Endpoints and Deploy API via APIM
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-via-apictl.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-via-apim.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/overview.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/defining-endpoints-in-an-openapi-definition.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/endpoint-types.md
  en/mkdocs.yml
Labels: 4.0.0-post

#4133 fixes https://github.com/wso2/docs-apim/issues/4132
  en/docs/api-analytics/architecture.md
Labels: API-M-4.0.0, Docs/SyncPR-Pending

#4136 Update bot-detection.md
  en/docs/design/api-security/threat-protection/bot-detection.md
Labels: 4.0.0-post

#4141 Update publish-to-multiple-external-api-stores.md
  en/docs/deploy-and-publish/publish-on-dev-portal/publish-to-multiple-external-api-stores.md
Labels: 4.0.0-post

#4145 Update regular-expression-threat-protection-for-api-gateway.md
  en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway.md
Labels: 4.0.0-post, Docs/SyncPR-Pending, SyncPR-pending/master

#4142 Update publish-to-multiple-external-api-stores.md
  en/docs/deploy-and-publish/publish-on-dev-portal/publish-to-multiple-external-api-stores.md
Labels: 4.0.0-post

#4148 Update creating-data-services.md
  en/docs/integrate/develop/creating-artifacts/data-services/creating-data-services.md
Labels: 4.0.0-post, Docs/SyncPR-Pending, SyncPR-pending/master

#4138 Update configure-alerts.md
  en/docs/api-analytics/configure-alerts.md
Labels: 4.0.0-post, Docs/SyncPR-Pending, SyncPR-pending/master

#4150 Update mkdocs.yml
  en/mkdocs.yml
Labels: 4.0.0-post

#4151 Update exporting-artifacts.md
  en/docs/integrate/develop/exporting-artifacts.md
Labels: 4.0.0-post

#4153 Update creating-data-services.md
  en/docs/integrate/develop/creating-artifacts/data-services/creating-data-services.md
Labels: API-M-4.0.0, Docs/SyncPR-Pending, SyncPR-pending/master

#3841 Add doc for Deploy API to Choreo Connect with Virtual Hosts
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-with-virtual-hosts.md
  en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/exposing-apis-via-custom-hostnames.md
  en/mkdocs.yml
Labels: 4.0.0-post, PR-Review/Pending Resolution

#4168 fixes #4165
  en/docs/includes/analytics/configure-synapse-gateway.md
Labels: API-M-4.0.0

#4169 fixes https://github.com/wso2/docs-apim/issues/4165
  en/docs/includes/analytics/configure-synapse-gateway.md
Labels: API-M-4.0.0

#4176 fix for https://github.com/wso2/docs-apim/issues/4165
  en/docs/includes/analytics/configure-synapse-gateway.md
Labels: API-M-4.0.0

#4177 fixes https://github.com/wso2/docs-apim/issues/4165
  en/docs/includes/analytics/configure-synapse-gateway.md
Labels: API-M-4.0.0

#4179 resized and deleted images
  en/docs/assets/attachments/103328543/103328557.pdf
  en/docs/assets/attachments/103333651/103333657.pdf
  en/docs/assets/attachments/103333749/103333750.bmp
  en/docs/assets/attachments/103334910/103334912.png
  en/docs/assets/attachments/126559464/126559465.jpg
  en/docs/assets/attachments/126559464/126559465.png
  en/docs/assets/attachments/126559464/126559466.png
  en/docs/assets/attachments/126559467/126559468.jpg
  en/docs/assets/attachments/126559467/126559468.png
  en/docs/assets/img/integrate/create_artifacts/new_api/api-artifact-design-view.jpg
  en/docs/assets/img/integrate/create_artifacts/new_api/api-artifact-design-view.png
  en/docs/assets/img/integrate/create_artifacts/new_local_entry/new-local-entry-form-view.jpg
  en/docs/assets/img/integrate/create_artifacts/new_local_entry/new-local-entry-form-view.png
  en/docs/assets/img/integrate/create_project/docker_k8s_project/custom-proxy-service-jms.jpg
  en/docs/assets/img/integrate/create_project/docker_k8s_project/custom-proxy-service-jms.png
  en/docs/assets/img/integrate/create_project/docker_k8s_project/hello-docker-template.png
  en/docs/assets/img/integrate/create_project/docker_k8s_project/k8s-hello-world-template.jpg
  en/docs/assets/img/integrate/create_project/docker_k8s_project/k8s-hello-world-template.png
  en/docs/assets/img/integrate/create_project/docker_k8s_project/k8s-proj.jpg
  en/docs/assets/img/integrate/create_project/docker_k8s_project/k8s-proj.png
  en/docs/assets/img/integrate/create_project/docker_k8s_project/kubernetes-docker-project.png
  en/docs/assets/img/integrate/create_project/new_esb_project.png
  en/docs/assets/img/integrate/mediators/119131214/119131215.jpg
  en/docs/assets/img/integrate/mediators/119131214/119131215.png
  en/docs/assets/img/integrate/mediators/119131214/119134381.png
  en/docs/assets/img/integrate/tutorials/119132196/http4e-client-message-transformation.png
  en/docs/assets/img/integrate/tutorials/119132228/http4e-client-service-chaining.png
  en/docs/assets/img/integrate/tutorials/119132294/import-gmail-connector.jpg
  en/docs/assets/img/integrate/tutorials/119132294/import-gmail-connector.png
  en/docs/assets/img/integrate/tutorials/119132294/restart_server.png
  en/docs/assets/img/integrate/tutorials/data_services/119130577/119130584.png
  en/docs/assets/img/integrate/tutorials/data_services/operation-added.png
  en/docs/assets/img/integrate/tutorials/using-templates/delete-log-mediator.png
  en/docs/assets/img/integrate/workbench/workbench-getting-started.jpg
  en/docs/assets/img/integrate/workbench/workbench-getting-started.png
  en/docs/assets/img/integrate/workbench/workbench-working-project.jpg
  en/docs/assets/img/integrate/workbench/workbench-working-project.png
  en/docs/assets/img/learn/resource-of-pet-store-api.jpg
  en/docs/assets/img/learn/resource-of-pet-store-api.png
  en/docs/assets/img/setup-and-install/internal-public-and-private-cloud.png
  en/docs/assets/img/streaming/managing-wso2-dashboards/database-statistics.jpg
  en/docs/assets/img/streaming/managing-wso2-dashboards/database-statistics.png
  en/docs/assets/img/tutorials/scenarios/integration_studio_dataservice.jpg
  en/docs/assets/img/tutorials/scenarios/integration_studio_dataservice.png
  en/docs/design/api-security/threat-protection/gateway-threat-protectors/json-threat-protection-for-api-gateway.md
  en/docs/design/api-security/threat-protection/gateway-threat-protectors/xml-threat-protection-for-api-gateway.md
  en/docs/design/create-api/create-rest-api/create-a-rest-api-from-an-openapi-definition.md
  en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integrations/integration-samples/content-based-routing.md
  en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integrations/integration-samples/hello-world.md
  en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integrations/integration-samples/jms-sender-receiver.md
  en/docs/integrate/develop/creating-artifacts/creating-an-api.md
  en/docs/integrate/develop/creating-artifacts/registry/creating-local-registry-entries.md
  en/docs/integrate/develop/wso2-integration-studio.md
  en/docs/observe/si-observe/viewing-dashboards.md
  en/docs/reference/mediators/property-mediator.md
  en/docs/tutorials/integration-tutorials/using-the-gmail-connector.md
  en/docs/tutorials/scenarios/scenario6-integrating-with-data-sources.md
Labels: API-M-4.0.0

#4184 compressed images
  en/docs/assets/img/integrate/create_artifacts/new_api/add-new-api-resource.png
  en/docs/assets/img/integrate/create_artifacts/new_api/api-artifact-source-view.png
  en/docs/assets/img/integrate/create_artifacts/new_api/api-properties.png
  en/docs/assets/img/integrate/create_artifacts/new_api/api-resource-properties.png
  en/docs/assets/img/integrate/create_artifacts/new_api/create-new-api-option.png
  en/docs/assets/img/integrate/create_artifacts/new_api/import-api-dialog.png
  en/docs/assets/img/integrate/create_artifacts/new_api/new-api-artifact-dialog.png
  en/docs/assets/img/integrate/create_artifacts/new_api/new-api-meta-data-folder.png
  en/docs/assets/img/integrate/create_artifacts/new_api/new-api-swagger-dialog.png
  en/docs/assets/img/integrate/create_artifacts/new_api/new-artifact.png
  en/docs/assets/img/integrate/create_artifacts/new_api/project-explorer.png
  en/docs/assets/img/integrate/create_artifacts/new_endpoint/select-endpoint.png
  en/docs/assets/img/integrate/create_artifacts/new_inbound_endpoint/inbound-source-view.png
  en/docs/assets/img/integrate/create_artifacts/new_inbound_endpoint/new-inbound-endpoint-wizard-2-1.png
  en/docs/assets/img/integrate/create_artifacts/new_inbound_endpoint/select-inbound-endpoint.png
Labels: API-M-4.0.0

#4187 fixed heading levels
  en/docs/develop/streaming-apps/http-status-codes.md
Labels: API-M-4.0.0

#4186 Fix formatting
  en/docs/integrate/develop/packaging-artifacts.md
  en/docs/integrate/examples/data_integration/data-input-validator.md
  en/docs/integrate/examples/data_integration/request-box.md
Labels: 4.0.0-post

#4193 fixes broken link
  en/docs/includes/analytics/configure-synapse-gateway.md
Labels: API-M-4.0.0

#4192 fixing broken links
  en/docs/develop/streaming-apps/installing-siddhi-extensions.md
  en/docs/streaming/connectors/configuring-system-parameters-for-siddhi-extensions.md
  en/docs/streaming/connectors/connectors-overview.md
  en/docs/streaming/connectors/installing-siddhi-extensions.md
  en/docs/streaming/connectors/writing-custom-siddhi-extensions.md
  en/docs/use-cases/streaming-tutorials/creating-etl-application-via-tooling.md
  en/docs/use-cases/streaming-tutorials/performing-real-time-etl-with-mysql.md
  en/docs/use-cases/streaming-tutorials/triggering-integrations-via-micro-integrator.md
  en/docs/use-cases/streaming-usecase/transforming-data.md
  en/tools/config-catalog-generator-mi/README.md
  en/tools/config-catalog-generator/README.md
Labels: API-M-4.0.0

#4200 Fixed broken link
  en/docs/troubleshooting/error-handling.md
Labels: API-M-4.0.0

#4199 Fixed broken links
  en/docs/includes/deploy/assign-custom-hostname.md
Labels: API-M-4.0.0

#4201 fixes https://github.com/wso2/docs-apim/issues/4132
  en/docs/assets/img/analytics/apim-analytics-simplified.jpg
Labels: API-M-4.0.0

#4208 fixes https://github.com/wso2/docs-apim/issues/4207
  en/docs/learn/api-gateway/response-caching.md
Labels: API-M-3.2.0

#4209 fixes https://github.com/wso2/docs-apim/issues/4207
  en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/response-caching.md
Labels: API-M-4.0.0

#4211 fixes https://github.com/wso2/docs-apim/issues/3560 partly
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/event-hub.md
  en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways.md
  en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/exposing-apis-via-custom-hostnames.md
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
  en/docs/install-and-setup/setup/single-node/configuring-a-single-node.md
Labels: API-M-4.0.0

#4216 fixes https://github.com/wso2/docs-apim/issues/4170
  en/docs/learn/api-monetization/monetizing-an-api.md
Labels: API-M-3.2.0

#4218 4.0.0 - fixing the copyright statement
  en/theme/material/partials/footer.html
Labels: API-M-4.0.0

#4224 fixes https://github.com/wso2/docs-apim/issues/4221
  en/theme/material/partials/footer.html
Labels: API-M-3.0.0, Priority/Highest

#4223 fixes https://github.com/wso2/docs-apim/issues/4221
  en/theme/material/partials/footer.html
Labels: API-M-3.1.0, Priority/Highest

#4220 Updating the copyrights in 3.2.0
  en/theme/material/partials/footer.html
Labels: API-M-3.2.0, Priority/Highest

#4226 fixes https://github.com/wso2/docs-apim/issues/4217
  en/docs/administer/key-managers/configure-forgerock-connector.md
  en/docs/assets/img/administer/forgerock-create-oauth-provider.png
Labels: API-M-4.0.0

#4227 fixes https://github.com/wso2/docs-apim/issues/4217
  en/docs/administer/key-managers/configure-forgerock-connector.md
  en/docs/assets/img/administer/forgerock-create-oauth-provider.png
Labels: API-M-Master

#4229 fixing link
  en/docs/administer/managing-users-and-roles/managing-users-for-admin-portal.md
Labels: API-M-4.0.0, Docs/SyncPR-Pending, SyncPR-pending/master

#4228 fixing broken anchor
  en/docs/administer/managing-users-and-roles/managing-users-for-admin-portal.md
Labels: API-M-3.2.0

#4230 Fix Internal JIRA - 683
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: 4.0.0-post

#4225 Update the documentation related to Artifact sync feature in 3.2.0
  en/docs/assets/img/learn/artifact-synchronizer-architecture.png
  en/docs/assets/img/learn/gateway-startup.png
  en/docs/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster.md
  en/docs/learn/api-gateway/maintaining-separate-production-and-sandbox-gateways.md
Labels: API-M-3.2.0, APIMINTERNAL, CEXP, PR-Review/technical-review-done, component/api-gateway

#4239 Add CC error codes doc
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/error-handling.md
  en/mkdocs.yml
Labels: API-M-4.0.0, SyncPR-pending/master

#4241 fixes https://github.com/wso2/docs-apim/issues/4238
  en/docs/assets/img/setup-and-install/db-connections-distributed-deployment.png
  en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
Labels: API-M-4.0.0, Priority/Highest

#4237 Remove node_ip configuration parameter under the server tag
  en/tools/config-catalog-generator/data/server.toml
Labels: APIMINTERNAL, CEXP

#4236 Remove node_ip configuration parameter under the server tag
  en/tools/config-catalog-generator/data/server.toml
Labels: APIMINTERNAL, CEXP

#4058 Update Product API Definitions
  en/docs/reference/product-apis/admin-apis/admin-v2/admin-v2.yaml
  en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml
  en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
Labels: API-M-Master, PR-Review/Pending Resolution

#4246 fixes https://github.com/wso2/docs-apim/issues/4245
  en/docs/api-analytics/architecture.md
  en/docs/api-analytics/configure-alerts.md
  en/docs/api-analytics/gateways/configure-synapse-gateway.md
  en/docs/api-analytics/getting-started-guide.md
  en/docs/api-analytics/role-based-access-control.md
  en/docs/api-analytics/viewing/analytics-pages-alerts.md
  en/docs/api-analytics/viewing/analytics-pages-devices.md
  en/docs/api-analytics/viewing/analytics-pages-errors.md
  en/docs/api-analytics/viewing/analytics-pages-introduction.md
  en/docs/api-analytics/viewing/analytics-pages-latency.md
  en/docs/api-analytics/viewing/analytics-pages-overview.md
  en/docs/api-analytics/viewing/analytics-pages-report.md
  en/docs/api-analytics/viewing/analytics-pages-traffic.md
Labels: API-M-4.0.0

#4250 part 1 fix for #4140
  en/docs/administer/managing-users-and-roles/introduction-to-user-management.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-via-apictl.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-docker.md
  en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mariadb.md
  en/docs/install-and-setup/setup/si-setup/configuring-data-sources.md
  en/docs/integrate/examples/rabbitmq_examples/move-msgs-to-dlq-rabbitmq.md
  en/docs/integrate/examples/rabbitmq_examples/point-to-point-rabbitmq.md
  en/docs/integrate/examples/rabbitmq_examples/pub-sub-rabbitmq.md
  en/docs/integrate/examples/rabbitmq_examples/request-response-rabbitmq.md
  en/docs/integrate/examples/rabbitmq_examples/requeue-msgs-with-errors-rabbitmq.md
  en/docs/integrate/examples/rabbitmq_examples/retry-delay-failed-msgs-rabbitmq.md
  en/docs/observe/mi-observe/cloud-native-observability-dashboards.md
  en/docs/observe/si-observe/viewing-dashboards.md
  en/docs/reference/connectors/db-event-inbound-endpoint/db-event-inbound-endpoint-overview.md
  en/docs/reference/connectors/jira-connector/jira-connector-config.md
  en/docs/reference/connectors/jira-connector/jira-connector-example.md
  en/docs/reference/connectors/jira-connector/jira-connector-overview.md
Labels: API-M-4.0.0, Docs/SyncPR-Pending

#4248 Add doc change for the dashboard name change
  en/docs/assets/img/integrate/ei-analytics/119132315/mi-dashboard.png
  en/docs/observe/mi-observe/using-the-analytics-dashboard.md
Labels: Type/WUM

#4251 Change dashboard name
  en/docs/assets/img/integrate/ei-analytics/119132315/mi-dashboards.png
  en/docs/observe/mi-observe/using-the-analytics-dashboard.md
Labels: Type/WUM

#4257 Fix 690
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-5100.md
Labels: API-M-3.2.0

#4261 Fix 689
  en/docs/design/api-security/oauth2/grant-types/jwt-grant.md
Labels: 4.0.0-post

#4266 fixes https://github.com/wso2/docs-apim/issues/4244
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md
Labels: API-M-4.0.0, SyncPR-pending/master

#4281 fixes https://github.com/wso2/docs-apim/issues/4280
  en/docs/install-and-setup/setup/si-deployment/deploying-si-as-a-single-deployment.md
Labels: API-M-4.0.0

#4234 Change IS token endpoint (oauth2/token)
  en/docs/design/api-security/oauth2/grant-types/authorization-code-grant.md
  en/docs/design/api-security/oauth2/grant-types/client-credentials-grant.md
  en/docs/design/api-security/oauth2/grant-types/jwt-grant.md
  en/docs/design/api-security/oauth2/grant-types/kerberos-oauth2-grant.md
  en/docs/design/api-security/oauth2/grant-types/ntlm-grant.md
  en/docs/design/api-security/oauth2/grant-types/password-grant.md
  en/docs/design/api-security/oauth2/grant-types/refresh-token-grant.md
  en/docs/design/api-security/oauth2/grant-types/saml-extension-grant.md
Labels: APIMINTERNAL, CEXP

#4235 Change IS token endpoint (oauth2/token)
  en/docs/design/api-security/oauth2/grant-types/authorization-code-grant.md
  en/docs/design/api-security/oauth2/grant-types/client-credentials-grant.md
  en/docs/design/api-security/oauth2/grant-types/jwt-grant.md
  en/docs/design/api-security/oauth2/grant-types/kerberos-oauth2-grant.md
  en/docs/design/api-security/oauth2/grant-types/ntlm-grant.md
  en/docs/design/api-security/oauth2/grant-types/password-grant.md
  en/docs/design/api-security/oauth2/grant-types/refresh-token-grant.md
  en/docs/design/api-security/oauth2/grant-types/saml-extension-grant.md
Labels: API-M-4.0.0, APIMINTERNAL, CEXP

#4233 Update Keystore Configs & API Key Keystore Configs Descriptions
  en/docs/learn/api-security/api-authentication/secure-apis-using-api-keys.md
  en/tools/config-catalog-generator/data/configs.json
Labels: APIMINTERNAL, CEXP

#4081 Update Keystore Configs & API Key Keystore Configs Descriptions
  en/docs/learn/api-security/api-authentication/secure-apis-using-api-keys.md
  en/tools/config-catalog-generator/data/configs.json
Labels: API-M-3.2.0, APIMINTERNAL, CEXP, PR-Review/Pending Resolution

#4232 Update Keystore Configs & API Key Keystore Configs Descriptions
  en/docs/learn/api-security/api-authentication/secure-apis-using-api-keys.md
  en/tools/config-catalog-generator/data/configs.json
Labels: APIMINTERNAL, CEXP

#4292 Fixes A726
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: 4.0.0-post

#4293 Add docs for Redis connector v2.1.0 and v2.2.0
  en/docs/reference/connectors/redis-connector/1.0.1/redis-connector-reference.md
  en/docs/reference/connectors/redis-connector/2.1.x/redis-connector-reference.md
  en/docs/reference/connectors/redis-connector/2.2.x/redis-connector-reference.md
  en/docs/reference/connectors/redis-connector/redis-connector-configuration.md
  en/docs/reference/connectors/redis-connector/redis-connector-overview.md
  en/mkdocs.yml
Labels: 4.0.0-post

#4297 Revamping MI analytics docs
  en/docs/assets/img/integrate/ei-analytics/119132315/119132317.png
  en/docs/assets/img/integrate/ei-analytics/ob-all-events-to-all-servers.png
  en/docs/assets/img/integrate/ei-analytics/ob-fail-over.png
  en/docs/assets/img/integrate/ei-analytics/ob-lb-events-to-servers.png
  en/docs/assets/img/integrate/ei-analytics/ob-lb-to-sets-of-servers.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132316.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132318.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132319.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132320.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132321.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132322.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132323.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132324.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132325.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132326.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132327.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132328.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132329.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132330.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132331.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132332.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132333.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132334.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132335.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132336.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132337.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132338.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132339.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132340.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132341.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132342.png
  en/docs/assets/img/integrate/mi-analytics/119132315/119132343.png
  en/docs/assets/img/integrate/mi-analytics/119132315/message-tracing.png
  en/docs/assets/img/integrate/mi-analytics/119132315/mi-dashboard.png
  en/docs/assets/img/integrate/mi-analytics/119132315/per-endpoint-requests.png
  en/docs/assets/img/integrate/mi-analytics/analytics-architecture.jpg
  en/docs/assets/img/integrate/mi-analytics/dashboard-login.png
  en/docs/assets/img/integrate/mi-analytics/endpoint-properties.png
  en/docs/assets/img/integrate/mi-analytics/ob-all-events-to-all-servers.jpg
  en/docs/assets/img/integrate/mi-analytics/ob-fail-over.jpg
  en/docs/assets/img/integrate/mi-analytics/ob-lb-events-to-servers.jpg
  en/docs/assets/img/integrate/mi-analytics/ob-lb-to-sets-of-servers.jpg
  en/docs/assets/img/integrate/mi-analytics/restapi-properties.png
  en/docs/assets/img/integrate/monitoring-dashboard/classic-observability-architecture.png
  en/docs/install-and-setup/setup/mi-setup/observability/observability-deployment-strategy.md
  en/docs/install-and-setup/setup/mi-setup/observability/setting-up-classic-observability-deployment.md
  en/docs/mi-analytics/setting-up-mi-analytics.md
  en/docs/mi-analytics/using-the-analytics-dashboard.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#4301 Analytics docs related minor changes
  en/docs/mi-analytics/using-the-analytics-dashboard.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#4295 Add docs for Redis connector v2.1.0 and v2.2.0
  en/docs/reference/connectors/redis-connector/1.0.1/redis-connector-reference.md
  en/docs/reference/connectors/redis-connector/2.1.x/redis-connector-reference.md
  en/docs/reference/connectors/redis-connector/2.2.x/redis-connector-reference.md
  en/docs/reference/connectors/redis-connector/redis-connector-configuration.md
  en/docs/reference/connectors/redis-connector/redis-connector-overview.md
  en/mkdocs.yml
Labels: 4.0.0-post

#4306 fixes https://github.com/wso2/docs-apim/issues/4231
  en/docs/assets/css/theme.css
  en/theme/material/partials/footer.html
Labels: API-M-3.2.0

#4308 fixes https://github.com/wso2/docs-apim/issues/4231
  en/docs/assets/css/theme.css
  en/theme/material/partials/footer.html
Labels: API-M-3.0.0

#4307 fixes https://github.com/wso2/docs-apim/issues/4231
  en/docs/assets/css/theme.css
  en/theme/material/partials/footer.html
Labels: API-M-3.1.0
