Repository wso2/docs-apim, pull requests merged in 2021-02, with the labels that each got.

#3083 Correcting the default value of enable_unlimited_tier and the description in the config catalog
  en/docs/reference/config-catalog.md
  en/tools/config-catalog-generator/data/apim.throttling.toml
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/dist/config-catalog.md
Labels: API-M-4.0.0, APIMINTERNAL, CEXP

#3072 Add content on disabling Devportal Anonymous mode
  en/docs/administer/disabling-anonymous-access-to-developer-portal.md
  en/docs/assets/img/administer/disable-developer-portal-anonymous-mode.png
  en/mkdocs.yml
Labels: PR-Review/In-progress

#3046 Introducing a new structure to the API Controller docs section
  en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-different-endpoint-types.md
  en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md
  en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-git-integration.md
  en/docs/install-and-setup/setup/api-controller/advanced-topics/formatting-the-output-of-get-command.md
  en/docs/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md
  en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md
  en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md
  en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
  en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md
  en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
  en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
  en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md
  en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
  en/docs/install-and-setup/setup/api-controller/managing-applications/migrating-applications-to-different-environments.md
  en/docs/install-and-setup/setup/api-controller/managing-integrations/managing-integrations-with-ctl.md
  en/mkdocs.yml
Labels: API-M-4.0.0, PR-Review/technical-review-done

#3091 fixes https://github.com/wso2/docs-apim/issues/3089
  en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md
Labels: API-M-3.2.0

#3093 fixes https://github.com/wso2/docs-apim/issues/3089
  en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md
Labels: API-M-3.1.0

#3092 fixes https://github.com/wso2/docs-apim/issues/3089
  en/docs/publish/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md
Labels: API-M-4.0.0

#3105 Add Instructions to configure Forgerock as an external KM
  en/docs/administer/key-managers/configure-forgerock-connector.md
  en/docs/administer/key-managers/overview.md
  en/docs/assets/img/administer/forgerock-access-token-lifetime.png
  en/docs/assets/img/administer/forgerock-add-client.png
  en/docs/assets/img/administer/forgerock-add-km-1.png
  en/docs/assets/img/administer/forgerock-add-km-2.png
  en/docs/assets/img/administer/forgerock-add-km-3.png
  en/docs/assets/img/administer/forgerock-add-km-4.png
  en/docs/assets/img/administer/forgerock-client-grant.png
  en/docs/assets/img/administer/forgerock-configure-dcr.png
  en/docs/assets/img/administer/forgerock-createOauthProvider.png
  en/docs/assets/img/administer/forgerock-devportal-genkeys.png
  en/docs/assets/img/administer/forgerock-oauth2-ad.png
  en/docs/assets/img/administer/forgerock-oauth2-advance-1.png
  en/docs/assets/img/administer/forgerock-oauth2-core.png
  en/docs/assets/img/administer/forgerock-provider-advance-config.png
  en/docs/assets/img/administer/forgerock-realms.png
  en/docs/assets/img/administer/forgerock-token-format.png
  en/mkdocs.yml
Labels: API-M-4.0.0, PR/Reviewer-Updated

#3120 Update Encrypting Secrets with CTL section
  en/docs/install-and-setup/setup/api-controller/encrypting-secrets-with-ctl.md
  en/docs/install-and-setup/setup/mi-setup/security/encrypting_plain_text.md
  en/mkdocs.yml
Labels: PR-Review/technical-review-done

#3119 fixes EIINTERNAL-673
  en/docs/install-and-setup/setup/mi-setup/performance_tuning/jms_transport_tuning.md
Labels: API-M-4.0.0, CEXP

#3129 fix for EIINTERNAL-673 based on review comments
  en/docs/install-and-setup/setup/mi-setup/performance_tuning/jms_transport_tuning.md
Labels: CEXP

#3132 Define connection between max and core values EIINTERNAL-673
  en/docs/install-and-setup/setup/mi-setup/performance_tuning/jms_transport_tuning.md
Labels: CEXP

#3123 Include HA configurations(LB-configs) for the Traffic-Manager
  en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md
Labels: CEXP

#3124 APIM-Analytics-3.2.0 persistent artifacts
  en/docs/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts.md
Labels: APIMINTERNAL, CEXP

#3078 add relavant wum timestamp
  en/docs/administer/key-managers/configure-wso2is-connector.md
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Labels: PR-Review/Pending Resolution

#3075 Add xds concept doc
  en/docs/publish/api-microgateway/internal-communication-protocol.md
  en/mkdocs.yml
Labels: API-M-4.0.0, API-M-Master, PR-Review/Phase-1

#3138 Additional update for APIMINTERNAL-339
  en/docs/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts.md
Labels: CEXP

#3139 Sync PR for #3138
  en/docs/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts.md
Labels: API-M-Master

#3143 [3.0.0] Adding a new step when configuring workflow for tenants
  en/docs/learn/extensions/managing-workflow-extension/configuring-workflows-for-tenants.md
Labels: PR-Review/Phase-1, PR/Reviewer-Updated

#3146 Removing the docs on Implicit Grant from APIM 4.0.0
  en/docs/design/api-security/oauth2/grant-types/implicit-grant.md
  en/docs/get-started/about-this-release.md
  en/mkdocs.yml
Labels: CEXP, PR-Review/Phase-1, PR/Reviewer-Updated

#3145 [3.2.0] Deprecating the docs on Implicit Grant in APIM 3.2.0
  en/docs/getting-started/about-this-release.md
  en/docs/learn/api-security/oauth2/grant-types/implicit-grant.md
Labels: CEXP, PR-Review/Phase-1, PR/Reviewer-Updated

#3149 fixes APIMINTERNAL-305
  en/docs/administer/key-managers/configure-wso2is-connector.md
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5100.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-5100.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-5100.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-5100.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-5100.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-5100.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-5100.md
Labels: APIMINTERNAL

#3055 Add HashiCorp configuration section to APICTL docs
  en/docs/install-and-setup/setup/api-controller/managing-integrations/managing-integrations-with-ctl.md
  en/docs/install-and-setup/setup/mi-setup/security/using-hashicorp-secrets.md
  en/docs/install-and-setup/setup/mi-setup/user_stores/managing_users.md
Labels: API-M-4.0.0, PR-Review/technical-review-done

#3164 fixes https://github.com/wso2/docs-apim/issues/3159
  en/docs/learn/api-gateway/message-mediation/passing-a-custom-authorization-token-to-the-backend.md
Labels: API-M-3.2.0

#3163 fixes https://github.com/wso2/docs-apim/issues/3159
  en/docs/learn/api-gateway/message-mediation/passing-a-custom-authorization-token-to-the-backend.md
Labels: API-M-3.0.0

#3162 fixes https://github.com/wso2/docs-apim/issues/3159
  en/docs/learn/api-gateway/message-mediation/passing-a-custom-authorization-token-to-the-backend.md
Labels: API-M-3.1.0

#3165 fixes https://github.com/wso2/docs-apim/issues/3159
  en/docs/deploy/api-gateway/message-mediation/passing-a-custom-authorization-token-to-the-backend.md
Labels: API-M-4.0.0

#3183 fixes https://github.com/wso2/docs-apim/issues/3182
  en/mkdocs.yml
Labels: API-M-4.0.0

#3172 Change documentation with Event Based Gateway Related changes
  en/docs/assets/img/setup-and-install/db-connections-distributed-deployment.png
  en/docs/assets/img/setup-and-install/publisher-connections.png
  en/docs/assets/img/setup-and-install/traffic-manager-connections.png
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
  en/docs/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster.md
  en/mkdocs.yml
Labels: PR-Review/In-progress

#3160 Hack 3.2.0
  en/docs/assets/img/learn/ui-customize-pic0.png
  en/docs/assets/img/learn/ui-customize-pic1.png
  en/docs/assets/img/learn/ui-customize-pic2.png
  en/docs/assets/img/learn/ui-customize-pic3.png
  en/docs/assets/img/learn/ui-customize-pic4.png
  en/docs/assets/img/learn/ui-customize-pic4_.png
  en/docs/assets/img/learn/ui-customize-pic5.png
  en/docs/assets/img/learn/ui-customize-pic6.png
  en/docs/assets/img/learn/ui-customize-pic7.png
  en/docs/assets/img/learn/ui-customize-pub-pic1.png
  en/docs/assets/img/learn/ui-customize-pub-pic2.png
  en/docs/assets/img/learn/ui-customize-pub-pic3.png
  en/docs/assets/img/learn/ui-customize-pub-pic4.png
  en/docs/develop/customizations/advanced-ui-customization.md
Labels: API-M-3.2.0, PR-Review/Phase-1

#2911 [master] Update scope assignment docs for admin portal
  en/docs/administer/managing-users-and-roles/managing-permissions.md
  en/docs/assets/img/administer/add-new-scope-name.png
  en/docs/assets/img/administer/add-scope-mapping.png
  en/docs/assets/img/administer/new-custom-scope-mapping.png
  en/docs/assets/img/administer/new-role-alias-mapping.png
Labels: PR-Review/Pending Resolution

#3189 fixes issue 2 in docs-apim/issues/3187
  en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md
Labels: API-M-3.2.0

#3188 fixes issue 2 docs-apim/issues/3187
  en/docs/learn/tutorials/create-and-publish-a-graphql-api.md
Labels: API-M-3.2.0

#3194 fixes #3174 and #3177
  en/docs/assets/attachments/learn/api-authentication-handler.java
  en/docs/learn/api-gateway/handlers/writing-custom-handlers.md
Labels: API-M-3.0.0

#3193 fixes #3174 and #3177
  en/docs/assets/attachments/learn/api-authentication-handler.java
  en/docs/develop/extending-api-manager/extending-gateway/writing-custom-handlers.md
Labels: API-M-3.1.0

#3192 fixes #3174 and #3177
  en/docs/assets/attachments/learn/api-authentication-handler.java
  en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md
Labels: API-M-Master

#3191 fixes #3174 and #3177
  en/docs/assets/attachments/learn/api-authentication-handler.java
  en/docs/develop/extending-api-manager/extending-gateway/writing-custom-handlers.md
Labels: API-M-3.2.0

#3166 Fixes https://github.com/wso2/docs-apim/issues/3148
  en/docs/install-and-setup/install/installation-prerequisites.md
Labels: API-M-3.2.0, APIMINTERNAL, CEXP

#3190 Fix for APIMINTERNAL-348
  en/docs/assets/img/learn/service-providers.png
  en/docs/assets/img/learn/update-token.png
  en/docs/learn/api-security/oauth2/access-token-types/jwt-tokens.md
Labels: API-M-3.0.0, APIMINTERNAL, CEXP

#3195 Fix for latest comment in APIMINTERNAL-349
  en/docs/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-oidc.md
Labels: API-M-3.2.0, APIMINTERNAL, CEXP

#3199 Fix for APIMINTERNAL-359
  en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md
Labels: API-M-3.2.0, APIMINTERNAL, CEXP, Docs/Waiting on SME

#3171 Restructuring the doc on JWT grant with WSO2 IS as IDP
  en/docs/assets/img/learn/add-identity-provider.png
  en/docs/assets/img/learn/api-security/oauth2/jwt-grant/add-identity-provider.png
  en/docs/assets/img/learn/api-security/oauth2/jwt-grant/add-oauth-app.png
  en/docs/assets/img/learn/api-security/oauth2/jwt-grant/add-service-provider-menu.png
  en/docs/assets/img/learn/api-security/oauth2/jwt-grant/create-external-sp.png
  en/docs/assets/img/learn/api-security/oauth2/jwt-grant/external-oauthapp-credentials.png
  en/docs/assets/img/learn/api-security/oauth2/jwt-grant/register-oauth-app.png
  en/docs/design/api-security/oauth2/grant-types/jwt-grant.md
Labels: PR-Review/Pending Resolution

#3176 Update getting-started-with-wso2-api-controller.md
  en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
Labels: PR-Review/technical-review-done, help wanted

#3211 fixes https://github.com/wso2/docs-apim/issues/3063
  en/docs/assets/img/reference/default-json.png
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
  en/docs/reference/config-catalog.md
  en/docs/reference/understanding-the-new-configuration-model.md
  en/mkdocs.yml
Labels: API-M-Master, CEXP

#3214 fixes https://github.com/wso2/docs-apim/issues/3063 review comments
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-process.md
  en/docs/reference/understanding-the-new-configuration-model.md
Labels: API-M-3.2.0

#3215 fixes https://github.com/wso2/docs-apim/issues/3063 review comments
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-process.md
  en/docs/reference/understanding-the-new-configuration-model.md
Labels: API-M-4.0.0

#3227 Fixed warning links https://github.com/wso2/docs-apim/issues/3226
  en/docs/assets/img/integrate/broker-configs/hornetq/delete-package.png
  en/docs/assets/img/integrate/broker-configs/hornetq/sample-queue.png
  en/docs/assets/img/integrate/broker-configs/ibm-websphere-mq/119130334.png
  en/docs/assets/img/integrate/broker-configs/ibm-websphere-mq/119130335.png
  en/docs/assets/img/integrate/broker-configs/ibm-websphere-mq/119130336.png
  en/docs/assets/img/integrate/broker-configs/ibm-websphere-mq/119130337.png
  en/docs/assets/img/integrate/broker-configs/ibm-websphere-mq/119130338.png
  en/docs/assets/img/integrate/broker-configs/ibm-websphere-mq/119130339.png
  en/docs/assets/img/integrate/broker-configs/ibm-websphere-mq/119130340.png
  en/docs/assets/img/integrate/broker-configs/ibm-websphere-mq/119130341.png
  en/docs/assets/img/integrate/broker-configs/ibm-websphere-mq/119130342.png
  en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-ActiveMQ.md
  en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-HornetQ.md
  en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-IBM-websphereMQ.md
  en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-MSMQ.md
  en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-SwiftMQ.md
  en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-azureservicebus.md
  en/docs/install-and-setup/setup/mi-setup/deployment/backup_recovery.md
  en/docs/install-and-setup/setup/mi-setup/deployment/deploying_wso2_ei.md
  en/docs/install-and-setup/setup/mi-setup/deployment/migrating-from-ei-6.x.x.md
  en/docs/install-and-setup/setup/mi-setup/deployment/migrating-from-esb-5.x.x.md
  en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md
Labels: API-M-4.0.0
