Repository wso2/docs-apim, pull requests merged in 2021-05, with the labels that each got.

#3644 Add dss call mediator docs
  en/docs/reference/mediators/dss-mediator.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#3742 Distributed deployment docs for new pattern
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
  en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md
  en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md
Labels: API-M-4.0.0, PR-Review/Pending Resolution

#3797 Fixing broken links
  en/docs/install-and-setup/install-and-setup-overview.md
  en/docs/install-and-setup/setup/mi-setup/enabling_ssl_tunneling_thru_proxy_server.md
  en/docs/install-and-setup/setup/mi-setup/performance_tuning/tuning-the-vfs-transport.md
  en/docs/integrate/develop/creating-artifacts/creating-a-proxy-service.md
  en/docs/integrate/examples/proxy_service_examples/Introduction-to-proxy-services.md
  en/docs/integrate/examples/transport_examples/pub-sub-using-mqtt.md
  en/docs/integrate/integration-overview.md
  en/docs/integrate/integration-use-case/connectors.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-documents/documentdetails.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-documents/listofdocuments.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeeclockdevicegroups.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeecompensationsummary.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeecourses.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeeemploymentagreements.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeeemploymentstatuses.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeeemploymenttypes.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeehighlycompensatedemployees.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeehrincidents.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeelabordefaults.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeeonboardingpolicies.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeeorginfo.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeepayadjustmentcodegroups.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeepaygraderates.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeeperformanceratings.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeeproperties.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeeskills.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeetrainingprograms.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeeunionmemberships.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeeworkassignments.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-employment-information/employeeworkcontracts.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-personal-information/employeeaddresses.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-personal-information/employeecantaxes.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-personal-information/employeecontacts.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-personal-information/employeedirectdeposits.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-personal-information/employeeemergencycontacts.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-personal-information/employeeethnicities.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-personal-information/employeehealthandwellness.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-personal-information/employeemaritalstatuses.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-personal-information/employeeustaxes.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-time-management/availability.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-time-management/employeepunches.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-time-management/employeerawpunches.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-time-management/schedules.md
  en/docs/reference/connectors/ceridiandayforce-connector/employee-time-management/timeawayfromwork.md
  en/docs/reference/connectors/ceridiandayforce-connector/employment-eligibility-verification/i9order.md
  en/docs/reference/connectors/ceridiandayforce-connector/user-security-authority-and-management/documentmanagementsecuritygroups.md
  en/docs/reference/connectors/ceridiandayforce-connector/user-security-authority-and-management/employeelocations.md
  en/docs/reference/connectors/ceridiandayforce-connector/user-security-authority-and-management/employeemanagers.md
  en/docs/reference/connectors/ceridiandayforce-connector/user-security-authority-and-management/employeeroles.md
  en/docs/reference/connectors/ceridiandayforce-connector/user-security-authority-and-management/employeessoaccounts.md
  en/docs/reference/connectors/ceridiandayforce-connector/user-security-authority-and-management/employeeworkassignmentmanagers.md
  en/docs/reference/connectors/ceridiandayforce-connector/user-security-authority-and-management/userpayadjustmentcodegroups.md
  en/docs/reference/connectors/iso8583-connector/iso8583-connector-configuration.md
  en/docs/reference/connectors/iso8583-connector/iso8583-connector-example.md
  en/docs/reference/connectors/iso8583-connector/iso8583-connector-overview.md
  en/docs/reference/connectors/iso8583-connector/iso8583-connector-reference.md
  en/docs/reference/connectors/iso8583-connector/iso8583-inbound-endpoint-config.md
  en/docs/reference/connectors/iso8583-connector/iso8583-inbound-endpoint-example.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#3799 fixed broken links
  en/docs/integrate/develop/creating-artifacts/creating-a-proxy-service.md
  en/docs/integrate/examples/proxy_service_examples/introduction-to-proxy-services.md
  en/docs/integrate/integration-overview.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#3760 Add performance results for 4.0
  en/docs/assets/img/setup-and-install/performance-test-results/gc_0ms.png
  en/docs/assets/img/setup-and-install/performance-test-results/lineplot-average-response-time-2g-1kib-0ms.png
  en/docs/assets/img/setup-and-install/performance-test-results/lineplot-throughput-2G-50B-0ms.png
  en/docs/assets/img/setup-and-install/performance-test-results/lineplot-throughput-2g-1kib-0ms.png
  en/docs/assets/img/setup-and-install/performance-test-results/lmplot-average-response-time-concurrent-users-2g.png
  en/docs/assets/img/setup-and-install/performance-test-results/lmplot-average-response-time-message-size-2g.png
  en/docs/assets/img/setup-and-install/performance-test-results/lmplot-throughput-concurrent-users-2g.png
  en/docs/assets/img/setup-and-install/performance-test-results/lmplot-throughput-message-size-2g.png
  en/docs/assets/img/setup-and-install/performance-test-results/response_time_0ms_1kib.png
  en/docs/install-and-setup/setup/deployment-best-practices/performance-tests-results-async.md
  en/docs/install-and-setup/setup/deployment-best-practices/performance-tests-results.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#3661 AWS INIT Documentations
  en/docs/assets/img/publish/aws-api-publisher.png
  en/docs/assets/img/publish/publish-aws-api.png
  en/docs/deploy-and-publish/publish-on-dev-portal/publish-aws-apis-in-the-dev-portal.md
  en/docs/get-started/about-this-release.md
  en/mkdocs.yml
Labels: API-M-4.0.0, PR-Review/In-progress, PR-Review/technical-review-done

#3768 Update enabling cors doc for choreo connect
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/enabling-cors.md
Labels: PR-Review/In-progress

#3809 About us page improvements.
  en/docs/get-started/about-this-release.md
Labels: PR-Review/In-progress

#3767 Fix choreo-connect documentation
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/template-patterns-for-choreo-connect.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-caching.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-web-socket-api.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/rate-limiting/distributed-throttling.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-opaque-tokens.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authorization/subscription-validation.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/importing-certificates-to-the-choreo-connect-truststore.md
  en/mkdocs.yml
Labels: API-M-4.0.0, PR-Review/Pending Resolution, PR/Reviewer-Updated

#3814 [3.2.0] Update migration SQL scripts for 3.2.0
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
Labels: API-M-3.2.0, APIMINTERNAL

#3818 Review and Update the About this Release Page
  en/docs/get-started/about-this-release.md
Labels: API-M-4.0.0

#3822 Updated about this release page
  en/docs/get-started/about-this-release.md
Labels: API-M-4.0.0

#3810 Integration section update 1
  en/docs/assets/img/integrate/developing-first-integration/15-dev-get-started-aggregate-mediator.png
  en/docs/assets/img/integrate/developing-first-integration/16-dev-get-started-drop-mediator.png
  en/docs/assets/img/integrate/developing-first-integration/21-dev-get-started-dashboard-login.png
  en/docs/assets/img/integrate/developing-first-integration/22-dev-get-started-dashboard-artifact-view.png
  en/docs/assets/img/integrate/developing-first-integration/3-dev-get-started-proj-explorer.png
  en/docs/design/create-api/create-an-api-using-a-service.md
  en/docs/integrate/develop/integration-development-kickstart.md
  en/docs/integrate/develop/working-with-service-catalog.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#3705 default product ports
  en/docs/install-and-setup/setup/reference/default-product-ports.md
Labels: API-M-4.0.0, PR-Review/Pending Resolution

#3829 updated APIM fixed issue link
  en/docs/get-started/about-this-release.md
Labels: API-M-4.0.0

#3801 Add samples for API Operator API deployments
  en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-apis/api-deployments.md
  en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-apis/api-samples/sample-1-target-endpoint.md
  en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-apis/api-samples/sample-2-deployment-params-and-certs.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#3817 Review for 3773
  en/docs/assets/img/deploy/mgw/swagger-petstore-in-publisher-portal.png
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/defining-a-backend-security-scheme.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/overriding-endpoints-for-imported-apis.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-kubernetes-with-apim.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-kubernetes.md
  en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/install.md
  en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-apis/api-deployments.md
  en/mkdocs.yml
Labels: API-M-4.0.0, PR/Reviewer-Updated

#3816 Removing unwanted 3.2.0 instances from API-M migration docs
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-191-to-400.md
Labels: help wanted

#3743 Removing old Analytics content from Setup and Reference sections
  en/docs/administer/managing-users-and-roles/managing-users-for-admin-portal.md
  en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
  en/docs/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts.md
  en/docs/install-and-setup/setup/security/general-data-protection-regulation-gdpr-for-wso2-api-manager.md
  en/docs/install-and-setup/setup/setting-up-databases/overview.md
  en/docs/reference/analytics-rest-api.md
  en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md
  en/docs/reference/guides/message-flow-in-the-api-manager-gateway.md
  en/docs/reference/samples/api-rate-monetization-sample.md
  en/docs/reference/samples/api-security-sample.md
Labels: API-M-4.0.0, PR-Review/Pending Resolution

#3830 removing the WIP banner
  en/docs/assets/css/theme.css
  en/theme/material/partials/header.html
Labels: API-M-4.0.0

#3833 Add Google indexing
  en/theme/material/base.html
Labels: API-M-4.0.0

#3836 updated Angolia search
  en/theme/material/base.html
Labels: API-M-4.0.0

#3845 (4.0.0 branch) Updates related to installation guide
  en/docs/get-started/quick-start-guide/integration-qsg.md
  en/docs/get-started/quick-start-guide/quick-start-guide.md
  en/docs/get-started/quick-start-guide/streaming-qsg.md
  en/docs/install-and-setup/install/installing-the-product/installing-api-m-runtime.md
  en/docs/install-and-setup/install/installing-the-product/installing-mi-as-a-windows-service.md
  en/docs/install-and-setup/install/installing-the-product/installing-mi-dashboard.md
  en/docs/install-and-setup/install/installing-the-product/installing-mi.md
  en/docs/install-and-setup/install/installing-the-product/installing-si.md
  en/docs/install-and-setup/setup/api-controller/managing-integrations/managing-integrations-with-ctl.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.0.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.1.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.2.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.3.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.4.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.5.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.6.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.0.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.1.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-esb-5.x.x.md
  en/docs/integrate/develop/deploying-in-integration-cloud.md
  en/docs/integrate/develop/installing-wso2-integration-studio.md
  en/docs/integrate/develop/integration-development-kickstart.md
  en/docs/tutorials/integration-tutorials/exposing-several-services-as-a-single-service.md
  en/docs/tutorials/integration-tutorials/file-processing.md
  en/docs/tutorials/integration-tutorials/routing-requests-based-on-message-content.md
  en/docs/tutorials/integration-tutorials/sending-a-simple-message-to-a-datasource.md
  en/docs/tutorials/integration-tutorials/sending-a-simple-message-to-a-service.md
  en/docs/tutorials/integration-tutorials/service-catalog-tutorial.md
  en/docs/tutorials/integration-tutorials/storing-and-forwarding-messages.md
  en/docs/tutorials/integration-tutorials/transforming-message-content.md
  en/docs/tutorials/integration-tutorials/using-inbound-endpoints.md
  en/docs/tutorials/integration-tutorials/using-scheduled-tasks.md
  en/docs/tutorials/integration-tutorials/using-templates.md
  en/docs/tutorials/integration-tutorials/using-the-gmail-connector.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#3869 Update About This Release Page for SI Tooling section
  en/docs/get-started/about-this-release.md
Labels: PR-Review/In-progress

#3870 Add about release content for SI
  en/docs/get-started/about-this-release.md
Labels: PR-Review/In-progress

#3867 Adds APIM analytics pages documentation
  en/docs/assets/img/observe/alerts/alert-config-full.png
  en/docs/assets/img/observe/alerts/api-name-dropdown.png
  en/docs/assets/img/observe/alerts/latency-config-modify.png
  en/docs/assets/img/observe/alerts/latency-metric-type.png
  en/docs/assets/img/observe/alerts/latency-success.png
  en/docs/assets/img/observe/alerts/latency-threshold.png
  en/docs/assets/img/observe/alerts/traffic-alert-config-full.png
  en/docs/assets/img/observe/alerts/traffic-config-editable.png
  en/docs/assets/img/observe/alerts/traffic-metric-type.png
  en/docs/assets/img/observe/alerts/traffic-success.png
  en/docs/assets/img/observe/alerts/traffic-threshold.ong.png
  en/docs/assets/img/observe/overview/overview-page-error-rate.png
  en/docs/assets/img/observe/overview/overview-page-full.png
  en/docs/assets/img/observe/overview/overview-page-latency.png
  en/docs/assets/img/observe/overview/overview-page-timeline.png
  en/docs/assets/img/observe/overview/overview-page-total-traffic.png
  en/docs/observe/api-manager-analytics/analytics-pages/analytics-pages-alerts.md
  en/docs/observe/api-manager-analytics/analytics-pages/analytics-pages-introduction.md
  en/docs/observe/api-manager-analytics/analytics-pages/analytics-pages-overview.md
  en/docs/observe/api-manager-analytics/configure-analytics/configure-alerts.md
Labels: PR-Review/In-progress

#3902 Update WSO2 IS toml config
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: APIMINTERNAL, CEXP

#3901 Update WSO2 IS toml config
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: APIMINTERNAL, CEXP

#3905 Explaining the "re_indexing"config in the migration docs
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
Labels: APIMINTERNAL, CEXP

#3906 Explaining the "re_indexing"config in the migration docs
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md
Labels: APIMINTERNAL, CEXP

#3908 Explaining the "re_indexing"config in the migration docs
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md
Labels: APIMINTERNAL, CEXP

#3895 [4.0.0] Remove listing K8s AM Operator, without removing content
  en/mkdocs.yml
Labels: API-M-4.0.0

#3893 Remove listing K8s AM Operator, without removing content
  en/mkdocs.yml
Labels: API-M-4.0.0

#3879 Update as-a-standalone-gateway.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/as-a-standalone-gateway.md
Labels: Docs/Waiting on SME

#3975 fixed links
  README.md
  en/docs/develop/customizations/adding-a-user-signup-workflow-using-bps.md
  en/docs/develop/customizations/customize-the-api-store-and-gateway-urls-for-tenants.md
  en/docs/develop/customizations/customizing-login-pages-for-dev-portal-and-publisher.md
  en/docs/develop/customizations/log-in-to-the-dev-portal-using-social-media.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
  en/docs/learn/analytics/configuring-alerts.md
  en/docs/learn/api-gateway/message-mediation/configuring-message-builders-formatters.md
  en/docs/learn/api-gateway/message-mediation/transforming-api-message-payload.md
  en/docs/learn/api-monetization/monetizing-an-api.md
  en/docs/learn/api-security/api-authentication/secure-apis-using-basic-authentication.md
  en/docs/learn/api-security/oauth2/grant-types/implicit-grant.md
  en/docs/learn/consume-api/generating-sdks/write-a-client-application-using-the-sdk.md
  en/docs/learn/design-api/advanced-topics/control-api-visibility-and-subscription-availability-in-developer-portal.md
  en/docs/learn/design-api/api-documentation/add-api-documentation.md
  en/docs/learn/design-api/create-api/test-a-rest-api.md
  en/docs/learn/design-api/publish-api/publish-an-api-to-a-cloud-cluster-in-privatejet-mode.md
  en/docs/learn/design-api/publish-api/publish-an-api.md
  en/docs/reference/faq.md
  en/docs/troubleshooting/error-handling.md
Labels: 4.0.0-post

#3980 fixes https://github.com/wso2/docs-apim/issues/3978
  en/docs/learn/analytics/analytics-event-streams-and-aggregations.md
Labels: 4.0.0-post

#3970 [4.0.0] Update 4.0.0 REST APIs
  en/docs/assets/attachments/reference/admin-v2_postman_collection.json
  en/docs/assets/attachments/reference/devportal-v2_postman_collection.json
  en/docs/assets/attachments/reference/publisher-v2_postman_collection.json
  en/docs/reference/product-apis/admin-apis/admin-v2/admin-v2.yaml
  en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml
  en/docs/reference/product-apis/overview.md
  en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
  en/mkdocs.yml
Labels: Docs/SyncPR-Pending

#3992 Update "CaseInsensitiveUsername" in Config Catalog
  en/docs/reference/config-catalog.md
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/dist/config-catalog.md
Labels: APIMINTERNAL, CEXP

#2089 [3.2.0]Add proxy support related docs for APICTL
  en/docs/learn/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md
  en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
Labels: API-M-3.2.0, Docs/Waiting on SME, PR-Review/technical-review-done

#3995 Adds devices and reports page
  en/docs/assets/img/observe/devices/api-selector.png
  en/docs/assets/img/observe/devices/devices-page-full.png
  en/docs/assets/img/observe/devices/top-platforms.png
  en/docs/assets/img/observe/devices/top-user-agents.png
  en/docs/assets/img/observe/overview/overview-page-error-rate.png
  en/docs/assets/img/observe/overview/overview-page-latency.png
  en/docs/assets/img/observe/overview/overview-page-total-traffic.png
  en/docs/assets/img/observe/report/configured-report.png
  en/docs/assets/img/observe/report/custom-report-sample.png
  en/docs/assets/img/observe/report/custom-report.png
  en/docs/assets/img/observe/report/report-page-full.png
  en/docs/observe/api-manager-analytics/analytics-pages/analytics-pages-devices.md
  en/docs/observe/api-manager-analytics/analytics-pages/analytics-pages-report.md
Labels: API-M-4.0.0

#4027 Add the log layout pattern related docs for 3.2.0
  en/docs/administer/logging-and-monitoring/logging/setting-up-logging.md
Labels: API-M-3.2.0, CEXP

#4039 fixes https://github.com/wso2/docs-apim/issues/4038
  en/docs/design/api-security/threat-protection/bot-detection.md
  en/docs/get-started/architecture.md
  en/docs/observe/api-manager-analytics/configuring-alerts.md
  en/docs/observe/api-manager-analytics/configuring-apim-analytics.md
  en/docs/observe/api-manager-analytics/purging-analytics-data.md
  en/docs/observe/api-manager-analytics/subscribing-for-alerts.md
Labels: API-M-4.0.0

#4041 fix for https://github.com/wso2/docs-apim/issues/4040
  en/docs/consume/manage-subscription/advanced-topics/adding-an-api-subscription-workflow.md
Labels: 4.0.0-post

#4043 removed old samples
  en/docs/reference/samples/api-development-sample/collaborative-api-development-sample.md
  en/docs/reference/samples/api-development-sample/development-of-developer-optimized-apis-sample.md
  en/docs/reference/samples/api-development-sample/managing-apis-sample.md
  en/docs/reference/samples/api-governance-sample.md
  en/docs/reference/samples/api-lifecycle-management-sample.md
  en/docs/reference/samples/api-rate-limiting-sample.md
  en/docs/reference/samples/api-rate-monetization-sample.md
  en/docs/reference/samples/api-security-sample.md
  en/docs/reference/samples/api-versioning-sample.md
  en/mkdocs.yml
Labels: API-M-4.0.0, Docs/SyncPR-Pending

#4049 Added redirections for develop section
  en/mkdocs.yml
Labels: 4.0.0-post, API-M-4.0.0

#4057 Update Docs with Keystore Configs & API Key Keystore Configs
  en/docs/learn/api-security/api-authentication/secure-apis-using-api-keys.md
  en/docs/reference/config-catalog.md
  en/tools/config-catalog-generator/data/configs.json
  en/tools/config-catalog-generator/data/custom_keystore.toml
  en/tools/config-catalog-generator/dist/config-catalog.md
Labels: APIMINTERNAL, CEXP

#4061 add google site verification
  en/docs/google5db3f40334e06fa3.html
Labels: API-M-3.2.0

#4065 fixes https://github.com/wso2/docs-apim/issues/4064
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md
Labels: API-M-4.0.0

#4067 updated based on review comments
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md
Labels: API-M-4.0.0

#4066 fixes https://github.com/wso2/docs-apim/issues/4064
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md
Labels: API-M-Master

#4069 fixes https://github.com/wso2/docs-apim/issues/4068
  en/docs/integrate/develop/customizations/creating-synapse-handlers.md
Labels: API-M-4.0.0

#4070 fixes https://github.com/wso2/docs-apim/issues/4068
  en/docs/integrate/develop/customizations/creating-synapse-handlers.md
Labels: API-M-Master

#4052 (4.0.0 doc) Updating the Security Guidelines documentation
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Labels: 4.0.0-post, PR-Review/Pending Resolution

#3824 Adding docs for Choreo Connect Analytics
  en/docs/assets/img/deploy/choreo-analytics-latency.png
  en/docs/assets/img/deploy/choreo-analytics-overview.png
  en/docs/assets/img/deploy/choreo-analytics-traffic.png
  en/docs/assets/img/deploy/mgw/analytics-architecture.png
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/choreo-connect-analytics.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/analytics-configurations.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
  en/mkdocs.yml
Labels: API-M-4.0.0, API-M-Master

#4079 MI dashboard configuration
  en/docs/install-and-setup/install/installing-the-product/installing-mi-dashboard.md
Labels: API-M-4.0.0, APIMINTERNAL, CEXP

#4080 MI dashboard configuration
  en/docs/install-and-setup/install/installing-the-product/installing-mi-dashboard.md
Labels: API-M-Master, APIMINTERNAL, CEXP

#4060 (4.0.0 branch) Updating the default ports documentation
  en/docs/install-and-setup/setup/deployment-best-practices/changing-the-default-ports-with-offset.md
  en/docs/install-and-setup/setup/reference/default-product-ports.md
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: PR-Review/In-progress

#4074 Using a certificate with wildcard CN
  en/docs/install-and-setup/setup/security/configuring-keystores/keystore-basics/creating-new-keystores.md
Labels: API-M-3.1.0, APIMINTERNAL, CEXP

#4075 Using a certificate with wildcard CN
  en/docs/administer/product-security/configuring-keystores/keystore-basics/creating-new-keystores.md
Labels: API-M-3.0.0, APIMINTERNAL, CEXP

#4076 Using a certificate with wildcard CN
  en/docs/install-and-setup/setup/security/configuring-keystores/keystore-basics/creating-new-keystores.md
Labels: API-M-3.2.0, APIMINTERNAL, CEXP

#4077 Using a certificate with wildcard CN
  en/docs/install-and-setup/setup/security/configuring-keystores/keystore-basics/creating-new-keystores.md
Labels: API-M-4.0.0, APIMINTERNAL, CEXP

#4078 Using a certificate with wildcard CN
  en/docs/install-and-setup/setup/security/configuring-keystores/keystore-basics/creating-new-keystores.md
Labels: API-M-Master, APIMINTERNAL, CEXP

#3896 Adding mi helm resource doc
  en/docs/install-and-setup/setup/mi-setup/deployment/deploying-micro-integrator-with-helm.md
Labels: PR-Review/In-progress

#4086 (4.0.0 branch) Updates to Helm docs for MI
  en/docs/install-and-setup/setup/mi-setup/deployment/kubernetes_deployment.md
  en/mkdocs.yml
Labels: 4.0.0-post

#4088 (4.0.0 branch) Fixing the heading
  en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md
Labels: 4.0.0-post

#4089 (4.0.0 branch) Broken links
  en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md
Labels: 4.0.0-post

#4090 (4.0.0 branch) broken links in ports section
  en/docs/install-and-setup/setup/deployment-best-practices/changing-the-default-ports-with-offset.md
Labels: 4.0.0-post

#4099 (4.0.0 branch) download link of APICTL
  en/docs/reference/apictl/wso2-api-controller.md
Labels: 4.0.0-post

#4101 Update screenshots for Working with Organizations
  en/docs/assets/img/observe/invite-dialogue-box.png
  en/docs/assets/img/observe/organization-page.png
  en/docs/assets/img/observe/organization-selector.png
Labels: 4.0.0-post

#4091 (Master branch) Broken links
  en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md
Labels: 4.0.0-post

#4111 fixes #4108
  en/docs/design/api-security/threat-protection/gateway-threat-protectors/gateway-threat-protectors-for-api-manager.md
Labels: API-M-4.0.0, Docs/SyncPR-Pending

#4085 [3.0.0] Add Registry DB clean up scripts
  en/docs/administer/product-administration/removing-unused-tokens-from-the-database.md
Labels: APIMINTERNAL, CEXP

#4093 (4.0.0 branch) Running the API-M runtime doc
  en/docs/assets/img/setup-and-install/running-product-dev-portal-url.png
  en/docs/assets/img/setup-and-install/running-product-mgt-console-url.png
  en/docs/assets/img/setup-and-install/running-product-publisher-url.png
  en/docs/install-and-setup/install/installing-the-product/running-the-api-m.md
  en/docs/install-and-setup/install/installing-the-product/running-the-mi-dashboard.md
  en/docs/install-and-setup/install/installing-the-product/running-the-mi.md
  en/docs/install-and-setup/install/installing-the-product/running-the-si.md
  en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
  en/docs/install-and-setup/setup/security/securing-api-m-web-portals.md
  en/mkdocs.yml
Labels: 4.0.0-post

#4094 [4.0.0] Add choreo connect to about this release page
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/inter-component-communication.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/importing-certificates-to-the-choreo-connect-truststore.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/transport-security.md
  en/docs/get-started/about-this-release.md
  en/mkdocs.yml
Labels: 4.0.0-post, PR-Review/Pending Resolution

#3835 Add choreo connect to about this release page
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/inter-component-communication.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/importing-certificates-to-the-choreo-connect-truststore.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/transport-security.md
  en/docs/get-started/about-this-release.md
  en/mkdocs.yml
Labels: 4.0.0-post, PR-Review/Pending Resolution

#3839 Add configure multiple gateways in choreo connect docs
  en/docs/assets/img/deploy/mgw/add-gateway-environment.png
  en/docs/assets/img/deploy/mgw/distributed-adapter-pattern.png
  en/docs/assets/img/deploy/mgw/single-adapter-pattern.png
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/event-hub.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-multiple-gateways-with-choreo-connect.md
  en/mkdocs.yml
Labels: 4.0.0-post, PR-Review/Pending Resolution

#3863 [4.0.0] Add multiple gateways with choreo connect docs
  en/docs/assets/img/deploy/mgw/add-gateway-environment.png
  en/docs/assets/img/deploy/mgw/distributed-adapter-pattern.png
  en/docs/assets/img/deploy/mgw/single-adapter-pattern.png
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/event-hub.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-multiple-gateways-with-choreo-connect.md
  en/mkdocs.yml
Labels: 4.0.0-post, PR-Review/Pending Resolution

#4117 [4.0.0 branch] Update "Override API Overview page per API" Document
  en/docs/assets/img/learn/override-api-overview-page-per-api-devportal.png
  en/docs/assets/img/learn/override-api-overview-page-per-api-publisher1.png
  en/docs/assets/img/learn/override-api-overview-page-per-api-publisher2.png
  en/docs/assets/img/reference/customizations/override-api-overview-page/override-api-overview-page-per-api-devportal.png
  en/docs/assets/img/reference/customizations/override-api-overview-page/override-api-overview-page-per-api-publisher1.png
  en/docs/assets/img/reference/customizations/override-api-overview-page/override-api-overview-page-per-api-publisher2.png
  en/docs/assets/img/reference/customizations/override-api-overview-page/override-api-overview-page-per-api-publisher3.png
  en/docs/reference/customize-product/customizations/customizing-the-developer-portal/override-api-overview-page-per-api.md
Labels: 4.0.0-post

#4116 [master branch] Update "Override API Overview page per API" Document
  en/docs/assets/img/learn/override-api-overview-page-per-api-devportal.png
  en/docs/assets/img/learn/override-api-overview-page-per-api-publisher1.png
  en/docs/assets/img/learn/override-api-overview-page-per-api-publisher2.png
  en/docs/assets/img/reference/customizations/override-api-overview-page/override-api-overview-page-per-api-devportal.png
  en/docs/assets/img/reference/customizations/override-api-overview-page/override-api-overview-page-per-api-publisher1.png
  en/docs/assets/img/reference/customizations/override-api-overview-page/override-api-overview-page-per-api-publisher2.png
  en/docs/assets/img/reference/customizations/override-api-overview-page/override-api-overview-page-per-api-publisher3.png
  en/docs/reference/customize-product/customizations/customizing-the-developer-portal/override-api-overview-page-per-api.md
Labels: 4.0.0-post

#4082 (Master branch) Updating the default ports documentation
  en/docs/install-and-setup/setup/deployment-best-practices/changing-the-default-ports-with-offset.md
  en/docs/install-and-setup/setup/reference/default-product-ports.md
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: 4.0.0-post

#4083 (Master branch) Updating the Security Guidelines documentation
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Labels: 4.0.0-post

#4087 (Master branch) Updates to Helm docs for MI
  en/docs/install-and-setup/setup/mi-setup/deployment/deploying-micro-integrator-with-helm.md
  en/docs/install-and-setup/setup/mi-setup/deployment/kubernetes_deployment.md
  en/mkdocs.yml
Labels: 4.0.0-post
