Repository wso2/docs-apim, pull requests merged in 2021-10, with the labels that each got.

#4786 Add GeoLocation data population capability for Windows and Fix 'update-geolocation-data.sh' for Linux
  en/docs/assets/attachments/learn/analytics/geo-location/linux/update-geolocation-data.sh
  en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/using-geo-location-based-statistics/creating-geo-location-data-set.md
Labels: CEXP

#4787 Fix Step 4 - View the Analytics Dashboards section link in the QSG
  en/docs/api-analytics/getting-started-guide.md
Labels: CEXP

#4788 Fix Step 4 - View the Analytics Dashboards section link in the QSG
  en/docs/api-analytics/getting-started-guide.md
Labels: CEXP

#4791 Add auto generate dataservices docs
  en/docs/assets/img/integrate/tutorials/data_services/generate_dataservice.png
  en/docs/assets/img/integrate/tutorials/data_services/generate_dataservice_select_datasource.png
  en/docs/assets/img/integrate/tutorials/data_services/select_driver_file_system.png
  en/docs/assets/img/integrate/tutorials/data_services/select_existing_driver.png
  en/docs/assets/img/integrate/tutorials/data_services/select_tables.png
  en/docs/get-started/about-this-release.md
  en/docs/integrate/develop/creating-artifacts/data-services/creating-data-services.md
  en/docs/integrate/develop/creating-artifacts/data-services/creating-datasources.md
  en/docs/tutorials/integration-tutorials/sending-a-simple-message-to-a-datasource.md
  en/mkdocs.yml
Labels: Type/New Feature, API-M-4.1.0

#4792 fix for https://github.com/wso2/docs-apim/issues/4781
  en/docs/assets/img/integrate/use-cases-overview/message-gateway.png
  en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md
  en/docs/integrate/integration-use-case/gateway-overview.md
Labels: API-M-4.0.0

#4793 fix for https://github.com/wso2/docs-apim/issues/4781
  en/docs/assets/img/integrate/use-cases-overview/message-gateway.png
  en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md
  en/docs/integrate/integration-use-case/gateway-overview.md
Labels: API-M-4.1.0

#4795 fixes https://github.com/wso2/docs-apim/issues/4794
  en/docs/design/api-security/oauth2/grant-types/client-credentials-grant.md
Labels: API-M-4.0.0

#4796 fixes https://github.com/wso2/docs-apim/issues/4794
  en/docs/design/api-security/oauth2/grant-types/client-credentials-grant.md
Labels: API-M-4.1.0

#4816 Improvement for Gateway Rest API
  en/docs/develop/product-apis/gateway-apis/gateway-v1/gateway-v1.yaml
Labels: CEXP

#4811 PR Review for PKCE feature
  en/docs/assets/img/learn/application-key-generation.png
  en/docs/assets/img/learn/application-key-secret-view.png
  en/docs/assets/img/learn/application-select.png
  en/docs/assets/img/learn/key-generation-with-pkce-bypass-secret.png
  en/docs/assets/img/learn/key-generation-with-pkce-plain.png
  en/docs/assets/img/learn/key-generation-with-pkce.png
  en/docs/consume/manage-application/generate-keys/generate-api-keys.md
  en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/message-mediation/passing-a-custom-authorization-token-to-the-backend.md
  en/docs/get-started/about-this-release.md
Labels: API-M-4.1.0

#4823 Improvement for Gateway Rest API
  en/docs/reference/product-apis/gateway-apis/gateway-v1/gateway-v1.yaml
Labels: CEXP

#4824 SMPP Connector - Bulk messaging section
  en/docs/reference/connectors/smpp-connector/smpp-connector-config.md
Labels: CEXP

#4825 SMPP Connector - Bulk messaging section
  en/docs/reference/connectors/smpp-connector/smpp-connector-config.md
Labels: CEXP

#4845 Remove H2 DB Scripts from the Migration Documents
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
Labels: CEXP

#4852 Change parameter 'receiver_username' in 'Setup e-mail login' section
  en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md
Labels: CEXP

#4855 Remove H2 DB Scripts from the Migration Documents
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md
Labels: API-M-3.1.0, CEXP

#4857 fixes https://github.com/wso2/docs-apim/issues/4851
  en/mkdocs.yml
Labels: API-M-4.0.0

#4865 Fix typo for truststore parameter
  en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md
Labels: CEXP

#4864 Fix typo for truststore parameter
  en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md
Labels: CEXP

#4863 Fix typo for truststore parameter
  en/docs/administer/product-security/logins-and-passwords/working-with-encrypted-passwords.md
Labels: CEXP
