Repository wso2/docs-apim, pull requests merged in 2022-01, with the labels that each got.

#5156 Use web page to download the CC distribution instead of GitHub repo
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-via-apictl.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-docker.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-apim-as-control-plane.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/interceptor-microservice.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/message-transformation-overview.md
Labels: API-M-4.0.0, docs/choreo-connect

#5157 Use web page to download the CC distribution instead of GitHub repo
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-docker.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-apim-as-control-plane.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/interceptor-microservice.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/message-transformation-overview.md
Labels: docs/choreo-connect

#5179 Update WSO2 IS connector links
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: API-M-3.2.0

#5098 added publisher read only mode docs
  en/docs/assets/img/learn/api-security/read-only-api-details.png
  en/docs/assets/img/learn/api-security/read-only-api-view.png
  en/docs/assets/img/learn/api-security/read-only-user-creation.png
  en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
  en/docs/get-started/about-this-release.md
  en/mkdocs.yml
Labels: PR-Review/Pending Resolution, API-M-4.1.0

#5182 Update WSO2IS connector links
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Labels: API-M-3.2.0

#5178 [CC][master] Improvements to CC docs
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/as-a-standalone-gateway.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-apis-as-immutable-gateway.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-rest-api-in-choreo-connect.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/failover-endpoints.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/load-balanced-endpoints.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-docker.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/defining-interceptors-in-an-open-api-definition.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/message-transformation-overview.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/oauth2-access-tokens.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/importing-certificates-to-the-choreo-connect-truststore.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/tls/backend-certificates.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/tls/component-certificates.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/use-a-custom-authorization-header.md
  en/docs/deploy-and-publish/deploy-on-gateway/deploying-apis-in-api-gateway-vs-choreo-connect.md
  en/mkdocs.yml
Labels: PR-Review/Pending Resolution, API-M-4.1.0

#5199 [CC][4.0.0] Improvements to CC docs
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/as-a-standalone-gateway.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-apis-as-immutable-gateway.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-rest-api-in-choreo-connect.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/failover-endpoints.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/load-balanced-endpoints.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-docker.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/defining-interceptors-in-an-open-api-definition.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/message-transformation-overview.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/oauth2-access-tokens.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/importing-certificates-to-the-choreo-connect-truststore.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/tls/backend-certificates.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/tls/component-certificates.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/use-a-custom-authorization-header.md
  en/docs/deploy-and-publish/deploy-on-gateway/deploying-apis-in-api-gateway-vs-choreo-connect.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#5202 [CC][master] Add transport security redirects
  en/mkdocs.yml
Labels: API-M-4.1.0

#5204 fixes https://github.com/wso2/docs-apim/issues/5203
  en/docs/assets/attachments/administer/custom.tracing.client.zip
  en/docs/observe/api-manager/traces/monitoring-with-opentracing.md
Labels: API-M-4.0.0

#5212 fixes https://github.com/wso2/docs-apim/issues/5203
  en/docs/assets/attachments/administer/custom.tracing.client.zip
  en/docs/observe/api-manager/traces/monitoring-with-opentracing.md
Labels: CEXP, API-M-4.1.0

#5206 fixes https://github.com/wso2/docs-apim/issues/5205
  en/mkdocs.yml
Labels: API-M-4.0.0

#5207 fixes https://github.com/wso2/docs-apim/issues/5205
  en/mkdocs.yml
Labels: API-M-4.1.0

#5192 Modify documentation to reflect the exclusion of http4e client from IntegrationStudio
  en/docs/assets/img/integrate/tutorials/119132155/rdbms-employee.png
  en/docs/assets/vids/healthcare-doctor-ophthalmologist.webm
  en/docs/assets/vids/query-doctor-surgery.webm
  en/docs/assets/vids/surgery-reserve.webm
  en/docs/integrate/develop/integration-development-kickstart.md
  en/docs/integrate/develop/using-http_rest_client.md
  en/docs/integrate/develop/wso2-integration-studio.md
  en/docs/tutorials/integration-tutorials/routing-requests-based-on-message-content.md
  en/docs/tutorials/integration-tutorials/sending-a-simple-message-to-a-datasource.md
  en/docs/tutorials/integration-tutorials/sending-a-simple-message-to-a-service.md
  en/docs/tutorials/integration-tutorials/storing-and-forwarding-messages.md
  en/docs/tutorials/integration-tutorials/transforming-message-content.md
  en/docs/tutorials/integration-tutorials/using-inbound-endpoints.md
  en/docs/tutorials/integration-tutorials/using-templates.md
  en/docs/tutorials/integration-tutorials/using-the-gmail-connector.md
Labels: PR-Review/Pending Resolution, API-M-4.1.0

#5213 Fixes https://github.com/wso2/docs-apim/issues/5205
  en/docs/consume/consume-api-overview.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/include-additional-headers-in-the-api-console.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-a-soap-client.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/try-out-using-postman.md
Labels: API-M-4.1.0

#5217 fixes https://github.com/wso2/docs-apim/issues/5205
  en/docs/consume/consume-api-overview.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/include-additional-headers-in-the-api-console.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-a-soap-client.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/try-out-using-postman.md
Labels: API-M-4.0.0

#5218 fixing lifecycle and version menu
  en/mkdocs.yml
Labels: API-M-4.0.0

#5219 fixing lifecycle and version menu
  en/mkdocs.yml
Labels: API-M-4.1.0

#5220 Add note for the deprecated expand parameter
  en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
Labels: CEXP

#5221 Add note for the deprecated expand parameter
  en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
Labels: CEXP

#5224 Add health check info for web socket ports
  en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md
Labels: API-M-3.2.0

#5215 Add K8s based CICD doc for SI
  en/docs/assets/img/deploy/si-cicd-k8s.png
  en/docs/install-and-setup/setup/mi-setup/deployment/mi-cicd-overview.md
  en/docs/install-and-setup/setup/si-setup/si-cicd-k8s.md
  en/mkdocs.yml
Labels: PR-Review/Pending Resolution
