Repository wso2/docs-apim, pull requests merged in 2022-02, with the labels that each got.

#5236 fixes build break
  en/mkdocs.yml
Labels: Priority/Highest, API-M-4.1.0

#5214 Choreo Connect 1.0.0 - Helm QSG and Production deployment guide
  en/docs/assets/img/deploy/mgw/helm.png
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/as-a-standalone-gateway.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes-helm-artifacts.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-deploy-overview.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
  en/docs/deploy-and-publish/deploy-on-gateway/deploying-apis-in-api-gateway-vs-choreo-connect.md
  en/docs/includes/deploy/cc-prod-guide-helm-values-yaml-tip.md
  en/mkdocs.yml
Labels: API-M-4.0.0, docs/choreo-connect

#5245 fixes https://github.com/wso2/docs-apim/issues/4363
  en/docs/develop/streaming-apps/installing-siddhi-extensions.md
  en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md
  en/docs/reference/mediators/property-reference/soap-headers.md
Labels: API-M-4.0.0

#5248 Google search console verification
  en/docs/google5db3f40334e06fa3.html
Labels: API-M-3.1.0

#5249 Removing Google Console ref
  en/docs/google186eb945fa6366b0.html
Labels: API-M-4.1.0

#5257 docs for Top down API development
  en/docs/assets/img/tutorials/api-from-scratch-menu.png
  en/docs/assets/img/tutorials/create-healthcare-api.png
  en/docs/assets/img/tutorials/import-api-from-apim.png
  en/docs/assets/img/tutorials/mi-config-icon.png
  en/docs/assets/img/tutorials/new-synapse-api-options.png
  en/docs/assets/img/tutorials/project-explorer.png
  en/docs/assets/img/tutorials/querydocter-resource.png
  en/docs/tutorials/develop-an-integration-with-a-managed-api.md
  en/mkdocs.yml
Labels: API-M-4.1.0

#5260 CC request body passing
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/extensions/custom-filters.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/extensions/request-payload-passing.md
  en/docs/reference/vendor-extensions-catalog.md
  en/mkdocs.yml
  en/tools/config-catalog-generator-cc/data/router/configs.json
  en/tools/config-catalog-generator-cc/data/router/request_payload_passing.toml
  en/tools/config-catalog-generator-cc/dist/router-configurations.md
Labels: PR/Reviewer-Updated, API-M-4.1.0

#5262 partly fixes https://github.com/wso2/docs-apim/issues/5261
  en/docs/design/advanced-topics/adding-an-api-state-change-workflow-using-bps.md
  en/docs/design/api-security/oauth2/grant-types/password-grant.md
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
  en/docs/troubleshooting/error-handling.md
  en/docs/troubleshooting/troubleshooting-invalid-callback-error.md
  en/mkdocs.yml
Labels: API-M-4.1.0

#5263 partly fixes https://github.com/wso2/docs-apim/issues/5261
  en/docs/design/advanced-topics/adding-an-api-state-change-workflow-using-bps.md
  en/docs/design/api-security/oauth2/grant-types/password-grant.md
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
  en/docs/troubleshooting/error-handling.md
  en/docs/troubleshooting/troubleshooting-invalid-callback-error.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#5266 fixes https://github.com/wso2/docs-apim/issues/5244
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
Labels: API-M-4.0.0

#5267 fixes https://github.com/wso2/docs-apim/issues/5244
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
Labels: API-M-4.1.0

#5254 Third-party API support in WSO2 API Manager
  en/docs/assets/img/develop/async-api.png
  en/docs/assets/img/develop/convert-to-third-party.png
  en/docs/assets/img/develop/third-party-tag.png
  en/docs/deploy-and-publish/publish-on-dev-portal/third-party-api-support.md
  en/mkdocs.yml
Labels: API-M-4.1.0

#5269 Fixed parameter in toml sample
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
Labels: CEXP

#5278 fix related to https://github.com/wso2/docs-apim/issues/5277
  en/docs/develop/streaming-apps/http-status-codes.md
Labels: API-M-4.1.0

#5279 fix related to https://github.com/wso2/docs-apim/issues/5277
  en/docs/develop/streaming-apps/http-status-codes.md
  en/docs/troubleshooting/configuring-xslt-mediation-with-xalan.md
Labels: API-M-4.0.0

#5283 PR sync for https://github.com/wso2/docs-apim/pull/5279
  en/docs/troubleshooting/configuring-xslt-mediation-with-xalan.md
Labels: API-M-4.1.0

#5284 fixes A-1650
  en/docs/learn/analytics/encrypting-sensitive-data-in-apim-analytics.md
Labels: API-M-3.2.0, CEXP

#5285 fixes A-1650
  en/docs/learn/analytics/encrypting-sensitive-data-in-apim-analytics.md
  en/mkdocs.yml
Labels: API-M-3.2.0, CEXP

#5288 fixes A-1650
  en/docs/learn/analytics/encrypting-sensitive-data-in-apim-analytics.md
Labels: API-M-3.2.0, CEXP

#5289 reviewed and updated
  en/docs/learn/analytics/encrypting-sensitive-data-in-apim-analytics.md
Labels: API-M-3.1.0

#5290 fixes https://github.com/wso2/docs-apim/issues/5258
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md
Labels: component/migration, API-M-4.0.0

#5291 fixes https://github.com/wso2/docs-apim/issues/5258
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md
Labels: component/migration, API-M-4.1.0

#5292 fixes #5264 and #5281
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md
  en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md
Labels: component/migration, API-M-4.0.0

#5295 fixes A-1686
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
Labels: CEXP, component/migration, API-M-4.0.0

#5296 fixes A-1686
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
Labels: component/migration, API-M-4.1.0

#5293 fixes #5264 #5281
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md
  en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md
Labels: component/migration, API-M-4.1.0

#5304 Error Code Link fix master
  en/docs/design/endpoints/resiliency/endpoint-timeouts.md
Labels: API-M-4.1.0

#5297 Change websocket health check path
  en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md
Labels: API-M-3.2.0

#5286 Add additional loggable properties
  en/docs/observe/api-manager/monitoring-api-logs.md
Labels: API-M-4.1.0

#5308 Changed Copyrights year to 2022
  en/theme/material/partials/footer.html
Labels: API-M-3.2.0

#5307 Changed Copyrights year to 2022
  en/theme/material/partials/footer.html
Labels: API-M-4.0.0

#5310 Changed Copyrights year to 2022
  en/theme/material/partials/footer.html
Labels: API-M-3.0.0

#5309 Changed Copyrights year to 2022
  en/theme/material/partials/footer.html
Labels: API-M-3.1.0

#5313 fix #https://github.com/wso2/docs-apim/issues/5311
  en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
Labels: API-M-4.0.0

#5314 fixes https://github.com/wso2/docs-apim/issues/5311
  en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
Labels: API-M-4.1.0

#5306 fixes A-1689
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
Labels: API-M-4.1.0

#5305 fixes A-1689
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
Labels: API-M-4.0.0

#5323 Add websocket health check api details
  en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md
Labels: API-M-4.1.0

#5322 fixes https://github.com/wso2/docs-apim/issues/4999
  en/docs/install-and-setup/install/installing-the-product/running-the-mi.md
  en/docs/integrate/develop/integration-development-kickstart.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#5321 fixes https://github.com/wso2/docs-apim/issues/4999
  en/docs/install-and-setup/install/installing-the-product/running-the-mi.md
  en/docs/integrate/develop/integration-development-kickstart.md
  en/mkdocs.yml
Labels: API-M-4.1.0

#5327 fixes https://github.com/wso2/docs-apim/issues/5318
  en/docs/design/api-security/oauth2/access-token-types/jwt-tokens.md
Labels: API-M-4.0.0

#5328 fixes https://github.com/wso2/docs-apim/issues/5318
  en/docs/design/api-security/oauth2/access-token-types/jwt-tokens.md
Labels: API-M-4.1.0

#5325 fixes https://github.com/wso2/docs-apim/issues/5324
  en/docs/design/rate-limiting/graphql-api/overview-query-limits-for-graphql.md
Labels: API-M-4.1.0

#5326 fixes https://github.com/wso2/docs-apim/issues/5324
  en/docs/design/rate-limiting/graphql-api/overview-query-limits-for-graphql.md
Labels: API-M-4.0.0

#5330 fixes https://github.com/wso2/docs-apim/issues/5231
  en/mkdocs.yml
Labels: API-M-4.0.0

#5333 fixes https://github.com/wso2/docs-apim/issues/4998
  en/docs/integrate/develop/advanced-development/applying-security-to-a-proxy-service.md
Labels: API-M-4.0.0

#5334 fixes https://github.com/wso2/docs-apim/issues/4998
  en/docs/integrate/develop/advanced-development/applying-security-to-a-proxy-service.md
Labels: API-M-4.1.0

#5337 fixes https://github.com/wso2/docs-apim/pull/5336
  en/docs/reference/customize-product/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
Labels: API-M-4.1.0

#5339 fixes https://github.com/wso2/docs-apim/issues/5316
  en/docs/design/api-documentation/add-api-documentation.md
Labels: API-M-4.1.0

#5338 fixes https://github.com/wso2/docs-apim/issues/5316
  en/docs/design/api-documentation/add-api-documentation.md
Labels: API-M-4.0.0

#5340 fixes https://github.com/wso2/docs-apim/issues/5273
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-example.png
  en/docs/reference/connectors/salesforce-connectors/sf-inbound-endpoint-example.md
Labels: API-M-4.0.0

#5341 fixes https://github.com/wso2/docs-apim/issues/5273
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-example.png
  en/docs/reference/connectors/salesforce-connectors/sf-inbound-endpoint-example.md
Labels: API-M-4.1.0

#5342 fixes https://github.com/wso2/docs-apim/issues/5317
  en/docs/reference/connectors/exporting-artifacts.md
  en/docs/reference/connectors/importing-connector-to-integration-studio.md
Labels: API-M-4.1.0
