Repository wso2/docs-apim, pull requests merged in 2022-03, with the labels that each got.

#5347 Update postman collection for APIM 4.0.0
  en/docs/reference/product-apis/overview.md
Labels: CEXP, API-M-4.0.0

#5348 Update postman collection for APIM 4.0.0
  en/docs/reference/product-apis/overview.md
Labels: CEXP, API-M-4.1.0

#5355 fixes https://github.com/wso2/docs-apim/issues/5273
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-insert-values-to-name-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-landing-page.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-resetsecurity-token-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-select-environment-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-select-pushtopic-account-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-select-single-record-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-slaesforce-login-workbench.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-streaming-push-topics-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-subscribe-updated.png
  en/docs/includes/reference/connectors/deploy-capp.md
  en/docs/includes/reference/connectors/exporting-artifacts.md
  en/docs/includes/reference/connectors/importing-connector-to-integration-studio.md
  en/docs/includes/reference/connectors/salesforce-connectors/sf-access-token-generation.md
  en/docs/reference/connectors/amazondynamodb-connector/amazondynamodb-connector-example.md
  en/docs/reference/connectors/amazonlambda-connector/amazonlambda-connector-example.md
  en/docs/reference/connectors/amazons3-connector/1.x/amazons3-connector-1.x-example.md
  en/docs/reference/connectors/amazons3-connector/amazons3-connector-example.md
  en/docs/reference/connectors/amazonsqs-connector/amazonsqs-connector-example.md
  en/docs/reference/connectors/bigquery-connector/bigquery-connector-example.md
  en/docs/reference/connectors/ceridiandayforce-connector/ceridiandayforce-connector-example.md
  en/docs/reference/connectors/documentum/documentum-example.md
  en/docs/reference/connectors/email-connector/email-connector-example.md
  en/docs/reference/connectors/fhir-connector/fhir-connector-example.md
  en/docs/reference/connectors/file-connector/3.x/file-connector-3.x-example.md
  en/docs/reference/connectors/file-connector/file-connector-example.md
  en/docs/reference/connectors/gmail-connector/gmail-connector-example.md
  en/docs/reference/connectors/google-firebase-connector/google-firebase-connector-example.md
  en/docs/reference/connectors/google-pubsub-connector/googlepubsub-connector-example.md
  en/docs/reference/connectors/google-spreadsheet-connector/google-spreadsheet-connector-example.md
  en/docs/reference/connectors/iso8583-connector/iso8583-connector-example.md
  en/docs/reference/connectors/jira-connector/jira-connector-example.md
  en/docs/reference/connectors/kafka-connector/kafka-connector-avro-producer-example.md
  en/docs/reference/connectors/kafka-connector/kafka-connector-producer-example.md
  en/docs/reference/connectors/ldap-connector/ldap-connector-example.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-connector-example.md
  en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
  en/docs/reference/connectors/redis-connector/redis-connector-example.md
  en/docs/reference/connectors/salesforce-connectors/salesforcebulk-connector-configuration.md
  en/docs/reference/connectors/salesforce-connectors/salesforcebulk-connector-example.md
  en/docs/reference/connectors/salesforce-connectors/sf-inbound-endpoint-configuration.md
  en/docs/reference/connectors/salesforce-connectors/sf-rest-connector-example.md
  en/docs/reference/connectors/salesforce-connectors/sf-soap-connector-config.md
  en/docs/reference/connectors/salesforce-connectors/sf-soap-connector-example.md
  en/docs/reference/connectors/salesforce-soap-connector/sf-soap-connector-config.md
  en/docs/reference/connectors/salesforce-soap-connector/sf-soap-connector-example.md
  en/docs/reference/connectors/salesforcebulk-connector/salesforcebulk-connector-configuration.md
  en/docs/reference/connectors/salesforcebulk-connector/salesforcebulk-connector-example.md
  en/docs/reference/connectors/servicenow-connector/servicenow-connector-example.md
  en/docs/reference/connectors/smpp-connector/smpp-connector-example.md
  en/mkdocs.yml
Labels: API-M-4.1.0

#5353 fixes https://github.com/wso2/docs-apim/issues/5273
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-insert-values-to-name-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-landing-page.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-resetsecurity-token-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-select-environment-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-select-pushtopic-account-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-select-single-record-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-slaesforce-login-workbench.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-streaming-push-topics-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-subscribe-updated.png
  en/docs/includes/reference/connectors/deploy-capp.md
  en/docs/includes/reference/connectors/exporting-artifacts.md
  en/docs/includes/reference/connectors/importing-connector-to-integration-studio.md
  en/docs/includes/reference/connectors/salesforce-connectors/sf-access-token-generation.md
  en/docs/reference/connectors/amazondynamodb-connector/amazondynamodb-connector-example.md
  en/docs/reference/connectors/amazonlambda-connector/amazonlambda-connector-example.md
  en/docs/reference/connectors/amazons3-connector/1.x/amazons3-connector-1.x-example.md
  en/docs/reference/connectors/amazons3-connector/amazons3-connector-example.md
  en/docs/reference/connectors/amazonsqs-connector/amazonsqs-connector-example.md
  en/docs/reference/connectors/bigquery-connector/bigquery-connector-example.md
  en/docs/reference/connectors/ceridiandayforce-connector/ceridiandayforce-connector-example.md
  en/docs/reference/connectors/documentum/documentum-example.md
  en/docs/reference/connectors/email-connector/email-connector-example.md
  en/docs/reference/connectors/fhir-connector/fhir-connector-example.md
  en/docs/reference/connectors/file-connector/3.x/file-connector-3.x-example.md
  en/docs/reference/connectors/file-connector/file-connector-example.md
  en/docs/reference/connectors/gmail-connector/gmail-connector-example.md
  en/docs/reference/connectors/google-firebase-connector/google-firebase-connector-example.md
  en/docs/reference/connectors/google-pubsub-connector/googlepubsub-connector-example.md
  en/docs/reference/connectors/google-spreadsheet-connector/google-spreadsheet-connector-example.md
  en/docs/reference/connectors/iso8583-connector/iso8583-connector-example.md
  en/docs/reference/connectors/jira-connector/jira-connector-example.md
  en/docs/reference/connectors/kafka-connector/kafka-connector-avro-producer-example.md
  en/docs/reference/connectors/kafka-connector/kafka-connector-producer-example.md
  en/docs/reference/connectors/ldap-connector/ldap-connector-example.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-connector-example.md
  en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
  en/docs/reference/connectors/redis-connector/redis-connector-example.md
  en/docs/reference/connectors/salesforce-connectors/salesforcebulk-connector-configuration.md
  en/docs/reference/connectors/salesforce-connectors/salesforcebulk-connector-example.md
  en/docs/reference/connectors/salesforce-connectors/sf-inbound-endpoint-configuration.md
  en/docs/reference/connectors/salesforce-connectors/sf-rest-connector-example.md
  en/docs/reference/connectors/salesforce-connectors/sf-soap-connector-config.md
  en/docs/reference/connectors/salesforce-connectors/sf-soap-connector-example.md
  en/docs/reference/connectors/salesforce-soap-connector/sf-soap-connector-config.md
  en/docs/reference/connectors/salesforce-soap-connector/sf-soap-connector-example.md
  en/docs/reference/connectors/salesforcebulk-connector/salesforcebulk-connector-configuration.md
  en/docs/reference/connectors/salesforcebulk-connector/salesforcebulk-connector-example.md
  en/docs/reference/connectors/servicenow-connector/servicenow-connector-example.md
  en/docs/reference/connectors/smpp-connector/smpp-connector-example.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#5358 fixes https://github.com/wso2/docs-apim/issues/5344
  en/mkdocs.yml
Labels: API-M-4.0.0

#5360 fixes https://github.com/wso2/docs-apim/issues/5344
  en/mkdocs.yml
Labels: API-M-4.0.0

#5346 Update script and trigger for AM_GW_API_ARTIFACTS table
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
Labels: API-M-3.2.0, CEXP

#5361 fixes https://github.com/wso2/docs-apim/issues/5344
  en/mkdocs.yml
Labels: API-M-4.1.0

#5365 fixes https://github.com/wso2/docs-apim/issues/5363
  en/mkdocs.yml
Labels: API-M-4.0.0

#5371 fixes https://github.com/wso2/docs-apim/issues/5356
  en/docs/install-and-setup/installation-guide/installing-the-product/installing-the-binary/installing-as-a-windows-service.md
Labels: API-M-3.0.0

#5370 fixes https://github.com/wso2/docs-apim/issues/5356
  en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-as-a-windows-service.md
Labels: API-M-3.1.0

#5369 fixes https://github.com/wso2/docs-apim/issues/5356
  en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-as-a-windows-service.md
Labels: API-M-3.2.0

#5368 fixes https://github.com/wso2/docs-apim/issues/5356
  en/docs/install-and-setup/install/installing-the-product/installing-api-m-as-a-windows-service.md
Labels: API-M-4.0.0

#5366 fixes https://github.com/wso2/docs-apim/issues/5363
  en/mkdocs.yml
Labels: API-M-3.2.0

#5373 [Master] Update MI certificate revocation configs
  en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md
  en/mkdocs.yml
Labels: API-M-4.1.0

#5374 [4.0.0] Update MI certificate revocation configs
  en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#5381 fixes https://github.com/wso2/docs-apim/issues/5273
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-enter-apex-code-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-execute-anonymous-window-updated.png
Labels: API-M-4.0.0

#5379 fixes https://github.com/wso2/docs-apim/issues/5273
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-enter-apex-code-updated.png
  en/docs/assets/img/integrate/connectors/salesforce-inboundep-execute-anonymous-window-updated.png
Labels: API-M-4.1.0

#5385 Updated algolia search
  en/theme/material/base.html
Labels: API-M-4.1.0

#5388 migrating to docsearch v3
  en/theme/material/base.html
Labels: API-M-4.1.0

#5389 migration to v3
  en/theme/material/base.html
Labels: API-M-4.1.0

#5393 Update producing-jms.md
  en/docs/integrate/examples/jms_examples/producing-jms.md
Labels: API-M-4.1.0

#5397 Add instructions to configure carbon datasource.
  en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores-mi.md
  en/docs/install-and-setup/setup/mi-setup/user_stores/setting_up_a_userstore.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.0.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.1.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.2.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.3.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.4.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.5.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.6.x.md
Labels: API-M-4.1.0

#5399 Update updating-wso2-api-manager.md
  en/docs/administer/updating-wso2-api-manager.md
Labels: API-M-4.1.0

#5398 Update updating-wso2-api-manager.md
  en/docs/administer/updating-wso2-api-manager.md
Labels: API-M-4.0.0

#5402 fixes https://github.com/wso2/docs-apim/issues/5400
  en/docs/administer/key-managers/configure-keycloak-connector.md
Labels: API-M-4.0.0

#5406 Restore search
  en/docs/assets/css/theme.css
  en/theme/material/base.html
  en/theme/material/partials/header.html
Labels: API-M-4.1.0

#5404 Migrating docsearch to v3
  .gitignore
  en/docs/assets/css/theme.css
  en/theme/material/base.html
  en/theme/material/partials/header.html
Labels: API-M-4.0.0

#5407 Migrating docsearch to v3
  .gitignore
  en/docs/assets/css/theme.css
  en/theme/material/base.html
  en/theme/material/partials/header.html
Labels: API-M-3.2.0

#5408 Migrating docsearch to v3
  .gitignore
  en/docs/assets/css/theme.css
  en/theme/material/base.html
  en/theme/material/partials/header.html
Labels: API-M-3.1.0

#5410 Migrating docsearch to v3
  .gitignore
  en/docs/assets/css/theme.css
  en/theme/material/base.html
  en/theme/material/partials/header.html
Labels: API-M-3.0.0

#5354 Update SNMP enabling steps
  en/docs/observe/micro-integrator/classic-observability-metrics/snmp-monitoring.md
Labels: PR-Review/Pending Resolution, API-M-4.0.0

#5301 Add docs of OPA validation in Choreo Connect
  en/docs/assets/img/deploy/mgw/choreo-connect-opa-overview.png
  en/docs/assets/img/deploy/mgw/configure-opa-policy.png
  en/docs/assets/img/design/security/opa-gateway-selection.png
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/extensions/custom-filters.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authorization/opa-validation.md
  en/docs/design/api-security/opa-validation/custom-opa-policy-for-choreo-connect.md
  en/docs/design/api-security/opa-validation/overview.md
  en/mkdocs.yml
Labels: docs/choreo-connect

#5405 Migrating docsearch to v3
  .gitignore
  en/theme/material/base.html
  en/theme/material/partials/header.html
Labels: API-M-4.1.0

#5418 reduced size of search icon and text
  en/docs/assets/css/theme.css
Labels: API-M-4.1.0

#5417 reduced size of search icon and text
  en/docs/assets/css/theme.css
Labels: API-M-4.0.0

#5415 fixed positioning of search
  en/docs/assets/css/theme.css
  en/mkdocs.yml
  en/theme/material/partials/header.html
Labels: API-M-3.0.0

#5414 fixed positioning of search
  en/docs/assets/css/theme.css
  en/mkdocs.yml
  en/theme/material/partials/header.html
Labels: API-M-3.1.0

#5413 fixed positioning of search
  en/docs/assets/css/theme.css
  en/mkdocs.yml
  en/theme/material/partials/header.html
Labels: API-M-3.2.0

#5429 Add data-source resource to management api
  en/docs/observe/mi-observe/working-with-management-api.md
Labels: CEXP

#5430 Add data-source resource to management api
  en/docs/observe/mi-observe/working-with-management-api.md
Labels: CEXP

#5438 Add documentation to enable file based artifact synchronization in 4.0.0
  en/docs/get-started/about-this-release.md
Labels: Docs/SyncPR-Pending, CEXP

#5442 fixes for https://github.com/wso2/docs-apim/issues/3963
  en/docs/assets/js/theme.js
Labels: API-M-4.0.0

#5441 fix for https://github.com/wso2/docs-apim/issues/3963
  en/docs/assets/js/theme.js
Labels: API-M-4.1.0

#5427 Fix proxy invocation URL
  en/docs/integrate/examples/jms_examples/dual-channel-http-to-jms.md
Labels: API-M-4.1.0

#5446 Update Salesforcerest API reference
  en/docs/reference/connectors/connector-usage.md
  en/docs/reference/connectors/salesforce-connectors/sf-rest-connector-config.md
Labels: API-M-4.1.0

#5448 fixes https://github.com/wso2/docs-apim/issues/5320
  en/docs/get-started/streaming-quick-start-guide.md
Labels: API-M-4.0.0

#5449 fixes https://github.com/wso2/docs-apim/issues/5443
  en/docs/tutorials/integration-tutorials/service-catalog-tutorial-for-proxy-services.md
  en/docs/tutorials/integration-tutorials/service-catalog-tutorial.md
Labels: API-M-4.1.0

#5447 fixes https://github.com/wso2/docs-apim/issues/5320
  en/docs/get-started/streaming-quick-start-guide.md
Labels: API-M-4.1.0

#5426 Fix proxy invocation URL
  en/docs/integrate/examples/jms_examples/dual-channel-http-to-jms.md
Labels: API-M-4.0.0

#5428 Update APIM 4.0.0 documentation to support the new CI/CD story via API Controller
  en/docs/assets/img/learn/api-controller/api-state.png
  en/docs/assets/img/learn/api-controller/apim-logs.png
  en/docs/assets/img/learn/api-controller/build-dev-now.png
  en/docs/assets/img/learn/api-controller/build-now.png
  en/docs/assets/img/learn/api-controller/cicd-jenkins-arch.png
  en/docs/assets/img/learn/api-controller/configure-system.png
  en/docs/assets/img/learn/api-controller/console-log-jenkins.png
  en/docs/assets/img/learn/api-controller/create-a-user.png
  en/docs/assets/img/learn/api-controller/create-file-git.png
  en/docs/assets/img/learn/api-controller/create-pipeline.png
  en/docs/assets/img/learn/api-controller/create-repository.png
  en/docs/assets/img/learn/api-controller/created-api.png
  en/docs/assets/img/learn/api-controller/customize-jenkins.png
  en/docs/assets/img/learn/api-controller/environment-variables.png
  en/docs/assets/img/learn/api-controller/global-variables.png
  en/docs/assets/img/learn/api-controller/jenkins-server-url.png
  en/docs/assets/img/learn/api-controller/repo-public-access.png
  en/docs/assets/img/learn/api-controller/select-repository.png
  en/docs/assets/img/learn/api-controller/select-webhooks.png
  en/docs/assets/img/learn/api-controller/set-event.png
  en/docs/assets/img/learn/api-controller/trigger-new-build.png
  en/docs/assets/img/learn/api-controller/two-versions.png
  en/docs/assets/img/learn/api-controller/webhook-trigger-plugin.png
  en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline-apictl.md
  en/mkdocs.yml
Labels: Docs/SyncPR-Pending, CEXP

#5453 Updated JDK for SI
  en/docs/install-and-setup/setup/reference/product-compatibility.md
Labels: API-M-4.0.0

#5451 fixes https://github.com/wso2/docs-apim/issues/5403
  en/docs/includes/design/create-streaming-api/create-a-websocket-streaming-api.md
Labels: API-M-4.0.0

#5454 Update the message processor configs.
  en/docs/integrate/examples/message_store_processor_examples/using-message-sampling-processor.md
Labels: API-M-4.0.0

#5459 Updated JDK for SI
  en/docs/install-and-setup/setup/reference/product-compatibility.md
Labels: API-M-4.1.0

#5439 fixes https://github.com/wso2/docs-apim/issues/4322
  en/docs/assets/img/deploy/mgw/choreo-connect-jwt-revocation.png
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/revoked-tokens.md
Labels: API-M-4.0.0, Docs/TW

#5440 fixes https://github.com/wso2/docs-apim/issues/4322
  en/docs/assets/img/deploy/mgw/choreo-connect-jwt-revocation.png
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/revoked-tokens.md
Labels: API-M-4.1.0

#5462 fix for https://github.com/wso2/docs-apim/issues/5396
  en/docs/consume/consume-api-overview.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md
  en/mkdocs.yml
Labels: API-M-4.1.0

#5463 fixes https://github.com/wso2/docs-apim/issues/5396
  en/docs/consume/consume-api-overview.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md
  en/docs/get-started/about-this-release.md
  en/mkdocs.yml
Labels: API-M-4.0.0

#5465 fixes fixes https://github.com/wso2/docs-apim/issues/5383
  en/docs/install-and-setup/setup/mi-setup/performance_tuning/tuning-inbound-endpoints.md
Labels: API-M-4.1.0

#5464 fixes https://github.com/wso2/docs-apim/issues/5383
  en/docs/install-and-setup/setup/mi-setup/performance_tuning/tuning-inbound-endpoints.md
Labels: API-M-4.0.0

#5467 fixes https://github.com/wso2/docs-apim/issues/4639
  en/docs/assets/attachments/103334399/103334401.png
  en/docs/install-and-setup/install/installing-the-product/installing-si.md
  en/docs/install-and-setup/setup/reference/product-compatibility.md
Labels: API-M-4.1.0

#5468 fixes https://github.com/wso2/docs-apim/issues/4639
  en/docs/assets/attachments/103334399/103334401.png
  en/docs/install-and-setup/install/installing-the-product/installing-si.md
  en/docs/install-and-setup/setup/reference/product-compatibility.md
Labels: API-M-4.0.0

#5241 Utility module (connector) documentation added
  en/docs/assets/img/integrate/connectors/utility-store.png
  en/docs/reference/connectors/utility-module/utility-module-config.md
  en/docs/reference/connectors/utility-module/utility-module-overview.md
  en/mkdocs.yml
Labels: PR-Review/In-progress, API-M-4.1.0

#5480 Update IS event handler jar
  en/docs/administer/key-managers/configure-wso2is-connector.md
  en/docs/assets/attachments/administer/wso2is-extensions-1.2.10.zip
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
Labels: CEXP

#5489 [choreo-connect] OPA naming fixes
  en/docs/assets/img/deploy/mgw/configure-opa-policy.png
  en/docs/design/api-security/opa-validation/overview.md
Labels: docs/choreo-connect

#5491 fixes A-1820
  en/docs/assets/css/theme.css
  en/docs/index.md
  en/theme/material/partials/header.html
Labels: Priority/Highest, API-M-3.2.0, CEXP

#5492 fixes A-1820
  en/docs/assets/css/theme.css
  en/docs/index.md
  en/theme/material/partials/header.html
Labels: Priority/Highest, API-M-3.1.0, CEXP

#5508 fixes https://github.com/wso2/docs-apim/issues/5232
  en/docs/assets/img/learn/prototype-api/backend-url-lifecycle.png
  en/docs/assets/img/learn/prototype-api/mock-impl-lifecycle.png
  en/docs/design/prototype-api/create-a-prototype-api.md
Labels: API-M-4.1.0

#5511 [CC 1.1.0] Update supported features
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md
Labels: API-M-4.1.0

#5501 Fix the login user names correctly
  en/docs/tutorials/scenarios/scenario-overview.md
Labels: API-M-4.0.0

#5516 Add ELK base analytics solution for APIM 4.0.0
  en/docs/api-analytics/cloud-analytics/elk-installation-guide.md
  en/docs/assets/img/analytics/cloud/add-new-role.png
  en/docs/assets/img/analytics/cloud/add-new-sp.png
  en/docs/assets/img/analytics/cloud/add-new-user.png
  en/docs/assets/img/analytics/cloud/architecture.png
  en/docs/assets/img/analytics/cloud/claim-config.png
  en/docs/assets/img/analytics/cloud/create-role-mapping.png
  en/docs/assets/img/analytics/cloud/export.ndjson
  en/docs/assets/img/analytics/cloud/inbound-auth-config.png
  en/docs/assets/img/analytics/cloud/login-apim.png
  en/docs/assets/img/analytics/cloud/login-elastic.png
  en/docs/assets/img/analytics/cloud/main-menu.png
  en/docs/assets/img/analytics/cloud/mapping-rules.png
  en/docs/assets/img/analytics/cloud/select-user-role.png
  en/docs/assets/img/analytics/cloud/service-providers.png
  en/docs/assets/img/analytics/cloud/update-settings.png
  en/mkdocs.yml
Labels: Docs/SyncPR-Pending, CEXP, API-M-4.0.0

#5421 added changes to read only user
  en/docs/assets/img/learn/api-security/assign-role-to-user.png
  en/docs/assets/img/learn/api-security/read-only-api-details.png
  en/docs/assets/img/learn/api-security/read-only-api-view.png
  en/docs/assets/img/learn/api-security/read-only-user-creation.png
  en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
Labels: API-M-4.1.0

#5517 Fix the login user names correctly
  en/docs/tutorials/scenarios/scenario-overview.md
Labels: API-M-4.1.0

#5520 Revert mkdocs changes made in Analytics
  en/docs/api-analytics/getting-started-guide.md
  en/docs/api-analytics/role-based-access-control.md
Labels: CEXP

#5521 Fix the config ordering issue
  en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md
Labels: Docs/SyncPR-Pending

#5531 fixed formatting issue
  en/docs/install-and-setup/setup/deployment-overview.md
Labels: API-M-4.1.0

#5530 Fix formatting issue
  en/docs/install-and-setup/setup/deployment-overview.md
Labels: API-M-4.0.0

#5539 added an entry for graphQL subscription
  en/docs/get-started/about-this-release.md
Labels: API-M-4.1.0

#5537 Update APIM 4.1.0 documentation to support the new CI/CD story via API Controller
  en/docs/assets/img/learn/api-controller/api-state.png
  en/docs/assets/img/learn/api-controller/apim-logs.png
  en/docs/assets/img/learn/api-controller/build-dev-now.png
  en/docs/assets/img/learn/api-controller/build-now.png
  en/docs/assets/img/learn/api-controller/cicd-jenkins-arch.png
  en/docs/assets/img/learn/api-controller/configure-system.png
  en/docs/assets/img/learn/api-controller/console-log-jenkins.png
  en/docs/assets/img/learn/api-controller/create-a-user.png
  en/docs/assets/img/learn/api-controller/create-file-git.png
  en/docs/assets/img/learn/api-controller/create-pipeline.png
  en/docs/assets/img/learn/api-controller/create-repository.png
  en/docs/assets/img/learn/api-controller/created-api.png
  en/docs/assets/img/learn/api-controller/customize-jenkins.png
  en/docs/assets/img/learn/api-controller/environment-variables.png
  en/docs/assets/img/learn/api-controller/global-variables.png
  en/docs/assets/img/learn/api-controller/jenkins-server-url.png
  en/docs/assets/img/learn/api-controller/repo-public-access.png
  en/docs/assets/img/learn/api-controller/select-repository.png
  en/docs/assets/img/learn/api-controller/select-webhooks.png
  en/docs/assets/img/learn/api-controller/set-event.png
  en/docs/assets/img/learn/api-controller/trigger-new-build.png
  en/docs/assets/img/learn/api-controller/two-versions.png
  en/docs/assets/img/learn/api-controller/webhook-trigger-plugin.png
  en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline.md
  en/mkdocs.yml
Labels: CEXP

#5541 Rename title of CI/CD story via API Controller doc
  en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline.md
  en/mkdocs.yml
Labels: CEXP

#5542 Hide Scenario tutorials in the Tutorials section temporarily
  en/docs/tutorials/tutorials-overview.md
  en/mkdocs.yml
Labels: API-M-4.1.0

#5529 PR review for https://github.com/wso2/docs-apim/pull/5272
  en/docs/assets/img/deploy/mgw/git-integration.png
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/git-integration.md
  en/docs/includes/deploy/cc-tryout-in-arm64-docker-note.md
  en/docs/includes/deploy/cc-tryout-in-arm64-k8s-note.md
  en/mkdocs.yml
  en/tools/config-catalog-generator-cc/data/adapter/configs.json
  en/tools/config-catalog-generator-cc/data/adapter/source_control.toml
  en/tools/config-catalog-generator-cc/dist/adapter-configurations.md
  en/tools/config-catalog-generator-cc/templates/index_adapter.njk
Labels: PR/Reviewer-Updated, API-M-4.1.0, docs/choreo-connect

#5548 fixes https://github.com/wso2/docs-apim/issues/5252
  en/docs/index.md
Labels: API-M-4.1.0

#5549 fixes https://github.com/wso2/docs-apim/issues/5252
  en/docs/index.md
Labels: API-M-4.0.0
