Repository wso2/docs-apim, pull requests merged in 2022-06, with the labels that each got.

#5929 fixes A-2118
  en/docs/assets/img/learn/okta-add-new-application-details.png
  en/docs/assets/img/learn/okta-add-new-application-web.png
  en/docs/assets/img/learn/okta-add-new-application.png
  en/docs/assets/img/learn/okta-add-new-attribute-add.png
  en/docs/assets/img/learn/okta-add-new-attribute-details.png
  en/docs/assets/img/learn/okta-add-new-attribute.png
  en/docs/assets/img/learn/okta-add-new-claims-role.png
  en/docs/assets/img/learn/okta-add-new-claims-user.png
  en/docs/assets/img/learn/okta-add-new-claims.png
  en/docs/assets/img/learn/okta-apim-add-role-permissions1.png
  en/docs/assets/img/learn/okta-apim-add-role-permissions2.png
  en/docs/assets/img/learn/okta-apim-add-role-permissions3.png
  en/docs/assets/img/learn/okta-apim-idp-odic-details.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit1.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit2.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit3.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit4.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit5.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit6.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit7.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui.png
  en/docs/assets/img/learn/okta-apim-role-permission-mapping-admin-ui-edit1.png
  en/docs/assets/img/learn/okta-apim-role-permission-mapping-admin-ui-edit2.png
  en/docs/assets/img/learn/okta-login.png
  en/docs/assets/img/learn/okta-profile-edit.png
  en/docs/assets/img/learn/okta-profile-edit2.png
  en/docs/assets/img/learn/okta-profile-edit3.png
  en/docs/assets/img/learn/scope-assignment-menu.png
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
Labels: CEXP, APIMINTERNAL, API-M-4.1.0

#5933 fixed wrong image
  en/docs/tutorials/integrating-with-solace.md
Labels: API-M-4.1.0

#5934 Fixed wrong image
  en/docs/tutorials/integrating-with-solace.md
Labels: API-M-Master

#5937 fixes A-2118
  en/docs/assets/img/learn/okta-add-new-application-details.png
  en/docs/assets/img/learn/okta-add-new-application-web.png
  en/docs/assets/img/learn/okta-add-new-application.png
  en/docs/assets/img/learn/okta-add-new-attribute-add.png
  en/docs/assets/img/learn/okta-add-new-attribute-details.png
  en/docs/assets/img/learn/okta-add-new-attribute.png
  en/docs/assets/img/learn/okta-add-new-claims-role.png
  en/docs/assets/img/learn/okta-add-new-claims-user.png
  en/docs/assets/img/learn/okta-add-new-claims.png
  en/docs/assets/img/learn/okta-apim-add-role-permissions1.png
  en/docs/assets/img/learn/okta-apim-add-role-permissions2.png
  en/docs/assets/img/learn/okta-apim-add-role-permissions3.png
  en/docs/assets/img/learn/okta-apim-idp-odic-details.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit1.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit2.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit3.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit4.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit5.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit6.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit7.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui.png
  en/docs/assets/img/learn/okta-apim-role-permission-mapping-admin-ui-edit1.png
  en/docs/assets/img/learn/okta-apim-role-permission-mapping-admin-ui-edit2.png
  en/docs/assets/img/learn/okta-login.png
  en/docs/assets/img/learn/okta-profile-edit.png
  en/docs/assets/img/learn/okta-profile-edit2.png
  en/docs/assets/img/learn/okta-profile-edit3.png
  en/docs/assets/img/learn/scope-assignment-menu.png
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
Labels: CEXP, API-M-4.0.0, APIMINTERNAL

#5935 fixes A-2118
  en/docs/assets/img/learn/okta-add-new-application-details.png
  en/docs/assets/img/learn/okta-add-new-application-web.png
  en/docs/assets/img/learn/okta-add-new-application.png
  en/docs/assets/img/learn/okta-add-new-attribute-add.png
  en/docs/assets/img/learn/okta-add-new-attribute-details.png
  en/docs/assets/img/learn/okta-add-new-attribute.png
  en/docs/assets/img/learn/okta-add-new-claims-role.png
  en/docs/assets/img/learn/okta-add-new-claims-user.png
  en/docs/assets/img/learn/okta-add-new-claims.png
  en/docs/assets/img/learn/okta-apim-add-role-permissions1.png
  en/docs/assets/img/learn/okta-apim-add-role-permissions2.png
  en/docs/assets/img/learn/okta-apim-add-role-permissions3.png
  en/docs/assets/img/learn/okta-apim-idp-odic-details.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit1.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit2.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit3.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit4.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit5.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit6.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui-edit7.png
  en/docs/assets/img/learn/okta-apim-role-pemission-mapping-admin-ui.png
  en/docs/assets/img/learn/okta-apim-role-permission-mapping-admin-ui-edit1.png
  en/docs/assets/img/learn/okta-apim-role-permission-mapping-admin-ui-edit2.png
  en/docs/assets/img/learn/okta-login.png
  en/docs/assets/img/learn/okta-profile-edit.png
  en/docs/assets/img/learn/okta-profile-edit2.png
  en/docs/assets/img/learn/okta-profile-edit3.png
  en/docs/assets/img/learn/scope-assignment-menu.png
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
Labels: API-M-Master, CEXP, APIMINTERNAL

#5942 removed note on SP-based analytics
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
Labels: CEXP, API-M-4.0.0, APIMINTERNAL

#5941 removed note on SP-based analytics
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
Labels: API-M-Master, CEXP, APIMINTERNAL

#5938 fixed note on tenant config
  en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
Labels: CEXP, APIMINTERNAL, API-M-4.1.0

#5945 fixes A-2120
  en/docs/consume/consume-api-overview.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/try-out-using-postman.md
  en/mkdocs.yml
Labels: CEXP, APIMINTERNAL, API-M-4.1.0

#5944 fixes A-2120
  en/docs/consume/consume-api-overview.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/try-out-using-postman.md
  en/mkdocs.yml
Labels: API-M-Master, CEXP, APIMINTERNAL

#5946 fixes A-2120
  en/docs/consume/consume-api-overview.md
  en/docs/consume/invoke-apis/invoke-apis-using-tools/try-out-using-postman.md
  en/mkdocs.yml
Labels: CEXP, API-M-4.0.0, APIMINTERNAL

#5947 fixes A-1454
  en/docs/learn/consume-api/generating-sdks/generate-sdks-in-dev-portal.md
Labels: API-M-3.2.0

#5949 fixes A-1615
  en/docs/assets/img/learn/click_custom_policy.png
  en/docs/assets/img/learn/throttling-custom-policy.png
  en/docs/learn/rate-limiting/advanced-topics/custom-throttling.md
Labels: API-M-3.2.0, CEXP, APIMINTERNAL

#5950 fixes A-1615
  en/docs/assets/img/learn/click_custom_policy.png
  en/docs/assets/img/learn/throttling-custom-policy.png
  en/docs/design/rate-limiting/advanced-topics/custom-throttling.md
Labels: CEXP, API-M-4.0.0, APIMINTERNAL

#5951 fixes A-1615
  en/docs/assets/img/learn/click_custom_policy.png
  en/docs/assets/img/learn/throttling-custom-policy.png
  en/docs/design/rate-limiting/advanced-topics/custom-throttling.md
Labels: CEXP, APIMINTERNAL, API-M-4.1.0

#5952 fixes A-1615
  en/docs/assets/img/learn/click_custom_policy.png
  en/docs/assets/img/learn/throttling-custom-policy.png
  en/docs/design/rate-limiting/advanced-topics/custom-throttling.md
Labels: API-M-Master, CEXP, APIMINTERNAL

#5953 improved update note
  en/docs/learn/consume-api/generating-sdks/generate-sdks-in-dev-portal.md
Labels: API-M-3.2.0, CEXP, APIMINTERNAL

#5956 fixes A-1454
  en/docs/learn/consume-api/generating-sdks/generate-sdks-in-dev-portal.md
Labels: API-M-3.2.0, CEXP, APIMINTERNAL

#5957 fixes A-1454
  en/docs/consume/generating-sdks/generate-sdks-in-dev-portal.md
Labels: CEXP, API-M-4.0.0, APIMINTERNAL

#5963 fixes A-274
  en/docs/assets/attachments/install-and-setup/apim200_to_apim320_gateway_artifact_migrator.sh
  en/docs/assets/attachments/install-and-setup/apim210_to_apim320_gateway_artifact_migrator.sh
  en/docs/assets/attachments/install-and-setup/apim220_to_apim320_gateway_artifact_migrator.sh
Labels: API-M-3.2.0, CEXP, APIMINTERNAL

#5975 [Master]- Remove APIM doc events
  en/docs/api-analytics/getting-started-guide.md
  en/docs/api-analytics/role-based-access-control.md
  en/docs/api-analytics/viewing/introduction-to-api-analytics-dashboard.md
  en/docs/assets/lib/insights/insights.js
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
  en/mkdocs.yml
Labels: API-M 4.2.0

#5973 [4.1.0]- Remove APIM doc events
  en/docs/api-analytics/getting-started-guide.md
  en/docs/api-analytics/role-based-access-control.md
  en/docs/api-analytics/viewing/introduction-to-api-analytics-dashboard.md
  en/docs/assets/lib/insights/insights.js
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
  en/mkdocs.yml
Labels: CEXP, API-M-4.1.0

#5977 fixes A-274
  en/docs/assets/attachments/install-and-setup/apim200_to_apim300_gateway_artifact_migrator.sh
  en/docs/assets/attachments/install-and-setup/apim210_to_apim300_gateway_artifact_migrator.sh
  en/docs/assets/attachments/install-and-setup/apim220_to_apim300_gateway_artifact_migrator.sh
Labels: API-M-3.0.0, CEXP, APIMINTERNAL

#5984 fixes Git issue A-114
  en/docs/install-and-setup/setup/reference/product-compatibility.md
Labels: API-M-3.2.0, CEXP, APIMINTERNAL

#5990 fixes A-119
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: API-M-Master, CEXP, APIMINTERNAL

#5989 fixes A-119
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: CEXP, APIMINTERNAL, API-M-4.1.0

#5988 fixes A-119
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: CEXP, API-M-4.0.0, APIMINTERNAL

#5987 fixes A-119
  en/docs/administer/key-managers/configure-wso2is-connector.md
  en/docs/assets/img/administer/add-key-manager.png
  en/docs/assets/img/administer/wso2is-km-configuration.png
Labels: API-M-3.2.0, CEXP, APIMINTERNAL

#5992 fixes A-2081
  en/docs/administer/key-managers/configure-wso2is-connector.md
  en/docs/assets/img/integrate/service-catalog/select-service-catalog.png
  en/docs/assets/img/integrate/service-catalog/select-services.png
  en/docs/design/create-api/create-an-api-using-a-service.md
Labels: CEXP, APIMINTERNAL, API-M-4.1.0

#5993 fixes A-2081
  en/docs/assets/img/integrate/service-catalog/select-service-catalog.png
  en/docs/assets/img/integrate/service-catalog/select-services.png
  en/docs/design/create-api/create-an-api-using-a-service.md
Labels: API-M-Master, CEXP, APIMINTERNAL

#5991 fixes A-2081
  en/docs/assets/img/integrate/service-catalog/select-service-catalog.png
  en/docs/assets/img/integrate/service-catalog/select-services.png
  en/docs/design/create-api/create-an-api-using-a-service.md
Labels: CEXP, APIMINTERNAL, 4.0.0-post

#5996 fixes E-1722
  en/docs/reference/mediators/data-mapper-mediator.md
Labels: CEXP, API-M-4.0.0, APIMINTERNAL

#5995 fixes E-1722
  en/docs/reference/mediators/data-mapper-mediator.md
Labels: API-M-Master, CEXP, APIMINTERNAL

#5998 fixes E-1134
  en/docs/assets/img/integrate/mediators/119131284/119131287.png
  en/docs/assets/img/integrate/mediators/119131284/autogen_config_files.png
  en/docs/reference/mediators/data-mapper-mediator.md
Labels: CEXP, API-M-4.0.0, APIMINTERNAL

#5999 fixes E-1134
  en/docs/assets/img/integrate/mediators/119131284/119131287.png
  en/docs/assets/img/integrate/mediators/119131284/autogen_config_files.png
  en/docs/reference/mediators/data-mapper-mediator.md
Labels: CEXP, APIMINTERNAL, API-M-4.1.0

#6000 fixes E-1134
  en/docs/assets/img/integrate/mediators/119131284/119131287.png
  en/docs/assets/img/integrate/mediators/119131284/autogen_config_files.png
  en/docs/reference/mediators/data-mapper-mediator.md
Labels: API-M-Master, CEXP, APIMINTERNAL

#5893 Add note
  en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
Labels: PR-Review/Pending Resolution, CEXP, API-M-4.0.0

#6011 fixes A-1230
  en/docs/reference/customize-product/customizations/customize-the-api-store-and-gateway-urls-for-tenants.md
Labels: API-M-Master, CEXP, APIMINTERNAL

#6010 fixes A-1230
  en/docs/reference/customize-product/customizations/customize-the-api-store-and-gateway-urls-for-tenants.md
Labels: CEXP, APIMINTERNAL, API-M-4.1.0

#6019 Update monitoring dashboard documentation with health check
  en/docs/observe/mi-observe/working-with-monitoring-dashboard.md
Labels: API-M-Master

#5986 [4.1.0] Add Istio service to service sample
  en/docs/assets/img/deploy/istio-east-west-traffic.png
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/service-mesh/istio.md
Labels: docs/choreo-connect

#6030 Fixes wso2-apim-internal/issues/132
  en/docs/reference/mediators/validate-mediator.md
Labels: CEXP, API-M-4.0.0, APIMINTERNAL

#6031 Fixes wso2-apim-internal/issues/132
  en/docs/reference/mediators/validate-mediator.md
Labels: API-M-Master, CEXP, APIMINTERNAL

#6039 [master] Add Istio service to service sample
  en/docs/assets/img/deploy/istio-east-west-traffic.png
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/service-mesh/istio.md
Labels: docs/choreo-connect

#6048 fixes Git A-132 review comments
  en/docs/reference/mediators/validate-mediator.md
Labels: CEXP, API-M-4.0.0, APIMINTERNAL

#6047 fixes Git A-132 review comments
  en/docs/reference/mediators/validate-mediator.md
Labels: CEXP, APIMINTERNAL, API-M-4.1.0

#6036 fixes Git A-132 review comments
  en/docs/reference/mediators/validate-mediator.md
Labels: API-M-Master, CEXP, APIMINTERNAL
