Repository wso2/docs-apim, pull requests merged in 2023-08, with the labels that each got.

#7163 Fix Performance Test Results Images
  en/docs/install-and-setup/setup/deployment-best-practices/performance-test-results-mi.md
Labels: API-M 4.2.0

#7165 Update Publisher REST API URL version to v4
  en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml
  en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml
  en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
Labels: API-M 4.2.0

#7182 Add missing in MI Analytics configurations doc
  en/docs/mi-analytics/setting-up-mi-analytics.md
Labels: Docs/SyncPR-Pending, API-M 4.2.0

#7181 Configuring customParameters without any parameters
  en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-different-endpoint-security-types.md
Labels: API-M-4.1.0

#7185 Remove invalid "What's Next" section
  en/docs/reference/connectors/amazondynamodb-connector/amazondynamodb-connector-example.md
  en/docs/reference/connectors/amazonlambda-connector/amazonlambda-connector-example.md
  en/docs/reference/connectors/amazonsqs-connector/amazonsqs-connector-example.md
  en/docs/reference/connectors/amazonsqs-connector/amazonsqs-inbound-endpoint-example.md
  en/docs/reference/connectors/bigquery-connector/bigquery-connector-example.md
  en/docs/reference/connectors/db-event-inbound-endpoint/db-event-inbound-endpoint-example.md
  en/docs/reference/connectors/documentum/documentum-example.md
  en/docs/reference/connectors/email-connector/email-connector-example.md
  en/docs/reference/connectors/fhir-connector/fhir-connector-example.md
  en/docs/reference/connectors/file-connector/3.x/file-connector-3.x-example.md
  en/docs/reference/connectors/file-connector/file-connector-example.md
  en/docs/reference/connectors/gmail-connector/gmail-connector-example.md
  en/docs/reference/connectors/google-firebase-connector/google-firebase-connector-example.md
  en/docs/reference/connectors/google-pubsub-connector/googlepubsub-connector-example.md
  en/docs/reference/connectors/google-spreadsheet-connector/google-spreadsheet-connector-example.md
  en/docs/reference/connectors/iso8583-connector/iso8583-connector-example.md
  en/docs/reference/connectors/iso8583-connector/iso8583-inbound-endpoint-example.md
  en/docs/reference/connectors/kafka-connector/kafka-connector-avro-producer-example.md
  en/docs/reference/connectors/kafka-connector/kafka-connector-producer-example.md
  en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-example.md
  en/docs/reference/connectors/ldap-connector/ldap-connector-example.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-connector-example.md
  en/docs/reference/connectors/redis-connector/redis-connector-example.md
  en/docs/reference/connectors/salesforce-connectors/salesforcebulk-connector-example.md
  en/docs/reference/connectors/salesforce-connectors/sf-rest-connector-example.md
  en/docs/reference/connectors/salesforce-connectors/sf-soap-connector-example.md
  en/docs/reference/connectors/salesforce-soap-connector/sf-soap-connector-example.md
  en/docs/reference/connectors/salesforcebulk-connector/salesforcebulk-connector-example.md
  en/docs/reference/connectors/servicenow-connector/servicenow-connector-example.md
  en/docs/reference/connectors/smpp-connector/smpp-connector-example.md
  en/docs/reference/connectors/smpp-connector/smpp-inbound-endpoint-example.md
Labels: API-M 4.2.0

#7188 Upload updated Custom Authentication Handler implementation to the Doc space
  en/docs/assets/attachments/reference/org.wso2.carbon.test.authenticator.zip
  en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md
Labels: API-M 4.2.0

#7189 [Sync PR] Upload updated Custom Authentication Handler implementation to the Doc space
  en/docs/assets/attachments/reference/org.wso2.carbon.test.authenticator.zip
  en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md
Labels: API-M-Master

#7177 Update Azure storage connector docs with client credentials authentication
  en/docs/assets/attachments/connectors/MSAzureStorageConnector.zip
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/adding_create_container_resource.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/adding_respond_mediator.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_add_blob_operation.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_blob_delete_operation.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_blob_download_operation.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_create_container_operation.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_delete_container_operation.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_list_metadata_operation.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_new_connection.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/create_new_connection_btn.png
  en/docs/integrate/integration-use-case/connectors.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/1.x/microsoft-azure-storage-connector-example.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/1.x/microsoft-azure-storage-reference.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/2.x/microsoft-azure-storage-connector-example.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/2.x/microsoft-azure-storage-reference.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-overview.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-configuration.md
  en/mkdocs.yml
Labels: API-M-Master

#7179 Add note about ports for server parameter
  en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/mutual-ssl-between-api-gateway-and-backend.md
Labels: Docs/SyncPR-Pending

#7190 Update Azure storage connector docs with client credentials authentication
  en/docs/assets/attachments/connectors/MSAzureStorageConnector.zip
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/adding_create_container_resource.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/adding_respond_mediator.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_add_blob_operation.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_blob_delete_operation.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_blob_download_operation.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_create_container_operation.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_delete_container_operation.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_list_metadata_operation.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/configure_new_connection.png
  en/docs/assets/img/integrate/connectors/msazure-connector-2x/create_new_connection_btn.png
  en/docs/integrate/integration-use-case/connectors.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/1.x/microsoft-azure-storage-connector-example.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/1.x/microsoft-azure-storage-reference.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/2.x/microsoft-azure-storage-connector-example.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/2.x/microsoft-azure-storage-reference.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-overview.md
  en/docs/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-configuration.md
  en/mkdocs.yml
Labels: MI-4.2.0

#7191 Access Tokens Per Device - JWT
  en/docs/consume/manage-application/generate-keys/obtain-access-token/access-tokens-per-device.md
Labels: API-M-4.1.0

#7200 [4.1.0] Update file-connector-3.x-config.md
  en/docs/reference/connectors/file-connector/3.x/file-connector-3.x-config.md
Labels: API-M-4.1.0

#7201 [Sync PR] Update file-connector-3.x-config.md
  en/docs/reference/connectors/file-connector/3.x/file-connector-3.x-config.md
Labels: API-M-Master

#7187 APIM 3.1.0 - Add note about additional `passthru_http` parameters
  en/docs/install-and-setup/setup/advance-configurations/changing-the-default-transport.md
Labels: API-M-3.1.0

#7180 Add Note - `Securing JWT Validation in User Info and Token Introspection Endpoints`
  en/docs/learn/api-security/openid-connect/obtaining-user-profile-information-with-openid-connect.md
Labels: API-M-3.2.0

#7211 Add missing information regarding token cleanup in APIM documentation
  en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
Labels: Docs/SyncPR-Pending, API-M-4.0.0

#7218 Add missing information regarding token cleanup in APIM documentation
  en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
Labels: API-M-4.1.0

#7217 Add missing information regarding token cleanup in APIM documentation
  en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
Labels: API-M 4.2.0
