Repository wso2/docs-apim, pull requests merged in 2023-03, with the labels that each got.

#6766 Update instructions to support Java 17
  en/docs/install-and-setup/install/installing-the-product/installing-mi-as-a-windows-service.md
Labels: API-M 4.2.0

#6772 Requirement to mount Solr directory is not mentioned in distributed setup
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
Labels: API-M-4.1.0

#6778 Fix formatting issues in Create and Publish a WebSub/WebHook API documentation
  en/docs/tutorials/streaming-api/create-and-publish-websub-api.md
Labels: API-M 4.2.0

#6779 Add missing resource
  en/docs/design/api-security/oauth2/grant-types/ntlm-grant.md
Labels: API-M 4.2.0

#6780 [4.2.0] Update Adding Scope Assignments Docs
  en/docs/administer/managing-users-and-roles/managing-user-roles.md
  en/docs/assets/img/administer/add-new-role-name.png
  en/docs/assets/img/administer/add-scope-to-role-mapping.png
  en/docs/assets/img/administer/map-existing-role.png
  en/docs/assets/img/administer/view-scope-assignments.png
Labels: API-M 4.2.0

#6783 [APIM][4.1.0] Update Enable Audit API for a single tenant configuration steps
  en/docs/assets/img/learn/advanced-config.png
  en/docs/design/api-security/configuring-api-security-audit.md
Labels: API-M-4.1.0

#6784 Add info to invoke graphql api by accepting the cert
  en/docs/tutorials/create-and-publish-a-graphql-api.md
Labels: API-M 4.2.0

#6788 Add enable secret generation step
  en/docs/assets/img/tutorials/streaming-api/enable-secret-generation.png
  en/docs/tutorials/streaming-api/create-and-publish-websub-api.md
Labels: API-M 4.2.0

#6785 Fix outdated information in Configure a Custom Key Manager page
  en/docs/administer/key-managers/configure-custom-connector.md
  en/docs/assets/img/administer/custom-keymanager/external-keymanager-form3.png
Labels: API-M 4.2.0

#6773 Requirement to mount Solr directory is not mentioned in distributed setup
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
Labels: API-M-4.0.0

#6796 Fix https://github.com/wso2/docs-apim/issues/6305
  en/docs/install-and-setup/setup/mi-setup/databases/setting-up-mysql.md
Labels: API-M-4.1.0

#6795 Fix https://github.com/wso2/docs-apim/issues/6305
  en/docs/install-and-setup/setup/mi-setup/databases/setting-up-mysql.md
Labels: API-M-4.0.0

#6799 Update note
  en/docs/mi-analytics/setting-up-mi-analytics.md
Labels: API-M-4.1.0

#6802 Update APIM quick start guide
  en/docs/assets/img/get_started/key-gen-wizard-1.png
  en/docs/get-started/api-manager-quick-start-guide.md
Labels: API-M 4.2.0

#6801 [4.1.0] Update APIM quick start guide
  en/docs/assets/img/get_started/key-gen-wizard-1.png
  en/docs/get-started/api-manager-quick-start-guide.md
Labels: API-M-4.1.0

#6805 [4.1.0] Update MI Quick Start Guide
  en/docs/assets/img/integrate/quick-start-guide/select-services.png
  en/docs/get-started/integration-quick-start-guide.md
Labels: API-M-4.1.0

#6767 Update Add a Third-party API doc
  en/docs/deploy-and-publish/publish-on-dev-portal/third-party-api-support.md
Labels: API-M 4.2.0

#6815 Improve Streaming Integrator Quick Start Guide
  en/docs/get-started/streaming-quick-start-guide.md
Labels: API-M-4.1.0

#6816 Improve Streaming Integrator Quick Start Guide
  en/docs/get-started/streaming-quick-start-guide.md
Labels: API-M-Master

#6819 Correct Payload Format for Using Publisher Rest API
  en/docs/reference/product-apis/publisher-apis/publisher-v3/publisher-v3.yaml
Labels: API-M-4.1.0

#6821 Update TLS version in toml config
  en/docs/install-and-setup/setup/deployment-best-practices/production-deployment-guidelines.md
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
  en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md
  en/docs/reference/faq.md
Labels: API-M-3.2.0

#6822 Fix broken link
  en/docs/design/api-security/oauth2/encrypting-oauth2-tokens.md
Labels: API-M-4.1.0

#6826 Fix the resource access control config for keymanager-operations/dcr/register POST method
  en/docs/administer/key-managers/configure-wso2is-connector.md
  en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Labels: API-M-4.0.0

#6828 Fix the resource access control config for keymanager-operations/dcr/register POST method
  en/docs/administer/key-managers/configure-wso2is-connector.md
Labels: API-M 4.2.0

#6829 Update db table names for when an access token is revoked
  en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
Labels: API-M 4.2.0

#6834 [Sync PR] Update db table names for when an access token is revoked
  en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
Labels: API-M-4.1.0

#6835 [Sync PR] Update db table names for when an access token is revoked
  en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
Labels: API-M-4.0.0

#6836 [Sync PR] Update db table names for when an access token is revoked
  en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
Labels: API-M-3.2.0

#6837 [Sync PR] Update db table names for when an access token is revoked
  en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
Labels: API-M-3.1.0

#6844 Update email connector docs with inlineImages parameter
  en/docs/reference/connectors/email-connector/email-connector-config.md
Labels: API-M-4.1.0

#6846 Fix broken URL
  en/docs/integrate/examples/jms_examples/consuming-jms.md
Labels: API-M-4.1.0

#6847 Fix formatting in Migrating Rate Limiting Policies to Different Environments
  en/docs/install-and-setup/setup/api-controller/managing-rate-limiting-policies/migrating-rate-limiting-policies-to-different-environments.md
Labels: API-M 4.2.0

#6845 Update email connector docs with inlineImages parameter
  en/docs/reference/connectors/email-connector/email-connector-config.md
Labels: API-M 4.2.0

#6843 Update 4.1.0 to 4.2.0
  en/docs/integrate/integration-overview.md
Labels: API-M 4.2.0

#6851 Subscription deletion workflow doc link [4.1.0]
  en/mkdocs.yml
Labels: API-M-4.1.0

#6848 Add note about SQL statement
  en/docs/use-cases/examples/streaming-examples/cdc-with-listening-mode.md
  en/docs/use-cases/streaming-tutorials/creating-etl-application-via-tooling.md
Labels: API-M 4.2.0

#6854 Update product-compatibility.md
  en/docs/install-and-setup/setup/reference/product-compatibility.md
Labels: API-M-4.0.0

#6853 Update product-compatibility.md
  en/docs/install-and-setup/setup/reference/product-compatibility.md
Labels: API-M-4.1.0

#6859 [Sync PR] Add missing configuration in cross tenant subscriptions doc
  en/docs/learn/design-api/advanced-topics/control-api-visibility-and-subscription-availability-in-developer-portal.md
Labels: API-M-3.2.0

#6858 [Sync PR] Add missing configuration in cross tenant subscriptions doc
  en/docs/design/advanced-topics/control-api-visibility-and-subscription-availability-in-developer-portal.md
Labels: API-M-4.0.0

#6857 [Sync PR] Add missing configuration in cross tenant subscriptions doc
  en/docs/design/advanced-topics/control-api-visibility-and-subscription-availability-in-developer-portal.md
Labels: API-M 4.2.0

#6874 Move the What Has Changed section to About this release page
  en/docs/get-started/about-this-release.md
Labels: API-M-4.1.0

#6875 Move the What Has Changed section to About this release page
  en/docs/get-started/about-this-release.md
Labels: API-M-4.0.0

#6876 Move the What Has Changed section to About this release page
  en/docs/getting-started/about-this-release.md
Labels: API-M-3.2.0

#6877 Move the What Has Changed section to About this release page
  en/docs/getting-started/about-this-release.md
Labels: API-M-3.1.0

#6879 Move the What Has Changed section to About this release page
  en/docs/getting-started/about-this-release.md
Labels: API-M-3.0.0

#6871 Move the What Has Changed section to About this release page
  en/docs/get-started/about-this-release.md
Labels: API-M 4.2.0

#6880 Add sample output which is seen when starting 'Gateway worker profile'.
  en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md
Labels: API-M 4.2.0

#6894 Mentioning about the removed publisher, devportal profiles
  en/docs/get-started/about-this-release.md
Labels: API-M 4.2.0

#6904 [4.1.0] Update Router debug memory steps for Docker Compose
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md
Labels: docs/choreo-connect

#6906 [4.0.0] Update Router debug memory steps for Docker Compose
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md
Labels: docs/choreo-connect

#6905 [master] Update Router debug memory steps for Docker Compose
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md
Labels: docs/choreo-connect

#6907 [master] Update Choreo Connect Helm Deployment Guide
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-with-custom-hostnames.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md
Labels: docs/choreo-connect

#6899 Update supported cipher suites in product documentations
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: API-M-4.1.0

#6910 [4.2.0] Changes for release
  README.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/faq.md
  en/docs/includes/work-in-progress.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-apim-4.0.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.0.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.1.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.2.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.3.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.4.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.5.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.6.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.0.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.1.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-esb-5.x.x.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/what-has-changed.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/what-has-changed.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-api-manager.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-191-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-guidelines.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-to-log4j2.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-500-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-510-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-si/migrating-from-stream-processor.md
  en/docs/install-and-setup/upgrading-wso2-si/upgrading-from-previous-version.md
  en/mkdocs.yml
  en/theme/material/base.html
  en/theme/material/partials/header.html
Labels: API-M 4.2.0

#6911 Sync with master
  README.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/faq.md
  en/docs/includes/work-in-progress.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-apim-4.0.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.0.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.1.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.2.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.3.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.4.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.5.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.6.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.0.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.1.x.md
  en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-esb-5.x.x.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/what-has-changed.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/what-has-changed.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-api-manager.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-191-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-410.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-guidelines.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-to-log4j2.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-500-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-510-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
  en/docs/install-and-setup/upgrading-wso2-si/migrating-from-stream-processor.md
  en/docs/install-and-setup/upgrading-wso2-si/upgrading-from-previous-version.md
  en/mkdocs.yml
  en/theme/material/base.html
  en/theme/material/partials/header.html
Labels: API-M 4.2.0

#6915 Update the About this Release page
  en/docs/get-started/about-this-release.md
Labels: API-M 4.2.0

#6919 Fix for versions drop down
  en/docs/assets/versions.json
Labels: API-M 4.2.0

#6920 Fix code block showing in page
  en/docs/index.md
Labels: API-M 4.2.0

#6921 [4.2.0] Document `mountAs` in Choreo Connect Helm chart in Prod Guide
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
Labels: docs/choreo-connect

#6939 Update the documentation on cert bound access token with only token validation support
  en/docs/design/api-security/api-authentication/securing-apis-using-certificate-bound-access-tokens.md
Labels: API-M-4.0.0

#6938 Update the documentation on cert bound access token with only token validation support
  en/docs/design/api-security/api-authentication/securing-apis-using-certificate-bound-access-tokens.md
Labels: API-M-4.1.0

#6936 Update the documentation on cert bound access token with only token validation support
  en/docs/design/api-security/api-authentication/securing-apis-using-certificate-bound-access-tokens.md
Labels: API-M 4.2.0
