Repository wso2/docs-apim, pull requests merged in 2023-07, with the labels that each got.

#7119 Remove sample OpenTracing doc
  en/docs/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing.md
Labels: API-M-3.2.0

#7118 Remove sample OpenTracing doc
  en/docs/observe/api-manager/traces/monitoring-with-opentracing.md
Labels: API-M-4.0.0

#7127 Add Configure client authentication section
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Labels: API-M-Master

#7132 [3.1.0] Add Configure client authentication section
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Labels: API-M-3.1.0

#7133 [3.0.0] Add Configure client authentication section
  en/docs/install-and-setup/deploying-wso2-api-manager/security-guidelines-for-production-deployment.md
Labels: API-M-3.0.0

#7128 [4.2.0] Add Configure client authentication section
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Labels: API-M 4.2.0

#7129 [4.1.0] Add Configure client authentication section
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Labels: API-M-4.1.0

#7131 [3.2.0] Add Configure client authentication section
  en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Labels: API-M-3.2.0

#7114 [3.1.0] Install GA4 tracking code to APIM docs
  en/theme/material/main.html
Labels: API-M-3.1.0

#7113 [3.2.0] Install GA4 tracking code to APIM docs
  en/theme/material/main.html
Labels: API-M-3.2.0

#7111 [4.1.0] Install GA4 tracking code to APIM docs
  en/theme/material/main.html
Labels: API-M-4.1.0

#7112 [4.0.0] Install GA4 tracking code to APIM docs
  en/theme/material/main.html
Labels: API-M-4.0.0

#7098 Add note for OData Feature
  en/docs/integrate/examples/data_integration/odata-service.md
Labels: API-M-Master

#7137 Remove Google Fonts
  en/docs/index.md
  en/docs/integrate/integration-overview.md
  en/docs/streaming/streaming-overview.md
  en/theme/material/base.html
Labels: API-M-Master

#7140 Remove Google Fonts
  en/docs/index.md
  en/docs/integrate/integration-overview.md
  en/docs/streaming/streaming-overview.md
  en/theme/material/base.html
Labels: API-M-4.0.0

#7139 Remove Google Fonts
  en/docs/index.md
  en/docs/integrate/integration-overview.md
  en/docs/streaming/streaming-overview.md
  en/theme/material/base.html
Labels: API-M-4.1.0

#7142 Remove Google Fonts
  en/docs/index.md
  en/theme/material/base.html
Labels: API-M-3.2.0

#7147 SMBv2/v3 support of VFS transport
  en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md
Labels: API-M 4.2.0

#7148 SMBv2/v3 support of VFS transport
  en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md
Labels: API-M-4.1.0

#7149 SMBv2/v3 support of VFS transport
  en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md
Labels: API-M-Master

#7150 Update APICTL 3.2.7 Artifacts in the Docs
  en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
Labels: API-M-3.2.0

#7144 Remove Google Fonts
  en/docs/index.md
  en/theme/material/base.html
Labels: API-M-3.0.0

#7143 Remove Google Fonts
  en/docs/index.md
  en/theme/material/base.html
Labels: API-M-3.1.0

#7116 Fixes analytics link in 2 pages
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md
  en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
Labels: Docs/SyncPR-Pending
