Repository wso2/docs-apim, pull requests merged in 2023-01, with the labels that each got.

#6579 Fix runtime config image with correct screenshot
  en/docs/assets/img/learn/runtime-configs.png
Labels: API-M-4.1.0

#6580 Fix runtime config image with correct screenshot
  en/docs/assets/img/learn/runtime-configs.png
Labels: API-M 4.2.0

#6573 fixes A1487
  en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
Labels: APIMINTERNAL, API-M-4.1.0

#6574 fixes A1487
  en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
Labels: APIMINTERNAL, API-M 4.2.0

#6575 fixes A1487
  en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
Labels: API-M-4.0.0, APIMINTERNAL

#6576 fixes A1487
  en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
Labels: API-M-3.2.0, APIMINTERNAL

#6577 fixes A1487
  en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
Labels: API-M-3.1.0, APIMINTERNAL

#6578 fixes A1487
  en/docs/install-and-setup/supported-cipher-suites.md
Labels: API-M-3.0.0, APIMINTERNAL

#6420 [master] Organize cc config location info for all configs
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
Labels: API-M-Master, docs/choreo-connect

#6584 fixes A1487
  en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
Labels: API-M 4.2.0

#6415 [master] Update for cc Enforcer's dropins folder with helm artifacts
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/extensions/custom-filters.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/support-custom-claims-mapping.md
Labels: API-M-Master, docs/choreo-connect

#6585 Update the runtime config image with the correct screenshot
  en/docs/assets/img/learn/runtime-configs.png
Labels: API-M 4.2.0

#6452 Updating 3.2.0 migration docs
  en/docs/assets/attachments/install-and-setup/apim110_to_apim320_gateway_artifact_migrator.sh
  en/docs/assets/attachments/install-and-setup/apim200_to_apim320_gateway_artifact_migrator.ps1
  en/docs/assets/attachments/install-and-setup/apim200_to_apim320_gateway_artifact_migrator.sh
  en/docs/assets/attachments/install-and-setup/apim200_to_apim320_gateway_artifact_migrator_for_tenants.ps1
  en/docs/assets/attachments/install-and-setup/apim210_to_apim320_gateway_artifact_migrator.ps1
  en/docs/assets/attachments/install-and-setup/apim210_to_apim320_gateway_artifact_migrator.sh
  en/docs/assets/attachments/install-and-setup/apim210_to_apim320_gateway_artifact_migrator_for_tenants.ps1
  en/docs/assets/attachments/install-and-setup/apim220_to_apim320_gateway_artifact_migrator.ps1
  en/docs/assets/attachments/install-and-setup/apim220_to_apim320_gateway_artifact_migrator.sh
  en/docs/assets/attachments/install-and-setup/apim220_to_apim320_gateway_artifact_migrator_for_tenants.ps1
  en/docs/assets/attachments/install-and-setup/migration-resources.zip
  en/docs/assets/attachments/install-and-setup/migration-scripts.zip
  en/docs/assets/attachments/install-and-setup/org.wso2.carbon.apimgt.migrate.client-3.2.0-2.jar
  en/docs/assets/attachments/install-and-setup/reg-index.sql
  en/docs/assets/attachments/install-and-setup/tenantloader-1.0.jar
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-api-manager.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-191-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-process.md
  en/mkdocs.yml
Labels: API-M-3.2.0

#6600 Fixed about this release link
  en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-api-manager.md
Labels: API-M-3.2.0

#6613 Mentioned support for TLSv1.3
  en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
Labels: API-M-Master

#6612 Mentioned support for TLSv1.3
  en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
Labels: API-M 4.2.0

#6611 Mentioned support for TLSv1.3
  en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
Labels: API-M-4.0.0

#6610 Mentioned support for TLSv1.3
  en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
Labels: API-M-4.1.0

#6614 Add changes missed when resolving conflicts
  en/mkdocs.yml
Labels: API-M-4.0.0

#6619 Fixing redirection links
  en/mkdocs.yml
Labels: API-M-4.1.0

#6620 updated ZIP for A1633
  en/docs/assets/attachments/administer/wso2is-km-connector-u2.zip
Labels: API-M-3.2.0

#6625 [4.2.0 Sync] Update k8s-api-operator.md
  en/docs/reference/k8s-operators/k8s-api-operator.md
Labels: API-M 4.2.0

#6630 Updated Copyrights
  en/theme/material/partials/footer.html
Labels: API-M-4.1.0

#6635 Updated Copyrights
  en/theme/material/partials/footer.html
Labels: API-M-3.0.0
