Repository wso2/docs-apim, pull requests merged in 2023-06, with the labels that each got.

#7062 Add a note about the naming convention for the soap-to-rest feature
  en/docs/integrate/develop/creating-artifacts/creating-an-api.md
Labels: MI-4.2.0

#7063 Add a note about the naming convention for the soap to rest feature
  en/docs/integrate/develop/creating-artifacts/creating-an-api.md
Labels: API-M-Master

#7066 Update script mediator doc
  en/docs/reference/mediators/script-mediator.md
Labels: API-M 4.2.0

#7065 [CC 1.0.0.20] Add Mutual SSL Authentication support for CC as an update
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md
  en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/mutual-ssl-authentication.md
  en/docs/deploy-and-publish/deploy-on-gateway/deploying-apis-in-api-gateway-vs-choreo-connect.md
  en/docs/design/api-security/api-authentication/secure-apis-using-mutual-ssl.md
  en/docs/includes/design/create-mtls-api.md
  en/docs/includes/design/handling-mtls-ssl-termination.md
  en/docs/includes/design/invoke-mtls-api-using-postman.md
  en/mkdocs.yml
  en/tools/config-catalog-generator-cc/data/enforcer/configs.json
  en/tools/config-catalog-generator-cc/data/enforcer/mutual_ssl.toml
  en/tools/config-catalog-generator-cc/data/router/configs.json
  en/tools/config-catalog-generator-cc/data/router/downstream_tls.toml
  en/tools/config-catalog-generator-cc/dist/control-plane-configurations.md
  en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md
  en/tools/config-catalog-generator-cc/dist/router-configurations.md
  en/tools/config-catalog-generator-cc/package-lock.json
Labels: docs/choreo-connect

#7081 Add kafka inbound endpoint basic authentication parameters
  en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-example.md
Labels: API-M 4.2.0

#7085 Update VFS docs with 'transport.vfs.UpdateLastModified' parameter
  en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
Labels: MI-4.2.0

#7086 Update VFS docs with 'transport.vfs.UpdateLastModified' parameter
  en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
Labels: API-M-4.1.0

#7087 Update VFS docs with 'transport.vfs.UpdateLastModified' parameter
  en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
Labels: API-M-Master

#7095 Fix formatting in `Add a Third-party API` doc
  en/docs/deploy-and-publish/publish-on-dev-portal/third-party-api-support.md
Labels: API-M 4.2.0

#7100 Fix broken attachment download
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: API-M 4.2.0

#7103 Fix broken attachment download
  en/docs/assets/attachments/admin/testsslserver-jar.zip
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: API-M-4.1.0

#7105 [Sync PR] Remove Service MBeans section + Fix link
  en/docs/observe/api-manager/metrics/jmx-based-monitoring.md
  en/docs/reference/connectors/salesforce-connectors/sf-overview.md
Labels: API-M-Master

#7104 Remove Service MBeans section + Fix link
  en/docs/observe/api-manager/metrics/jmx-based-monitoring.md
  en/docs/reference/connectors/salesforce-connectors/sf-overview.md
Labels: API-M 4.2.0

#7106 Fix link
  en/docs/reference/connectors/salesforce-connectors/sf-overview.md
Labels: API-M-4.1.0

#7110 [master] Install GA4 tracking code to APIM docs
  en/theme/material/main.html
Labels: API-M-Master

#7115 [3.0.0] Install GA4 tracking code to APIM docs
  en/theme/material/main.html
Labels: API-M-3.0.0

#7102 [Sync PR] Fix attachment download
  en/docs/assets/attachments/admin/testsslserver-jar.zip
  en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Labels: API-M-Master
